### ISSUE TITLE
This Region has a quota of 0 instances for your subscription

### ISSUE THREAD

**Issue by devwheel** [OfficeDev/microsoft-teams-emergency-operations-center#100]
When deploying the arm template to azure I get this error:

`{"code":"InvalidTemplateDeployment","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"SubscriptionIsOverQuotaForSku","message":"This region has quota of 0 instances for your subscription. Try selecting different region or SKU."}]}],"message":"The template deployment 'Microsoft.Template-20230511132206' is not valid according to the validation procedure. The tracking id is '7c4a3b33-2221-4914-9c79-324bf78b38dc'. See inner errors for details."}`

**Comment by devwheel** [comment]
It is only the simpleAuthProvision Resource that fails - can I manually create?

**Comment by v-prigunasek** [comment]
Hi @devwheel ,

Thanks for reaching out to us. 
Could you please try to deploy by choosing different region and see if it works? Thanks!

**Comment by Nagamani20** [comment]
when deploying python web app in azure portal am getting error like this

{"code":"InvalidTemplateDeployment","details":[{"code":"ValidationForResourceFailed","message":"Validation failed for a resource. Check 'Error.Details[0]' for more information.","details":[{"code":"RegionClosedForSubscription","message":"The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option."}]}],"message":"The template deployment 'Microsoft.Web-WebApp-Portal-1ed8a1c1-88ce' is not valid according to the validation procedure. The tracking id is 'f72748c2-0229-4d38-86fe-d1c57739d40a'. See inner errors for details."}
