### ISSUE TITLE
If I need to update the app secret of the app regist

### ISSUE THREAD

**Issue by shiu701129** [OfficeDev/microsoft-teams-emergency-operations-center#105]
If I need to update the App secret of the App regist, 
do I just need to update the value of the configuration Client_Secret of the SimpleAuth App Service?
Thanks!
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/22926315/05118c2e-5e6f-4783-a234-451af166c07c)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/22926315/aa83c0cc-d443-4cc5-8893-e1f68e152e78)

**Comment by v-prigunasek** [comment]
Hi @shiu701129 ,

Thanks for reaching out to us. Yes, that is correct. You need to update the Client_Secret app setting and save it to restart the service.
