### ISSUE TITLE
Updated, but have same issue as before

### ISSUE THREAD

**Issue by PGSEOC** [OfficeDev/microsoft-teams-emergency-operations-center#106]
Once we create an incident, it just spins for a long duration and its hit or miss if the incident sticks. Once they do stick, meaning we have incidents showing up on our dashboard, they cannot be edited or adjusted in any way. When you click the edit icon next to the incident, it just spins constantly with nothing opening.

**Comment by v-prigunasek** [comment]
Hi @PGSEOC,

Thanks for reaching out.
Can you please confirm this setting from your tenant?  (SharePoint Admin Center --> Settings --> Site creation-->Create teams site under)

Could you please share me the following details for further troubleshooting on this issue?
1. Replicate the issue in browser version of teams by creating new incident and share me the console logs and network trace.
2. Screenshot of the TEOC dashboard.
3. Screenshot of the site contents page form the TEOC SharePoint site.

**Comment by PGSEOC** [comment]
See below screenshots. Can I get some guidance on completing #1? Thanks!

Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by PGSEOC** [comment]
#1 below (If I did it right).

Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by v-prigunasek** [comment]
Hi @PGSEOC ,

I haven't received any attachments or screenshots as you replied via email. Could you please respond to this issue with those details here in GitHub repo? Thanks!

**Comment by PGSEOC** [comment]
I put screenshots on there… If this isn’t working, can we please schedule a meeting so the correct players can be on the call to get this fixed?
+ Frank, Gil, and Marlon

Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by v-prigunasek** [comment]
We noticed the issue is due to the managed path set to ../teams in their tenant. Had a call with the customer and guided them through the upgrade steps for 2.0 version. The app was upgraded successfully and now the incidents are getting created and updated without any issues.
