### ISSUE TITLE
How to update from Version 1 to 2

### ISSUE THREAD

**Issue by devansinleesburgva** [OfficeDev/microsoft-teams-emergency-operations-center#107]
I installed version 1 a few months ago.  Do I have to go through the whole process again to update to version 2 or is there a simpler way?

**Comment by v-prigunasek** [comment]
Hi @devansinleesburgva ,

Thanks for reaching out to us. You can follow this wiki [guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version) to upgrade from 1.0 to 2.0 version.

**Comment by v-prigunasek** [comment]
Closing this ticket as there is another issue (110) opened for the queries /issues in the upgrade process.
