### ISSUE TITLE
TEOC Deployment Issue

### ISSUE THREAD

**Issue by SteveWedge** [OfficeDev/microsoft-teams-emergency-operations-center#108]
Hi, I am having a problem with the initial deployment of this solution. When running the provisioning script, EOC-Provision.ps1, the process consistently fails at the point where it is attempting to create lists for the site. I tried this with an existing site, supplying the last part of the SharePoint site URL and also tried with new sites where I excluded any special characters from the site name that was entered, see the example screenshot below.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/13b58f11-b9c1-45a6-8b50-398c77039ca4)

I have been persuading the client's business team that this is a viable option to meet their requirements, so not being able to deploy it will be quite embarrassing. I don't think that I'm doing anything wrong, the sites exist, so I can only assume there is a problem with the characters in the list names which are being created. I don't see any lists against the site.

Additionally, I note that it is not possible to deploy this solution against an existing site which has been deployed to .../teams , it will only work where the existing site was created under .../sites.

**Comment by v-prigunasek** [comment]
Hi @SteveWedge ,

Thanks for reaching out to us. I see there is double quotes added in the xml file path parameter. Can you please delete this site from SP admin center from both active and deleted sites and then re-run the script? Make sure to provide the XML path WITHOUT double quotes. In case if you are still getting any other error, I would recommend you to copy the "provisioning" folder to desktop and try it once, as I see the path name is too long as well.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/d0d62052-7304-48ce-a980-b9109fb88d55)

Currently, the application is supported only for the site provisioned under ../sites and not under ../teams. We will take this into consideration and check for the feasibility to implement that feature.

**Comment by SteveWedge** [comment]
Thanks for the prompt response. Clearly the solution doesn't support file paths which contain spaces, as that is why the path was contained within quotes. I find that quite surprising!

Anyway, I moved the whole deployment code so that it sits under the C: drive, otherwise it would never work be able to run successfully from my desktop. However, I still get a an error upon installation and given that this is a site which has been created by the provisioning process, I cannot see why this should be an issue.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/558ed7ec-a56d-4aba-a531-f1d59fb686cd)

As you can see the error states "**A list, survey, discussion board, or document library with the specified title already exists in this Web site.  Please choose another title.**". 

Please advise on next steps for resolution

**Comment by v-prigunasek** [comment]
We noticed the issue is due to the managed path set to ../teams in their tenant. Had a call with the customer and guided them through the upgrade steps for 2.0 version. The app was upgraded successfully and now the incidents are getting created and updated without any issues.

**Comment by v-prigunasek** [comment]
Hi @SteveWedge ,

I tried to run the script from my end and couldn't replicate this error. I believe this error might be kind of glitch. 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/922498b0-0653-4f71-a62b-1f0fa5f12711)

Can you please delete the site from SP admin center from both active and deleted sites and re-run the script again? Thanks

**Comment by SteveWedge** [comment]
Looks like it was a glitch, I ran the script again, this morning, and it completed successfully this time.

Thanks for your input!

Now for the rest of the setup!

**Comment by v-prigunasek** [comment]
That sounds good!

Quick summary -
Error Message - Illegal Characters in Path.
Resolution - The issue was due to the double quotes present in the XML path and after removing that, the script ran successfully.

**Comment by SteveWedge** [comment]
Yes, but its important to note that the path also cannot contain spaces, which technically are no longer illegal characters in a file path.
