### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by jhuard12** [OfficeDev/microsoft-teams-emergency-operations-center#109]
The app is installed and then when I attempt to launch, it asked me to "log in" but will to log in.  I get the following error: 

Request Id: 73cb1fe2-42ae-49cc-8bed-62623501cf00
Correlation Id: a48e6314-e347-46ab-b73a-5fa996496547
Timestamp: 2023-06-14T18:47:39Z
Message: AADSTS700016: Application with identifier '50f9fe1f-b469-446f-8132-5df6416db0e9' was not found in the directory 'Contoso'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by v-prigunasek** [comment]
Hi @jhuard12,

Thanks for reaching out to us. I believe there might be some issue with the client id/tenant id configuration in the resource group. Can you please go through all the steps from the [deployment guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide) once and make sure all the values from the app registration are correctly configured in the resource group (Configuration in the app service and simpleAuth app service)?

**Comment by v-prigunasek** [comment]
Closed due to inactivity. If this is still an issue, please create a new issue.
