### ISSUE TITLE
Error when uploading Teams app

### ISSUE THREAD

**Issue by eendrulat** [OfficeDev/microsoft-teams-emergency-operations-center#11]
I updated the local manifest file according to the instructions, zipped and uploaded to the Teams Admin center. When I do this, I get the following error:

> ##Mgmt.AppCatalog.LOBApp.Upload.BadRequest.UnknownTeamsAppManifestExceptionType

**Comment by eendrulat** [comment]
My manifest is below

`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "0.5",
  "id": "bef61400-db9b-41d4-a617-403deb7bbe77",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams Customer Advocacy Group",
    "websiteUrl": "https://aka.ms/teamsapptemplates",
    "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
  },
  "icons": {
    "color": "resources/color.png",
    "outline": "resources/outline.png"
  },
  "name": {
    "short": "TEOC",
    "full": "Microsoft Teams Emergency Operations Center (Preview)"
  },
  "description": {
    "short": "Microsoft Teams Emergency Operation Center (Preview)",
    "full": "The Microsoft Teams Emergency Operations Center (TEOC) solution template leverages the power of the Microsoft 365 platform to centralize incident response, information sharing and field communications using powerful services like Microsoft Lists, SharePoint and more. An open-source solution supported by Microsoft it provides core functionality out of the box or can be extended to meet specific agency requirements."
  },
  "accentColor": "#FFFFFF",
  "bots": [],
  "composeExtensions": [],
  "configurableTabs": [
    {
      "configurationUrl": "https://teoc.azurewebsites.net/index.html#/config",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Teams EOC",
      "contentUrl": "https://teoc.azurewebsites.net/index.html#/tab",
      "websiteUrl": "https://teoc.azurewebsites.net/index.html#/tab",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "teoc.azurewebsites.net/"
  ],
  "webApplicationInfo": {
    "id": "6eede4f0-da4c-4fca-ae6d-651d52b8ceee",
    "resource": "api://teoc.azurewebsites.net/6eede4f0-da4c-4fca-ae6d-651d52b8ceee"
  }
}`

**Comment by eendrulat** [comment]
Contents of Manifest file copied below

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "0.5",
  "id": "bef61400-db9b-41d4-a617-403deb7bbe77",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams Customer Advocacy Group",
    "websiteUrl": "https://aka.ms/teamsapptemplates",
    "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
  },
  "icons": {
    "color": "resources/color.png",
    "outline": "resources/outline.png"
  },
  "name": {
    "short": "TEOC",
    "full": "Microsoft Teams Emergency Operations Center (Preview)"
  },
  "description": {
    "short": "Microsoft Teams Emergency Operation Center (Preview)",
    "full": "The Microsoft Teams Emergency Operations Center (TEOC) solution template leverages the power of the Microsoft 365 platform to centralize incident response, information sharing and field communications using powerful services like Microsoft Lists, SharePoint and more. An open-source solution supported by Microsoft it provides core functionality out of the box or can be extended to meet specific agency requirements."
  },
  "accentColor": "#FFFFFF",
  "bots": [],
  "composeExtensions": [],
  "configurableTabs": [
    {
      "configurationUrl": "https://teoc.azurewebsites.net/index.html#/config",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Teams EOC",
      "contentUrl": "https://teoc.azurewebsites.net/index.html#/tab",
      "websiteUrl": "https://teoc.azurewebsites.net/index.html#/tab",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "teoc.azurewebsites.net/"
  ],
  "webApplicationInfo": {
    "id": "6eede4f0-da4c-4fca-ae6d-651d52b8ceee",
    "resource": "api://teoc.azurewebsites.net/6eede4f0-da4c-4fca-ae6d-651d52b8ceee"
  }
}

**Comment by Porkai-Pandian** [comment]
Hi @eendrulat,

Thank you for raising the query and sharing the manifest, can you please remove '/' at the end in validDomains and just have 'teoc.azurewebsites.net'. After making the changes, please create zip file and upload it. You can always validate the manifest file in Teams App Studio to check if it has any validation errors.

**Comment by Porkai-Pandian** [comment]
Hi @eendrulat, 

Even after making the above changes, you face similar issue, please let us know. It seems there is an ongoing issue with MS Teams in uploading the manifest, you can find the issue thread [here](https://techcommunity.microsoft.com/t5/teams-developer/mgmt-appcatalog-lobapp-upload-badrequest/m-p/3281493)

**Comment by eendrulat** [comment]
Good idea regarding validating the app. I did get one error related to app version (needed to change from 0.5 to 1.0); and warnings regarding privacy/ Terms of use links. Corrected these and the manifest passes - however i'm still unable to publish - keep getting the **'Mgmt.AppCatalog.LOBApp.Upload.BadRequest.UnknownTeamsAppManifestExceptionType'** error

**Comment by eendrulat** [comment]
Still get error when uploading app from the Teams admin console, however I was able to successfully install the app from Teams Desktop app (Manage your Apps > Upload app).
You can close this issue.

**Comment by thatguy9129** [comment]
I'm going to re-open this. I get this same error and I also get "Something went wrong, please try again later" when I try to upload from the desktop. Any other thoughts?
