### ISSUE TITLE
Unable to Log in to TEOC

### ISSUE THREAD

**Issue by SteveWedge** [OfficeDev/microsoft-teams-emergency-operations-center#111]
Hi, Having successfully deployed the TEOC solution I'm now faced with a problem when trying to log on. I have attempted to log on with 2 different accounts, one being the account that I used to deploy the solution. With both accounts, after clicking on the Logon button, in the Teams TEOC App, I see a pop up window flash up and disappear, and then just see the Logon screen again.

I managed to capture the interim state, when the pop-up appears and this is shown below. This is obviously trying to connect to the App Service, that was created during deployment, but I don't see any activity when checking the logs for that service

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/05a4b1b5-d67c-44ad-b6a7-b1e60f1d1a3b)

I'm not sure what to check next, but I don't get prompted to grant permissions, although I have done this directly against the associated registered App. I am not seeing a Dashboard, so am clearly not getting logged on.

Please advise

**Comment by v-prigunasek** [comment]
Hi @SteveWedge ,

Can you please reproduce the issue again in browser version of teams and share me the console logs and the network trace (Har file) to further troubleshooting on this issue? Thanks!

**Comment by SteveWedge** [comment]
Here's the additional information you requested, as it happens I was already running this test in an InPrivate browsing session.


[TeamsConsoleLogHar.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/11788277/TeamsConsoleLogHar.zip)

**Comment by SteveWedge** [comment]
It appears to be an issue related to "blocked by CORS policy: No 'Access-Control-Allow-Origin'"

**Comment by SteveWedge** [comment]
Thanks, I'd missed the replacement of <<Client ID>> in the manifest for the Teams App. SO I've moved past that issue, I'm not getting a logon prompt at all now, but I don't see the dashboard and I'm still seeing a number of errors in the Console

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/a0625182-fd82-40a8-ae33-f2b37f4339dc)

From reviewing them I'm wondering if there is some (undocumented) configuration needed on the SharePoint site, like adding users to Role, creating roles, etc?

**Comment by v-prigunasek** [comment]
Hi @SteveWedge ,

I believe you have provisioned the SharePoint site for TEOC before deploying the solution in Azure. If yes, can you please check the REACT_APP_SHAREPOINT_SITE_NAME configuration in your app service ? (In Azure portal, navigate to TEOC resource group, open app service and click on Configuration)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/9fbcb483-59a3-4e7e-9683-3bca786e5a51)

It should be just the site name (ex: KTBEmergencyResponders), if you have provided the full URL of the site by any chance, please update that to sitename as shown above and click ok and Save it.

Then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.

**Comment by SteveWedge** [comment]
Does the value need to correspond with the last part of the URL for the Site?

See below, the value from the configuration of the App Service:
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/436452d5-6c3b-410f-be8e-9398bbc84e97)

And here is the SharePoint site

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/28443902/a41dafc0-6a62-4fcf-a112-86f0b217ad99)


Is there any dependency on the Site Title / Display Name matching? I did amend it to be a more friendly name, but have changed it back and still have no joy.

**Comment by v-prigunasek** [comment]
Thanks for sharing. There is no dependency for displayname and for the name in the URL, both can be different, but we should use the sitename from the URL in the App service configuration. 
If you have already provided "KTB-Emergency-Responders" in the configuration while deploying resources, then it should be correct. 
Can you please launch the app once to replicate the issue and share me the console logs and network trace to troubleshoot on the error messages? Thanks!

**Comment by SteveWedge** [comment]
[TeamsConsoleLog.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/11800843/TeamsConsoleLog.txt)
[TeamsConsoleLogHar.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/11800854/TeamsConsoleLogHar.zip)

As requested and thanks for your assistance.

**Comment by v-prigunasek** [comment]
Hi @SteveWedge ,

I see there is some extra characters %E2%80%8E in the site name that is causing the error. (sometimes that might happen when we copy/paste the text)
GET https://graph.microsoft.com/v1.0/sites/yourtenant.sharepoint.com:/sites/%E2%80%8EKTB-Emergency-Responders%E2%80%8E?$select=id 404 (Not Found)

Can you please update the SharePoint Site Name in the configuration to **KTB-Emergency-Responders** ,  click OK and Save it.

Then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.

**Comment by v-prigunasek** [comment]
Yes, I mean the REACT_APP_SHAREPOINT_SITE_NAME. Please clear out that field entirely once and type in the value **KTB-Emergency-Responders** and click OK and Save button. Then perform the  [Sync latest version](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version) step, to get the code updated with the new site name value in your app service.

**Comment by SteveWedge** [comment]
OK, I did exactly what you requested. I redeployed the service and then went back to Teams and refreshed the page. Unfortunately I still get the same outcome and I can see in the log that the request URL still has those invalid characters around the site name.

Request URL:
https://graph.microsoft.com/v1.0/sites/kontoorbrands.sharepoint.com:/sites/%E2%80%8EKTB-Emergency-Responders%E2%80%8E?$select=id
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
20.190.151.160:443
Referrer Policy:
strict-origin-when-cross-origin

**Comment by SteveWedge** [comment]
Closing & reopening the inPrivate Browser session seems to have resolved the issue, so clearly there was cached content causing the problem to appear to be present still. 

It looks like its all up and running, many thanks for your assistance!
