### ISSUE TITLE
Error creating incident

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#112]
Install went well with version 2.  

Testing the app, Create Incident

Error: 
An error has occurred, please try to create your incident again

It looked like the incident team was starting to be created, then it disappeared.

On second try it worked, but this time I didn't add Guest Users or CLoud Storage Location

**Comment by v-prigunasek** [comment]
Hi @tcrobbins4 ,

Thanks for reaching out to us. 
It could be an intermittent issue in your first try, but it should ideally work even if you add Guest users and cloud storage location. Can you please try to add those fields as well and create another incident in browser version of teams? If you face any errors again, please share me the console logs and network trace for further troubleshooting on this issue. Thanks!

**Comment by tcrobbins4** [comment]
Ok.  Stand by.  Heading on vacation for a few days.
