### ISSUE TITLE
Will not "Login"

### ISSUE THREAD

**Issue by Tom-Robbins-COL** [OfficeDev/microsoft-teams-emergency-operations-center#115]
App has been working fine and I was about to demo it to the team and now it has a "Login" prompt and none of us can log in.  It allows me to select my userid but then blinks and "Login" button remains.

I stopped and restarted the services but that doesn't seem to have any effect.

Not a good way to get started.

**Comment by v-prigunasek** [comment]
Hi @Tom-Robbins-COL ,

Thanks for reaching out to us.
Can you please replicate the issue in the browser and share me the console logs and network trace to troubleshoot on this issue? Thanks!

**Comment by Tom-Robbins-COL** [comment]
Can I send the .har to you privately?  Via URL it just sits there spinning.

**Comment by Tom-Robbins-COL** [comment]
Now its giving me this: seoc.azurewebsites.net.x.647228f60786104537081630d736c3e3445e.ccc2ef7d.id.opendns.com’s server IP address could not be found.   (I obscured the full url prefix.)

**Comment by Tom-Robbins-COL** [comment]
It's magically working again.  Likely a Microsoft issue as usual.
