### ISSUE TITLE
Users see a blank screen or "this content is blocked" when opening app

### ISSUE THREAD

**Issue by Tom-Robbins-COL** [OfficeDev/microsoft-teams-emergency-operations-center#117]
App is showing up in Teams on the app bar correctly.  Also showing on the channel tab.

But when users (excluding me, the admin) click on the app or the tab, they either get a blank screen or "this content is blocked".

The previous issue from today is resolved.

**Comment by v-prigunasek** [comment]
Hi @Tom-Robbins-COL ,

Can you make sure you have provided at least Read access to other users in the TEOC SharePoint Site? If yes and you still see the issue, please try to launch it as personal app and see if that works. 
If you still have any issues, can you share me the console logs and network trace for further troubleshooting? Thanks!

**Comment by Tom-Robbins-COL** [comment]
Yes, the EOC staff are in the Members group and have Edit.   

What do you mean by the Personal App?   They have the App showing as a Channel Tab and as a Teams App (on the left).  SHould they be able to open via a webpage?  I cannot do that myself.  Purple spinning circle if I try to open the web page at azurewebsites.net.

**Comment by v-prigunasek** [comment]
yes, Personal app is nothing but the one added as Teams App (from the left pane). Can you try adding TEOC app as a Teams/Personal App instead of adding it to Channel and see if that works. If you face any issues, please share me the details (screenshot or logs) about the error. Thanks!

**Comment by Tom-Robbins-COL** [comment]
Well, again, it resolved itself.  The only thing I did was restart the App service.  I hope the app services are much more reliable than this for our testing.  Thanks for your help.
