### ISSUE TITLE
Can't add new roles since update

### ISSUE THREAD

**Issue by PGSEOC** [OfficeDev/microsoft-teams-emergency-operations-center#122]
When I try to add a new role on an incident, I am left with a blank white screen, nothing is happening. Note: this did work previously, I haven't tried since our upgrade to version 2, now it doesn't work.

**Comment by v-prigunasek** [comment]
Hi @PGSEOC ,

Thanks for reaching out to us. Can you please replicate the issue in browser version of teams and share me the console logs to troubleshoot the issue? Please share me the screenshot of the site contents page from the EOC SharePoint site as well. Thanks!

**Comment by PGSEOC** [comment]
I’m not an IT person, you will have to walk me through this again. Or provide instructions. The first time you sent them they were not clear…

Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by v-prigunasek** [comment]
Hi @PGSEOC ,

1. To get a console logs, please try to access the TEOC application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the console window) 
2. Replicate the issue in the TEOC app - Try to add a new Role and see if you get the blank screen as you mentioned above.
3. If yes, then right click on the Console window to Save it as a log file and share it across for further troubleshooting.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/f448fc9a-813b-461b-886b-7eeb35a15897)

**Comment by PGSEOC** [comment]
[teams.microsoft.com-1689605058328.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12070641/teams.microsoft.com-1689605058328.log)

**Comment by PGSEOC** [comment]
***@***.***

Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by v-prigunasek** [comment]
Hi @PGSEOC ,

Thanks for sharing the log file, but I dont see any error was captured in that log file. Are you able to replicate the issue?

**Comment by PGSEOC** [comment]
Thanks,

Kelly Knigge, MA, EMT, FPEM
Manager, Emergency Management
Peoples Gas System
O: 813.228.4425
C: 813.449.3256
***@***.******@***.***>

***@***.***

***@***.***

**Comment by v-prigunasek** [comment]
Closing this upon user confirmation. Issue was due to the new role added in the SP list and cleaning up those entries resolved the error.
