### ISSUE TITLE
Unable to Sign into app after uploading to teams

### ISSUE THREAD

**Issue by clarkec2** [OfficeDev/microsoft-teams-emergency-operations-center#125]
Hello! 

I am setting this app up and after updating the manifest for deployment I am thinking I may have something setup wrong. When I add the app to a team i get the login page, however when attempting to sign in I get a "cannot sign in error" that shows a different APP iD in the message than what we have set and registered. I have updated the manifest a few times in the wake of this as we have a few different vanity urls for our domain so finding the appropriate app domain to use in the manifest has been tricky.

**Comment by AshwiniShrirao** [comment]
@clarkec2, 
Thank you for reaching out to us. Can you please share manifest file with us for further investigation. 
Also request you to please reproduce the issue again in browser version of teams and share console logs for further troubleshooting this issue.

**Comment by AshwiniShrirao** [comment]
You can directly attach files to the git case.

**Comment by actionh** [comment]
Having a similar issue here - Just went through the setup, without any issues, but unable to sign in, once added to Teams (tried desktop, *New* Teams desktop, web and mobile). I do see a pop-up, but it flashes and closes without any errors.
On mobile, I'm asked to launch from Edge, but the window also closes once the app is opened (most likely the auth window).

**Comment by v-prigunasek** [comment]
Hi @clarkec2 ,

The Client ID in the manifest should be the Application (client) ID from the app registered for TEOC. 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/22a77cfa-c69c-48af-8ee2-dc6f73f5ed8d)

Please let us know if you still have any issues.

**Comment by clarkec2** [comment]
That is correct, I worked with a contact from MSFT yesterday, and did some additional troubleshooting myself. This was tested and published into our dev env without issues. I have did some work on the manifest and I am still met with the same error after publishing the app into prod...

***@***.***

I found an article stating that a Global admin needs to reconsent after the app is reuploaded via this link...

https://login.microsoftonline.com/common/adminconsent?client_id=
(Client ID Removed)

-Col-


General Business
