### ISSUE TITLE
Azure App Secret renewal

### ISSUE THREAD

**Issue by martinfredette** [OfficeDev/microsoft-teams-emergency-operations-center#126]
Hi,

I set my app secret to expire in 12 months but question, is there any procedure on how to renew this secret ?

Thanks

**Comment by AshwiniShrirao** [comment]
@martinfredette , Thank you for reaching out to us. Please allow us some time to check this and will update you.

**Comment by AshwiniShrirao** [comment]
@martinfredette,
For updating client secret please follow below steps,
1. [Check and update client secret expiration date](https://learn.microsoft.com/en-us/azure/industry/training-services/microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault#check-and-update-client-secret-expiration-date)
2. [Update Application Configuration](https://learn.microsoft.com/en-us/azure/industry/training-services/microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault#update-application-configuration)
This has to be updated in simpleAuth Service configuration.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/140151638/74d366c3-e814-4b99-b13f-087a7e3d36c1)

Please refer [this](https://learn.microsoft.com/en-us/azure/industry/training-services/microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault#update-application-configuration) article for more details.
