### ISSUE TITLE
Blank App in Teams

### ISSUE THREAD

**Issue by CSBenW** [OfficeDev/microsoft-teams-emergency-operations-center#127]
We are having an issue with the Teams App not displaying any content after deployment. The title bar is there with the info, help, and feedback icons. The "welcome" message is also displayed, but there is no content below that to actually use the app. 
![Screenshot 2023-06-29 104705](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/133781988/3c2d71bc-269b-4ee2-9b81-104431c4b8b9)

**Comment by AshwiniShrirao** [comment]
@CSBenW , Thank you for reaching out to us. 
 Can you please check the REACT_APP_SHAREPOINT_SITE_NAME configuration in your app service?
 
 Please refer issue #82

**Comment by v-prigunasek** [comment]
Hi @CSBenW ,

Can you please let us know if you are still having this issue? If yes, please try to replicate the issue in the browser version of Teams and share us the console logs for further troubleshooting. Thanks!

**Comment by CSBenW** [comment]
Hi there, sorry for the delay. I did confirm the REACT_APP_SHAREPOINT_SITE_NAME is set properly in Azure. I have also verified the issue occurs in the browser version of Teams, as well as the desktop version. I will try to get the console logs to share for further troubleshooting.

**Comment by CSBenW** [comment]
Hi again, I was able to get the console log exported. Is there a secure way for me to share that with you here?

**Comment by v-asshrirao** [comment]
Closing this as user raised new ticket for this issue #140.
