### ISSUE TITLE
Teams EOC app Title change

### ISSUE THREAD

**Issue by przekom** [OfficeDev/microsoft-teams-emergency-operations-center#128]
![6f64a0a4-83df-4642-a158-a92b6026dfbc](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/140834272/45a8d3c8-29a9-4efe-968b-0247867b01ed)

Is there a way to change "Microsoft Teams Emergency Operations Center" at the top of the teams app page in Teams. Added screenshot not sure if its visible.

**Comment by AshwiniShrirao** [comment]
@przekom, At present we don't have this customization available. 
Thank you for brining this up, we will try to include this in one of our future releases.
