### ISSUE TITLE
Unable to Login to Teams App

### ISSUE THREAD

**Issue by actionh** [OfficeDev/microsoft-teams-emergency-operations-center#129]
Just went through the setup, without any issues, but unable to sign in, once added to Teams (tried desktop, *New* Teams desktop, web and mobile). I do see a pop-up, but it flashes and closes without any errors.
On mobile, I'm asked to launch from Edge, but the window also closes once the app is opened (most likely the auth window).

Edit (7/31): I went back through the documentation and double-checked all the steps. Everything _appears_ to be setup correctly. I did see successful login attempts to the TEOC app in Azure AD for the user, so authentication must be working in some regard. However, the TEOC Teams app screen never goes passed the Login page. No errors are visible and clicking login again, only generates the same results.

_Originally posted by @actionh in https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/125#issuecomment-1655973137_

**Comment by actionh** [comment]
> 

Hi @AshwiniShrirao - Here are the logs from my latest attempt.
I reviewed the previous post and went through the directions. The REACT_APP_SHAREPOINT_SITE_NAME was incorrect in my deployment, as well - I fixed that (by manually typing in the site name entry, to avoid hidden characters), redeployed and uploaded the updated app to Teams. However, I'm still facing the same login issue. I'm unable to advance from the initial teoc screen.
Please see the attached console logs and let me know if there's anything else that I might be able to provide.
[teams.microsoft.com-1691001312693.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12243595/teams.microsoft.com-1691001312693.log)

**Comment by AshwiniShrirao** [comment]
@actionh, Thank you for sharing the logs. 
Can you please confirm if deployment is successful and share the screenshot.
We will also need to verify manifest file so request you to kindly share that with us.

**Comment by actionh** [comment]
Hi @AshwiniShrirao

The deployment does appear to have been successful, but still unable to sign in.
Please see the attached manifests (app package & registration).



Tom Hanes | Cloud Systems Engineer | DDI

**Comment by AshwiniShrirao** [comment]
@actionh,
Please allow us some time to analyze and we will get back to you.

**Comment by AshwiniShrirao** [comment]
@actionh, We have verified both manifest files shared by you and both are configured correctly. 
We are still trying to analyze the issue. Meanwhile can you please confirm if https://ddi-eocsimpleauth.scm.azurewebsites.net is working for you.

**Comment by actionh** [comment]
> @actionh, We have verified both manifest files shared by you and both are configured correctly. We are still trying to analyze the issue. Meanwhile can you please confirm if https://ddi-eocsimpleauth.scm.azurewebsites.net is working for you.

Hi @AshwiniShrirao 
Thank you very much for taking the time to look into this. I really appreciate it!
It does appear that the is loading, from what I'm seeing.
Please let me know if there's any other information that I can get for you.

![simpleauth](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/90396877/6332ac07-5e61-4902-a904-f3a37158fb38)

**Comment by v-prigunasek** [comment]
Hi @actionh ,

Thanks for confirming the above. Could you please try to restart the simple auth app service and see if that makes any difference? 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/5494139d-a192-49b0-be51-bee9ceb597a4)

Also, can you please try to open the TEOC app in different browser and Teams client to verify if that works? Thanks!

**Comment by actionh** [comment]
Hi @v-prigunasek 
I went back through and recreated the resource group & services with a different name. After reconfiguring the app registration and reuploading the app to Teams, it now appears to be working properly.
Thank you very much for all of the assistance! Very much appreciated!

**Comment by v-prigunasek** [comment]
Hi @actionh, 

That sounds great and thanks for confirming. Closing this issue for now. Please feel free to open a new one if you face any other issues.
