### ISSUE TITLE
Teams EOC - Login Error

### ISSUE THREAD

**Issue by eendrulat** [OfficeDev/microsoft-teams-emergency-operations-center#13]
After installing the app - I can access the main welcome / login screen.

When I click Login, I was prompted for my password, after which there is no response on the UI.

Looking at the debugging tools, I see these errors logged in the console:

> POST https://teocsimpleauth.azurewebsites.net/auth/token 401 (Unauthorized)
> Uncaught (in promise) r.InternalError: Failed to get access token with error: Request failed with status code 401
> TypeError: Cannot read properties of undefined (reading 'appMetricsData')
> Uncaught TypeError: Cannot read properties of undefined (reading 'appMetricsData')
> POST https://teocsimpleauth.azurewebsites.net/auth/token 401 (Unauthorized)
> Uncaught (in promise) r.InternalError: Failed to get access token with error: Request failed with status code 401

[teams.microsoft.com-1649768971780.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/8473147/teams.microsoft.com-1649768971780.log)

**Comment by v-ashrirao** [comment]
@eendrulat, thank you for reporting this issue.
We will need more information to help you with this.
Step 1:
Can you please confirm if deployment was successful?
You can validate this by navigating to,
**Resource Group > Overview > Deployment**

Step 2:
If deployment is successful, validate if authentication setup is configured correctly. [Step 3 from Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-set-up-authentication).
**Resource Group > App Service > Configuration**

**Comment by Porkai-Pandian** [comment]
Hi @eendrulat, 

Please let us know your availability so that we can get into call and troubleshoot the issue.

**Comment by eendrulat** [comment]
sending you a message offline..

**Comment by thatguy9129** [comment]
> @eendrulat, thank you for reporting this issue. We will need more information to help you with this. Step 1: Can you please confirm if deployment was successful? You can validate this by navigating to, **Resource Group > Overview > Deployment**
> 
> Step 2: If deployment is successful, validate if authentication setup is configured correctly. [Step 3 from Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-set-up-authentication). **Resource Group > App Service > Configuration**

I am also having the same issue. I click Login and I get logged in but then nothing happens. I confirmed that deployment was successful and the app service is running. Are there further troubleshooting steps?

**Comment by eendrulat** [comment]
@thatguy9129  - walked through my configuration during a screen-share yesterday with @Porkai-Pandian, they're looking into it now.

**Comment by Porkai-Pandian** [comment]
Thanks @thatguy9129, I'm trying to reproduce the issue here, quick question for you, can you please confirm if you're using Windows or Mac OS?

**Comment by thatguy9129** [comment]
> Thanks @thatguy9129, I'm trying to reproduce the issue here, quick question for you, can you please confirm if you're using Windows or Mac OS?

Windows. Let me know if a screen share or logs would help.

**Comment by v-ashrirao** [comment]
@eendrulat , @thatguy9129 , 
Can you please confirm whether deployment was successful?

Please follow below steps.
Navigate to Resource Group, under Deployments you can see 5 succeeded. 
![image](https://user-images.githubusercontent.com/100257227/163760219-bbd165d6-f802-4178-be62-6fcfab5d4a1b.png)
Click on highlighted hyperlink and share below screenshot.
![image](https://user-images.githubusercontent.com/100257227/163760520-9997dd54-c8d1-4833-ae8b-2d4de453127a.png)

**Comment by eendrulat** [comment]
Confirming that the deployment was successful:
[image: image.png]

**Comment by v-saikirang** [comment]
Hi @eendrulat, 

That's good news. Thanks for your patience here. 
Can you please try creating a sample incident and let us know if you see any further issues. If you see any issues please share a screenshot and the console logs file.

Thanks.

**Comment by v-saikirang** [comment]
Hi @eendrulat,

Can you please confirm if the app is working fine now.

Thanks.

**Comment by eendrulat** [comment]
@v-saikirang 
The app still doesn't work, I was just confirming that the deployment in Azure Resource Groups indicated it was successful.  What do I need to do after updating that value in the manifest?

**Comment by v-saikirang** [comment]
Hi @eendrulat,

After updating the value in the manifest file it should automatically work. Can you please try open the app in a new incognito browser and test. If it still doesn't work can you please share the screenshot of the console logs and also the screenshot of the manifest you have just modified so we can verify.

Thanks.
Thanks.

**Comment by eendrulat** [comment]
![image](https://user-images.githubusercontent.com/527590/163812199-01a529d3-164d-4532-bacb-615fb274df1f.png)

![image](https://user-images.githubusercontent.com/527590/163812295-9a021d2c-2239-4140-84a7-73b6bf5ecd35.png)

**Comment by thatguy9129** [comment]
> @eendrulat , @thatguy9129, We have validated the configuration shared. It looks like below highlighted configuration is missing in tenant. Please refer [deployment guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-set-up-authentication) for same. ![image](https://user-images.githubusercontent.com/100257227/163793895-4e98854b-1d43-4c16-ad39-a7792bb2777f.png)
> 
> Can you please update the configuration and let us know if it's working?

I changed the accessTokenAcceptedVersion but your second image (step ii) didn't come through for optionalClaims. What changes need to be made to the optional claims?

**Comment by v-saikirang** [comment]
Hi @thatguy9129,

The above screenshot is from deployment guide. The link is also shared in the previous message. Can you please go through all the steps to confirm if they are already implemented. If you have missed out only accessTokenAcceptedVersion change you can open the app after making the change. Please confirm if it worked.

Hi @eendrulat,
Can you please confirm if you see that error when you click on Login.

Thanks.

**Comment by thatguy9129** [comment]
> Hi @thatguy9129,
> 
> The above screenshot is from deployment guide. The link to the guide is also shared in the previous message. Can you please go through all the steps to confirm if they are already implemented. If you have missed out only accessTokenAcceptedVersion change you can open the app after making the change. Please confirm if it worked after making that change.
> 
> Thanks.

I confirm the optional claims match the deployment guide. Changing the accessTokenAcceptedVersion does not fix it. Same behavior of the login screen but no changes after authentication.

**Comment by eendrulat** [comment]
> 
> Hi @eendrulat, Can you please confirm if you see that error when you click on Login.
> 
> Thanks.

Yes - I am seeing this error when I click Login:
{"type":"AuthInternalServerException","status":500,"detail":"The AAD configuration in server is invalid."}

**Comment by v-ashrirao** [comment]
@thatguy9129, 
Please let us know your availability so that we can troubleshoot the issue over call.

**Comment by thatguy9129** [comment]
> @thatguy9129, Please let us know your availability so that we can troubleshoot the issue over call. Request you to share your email id as well so that we can setup call.

9:30am ET tomorrow (4/20)?

**Comment by v-saikirang** [comment]
Hi @thatguy9129,
Sure. We will send you the meeting invite. Can you please share your Email.
Thanks.

**Comment by thatguy9129** [comment]
> Hi @thatguy9129, Sure. We will send you the meeting invite. Can you please share your Email. Thanks.

opnj@rkomo.com

**Comment by Porkai-Pandian** [comment]
Thanks @thatguy9129, will send you the meeting invite, I've deleted the email from the comments

**Comment by thatguy9129** [comment]
> Thanks @thatguy9129, will send you the meeting invite, I've deleted the email from the comments

Didn't get it. Please try  njmj@zhcne.com

**Comment by Porkai-Pandian** [comment]
Hi @thatguy9129, sent invite to both emails, please confirm if you've received.

**Comment by thatguy9129** [comment]
> Hi @thatguy9129, sent invite to both emails, please confirm if you've received.

Confirmed.

**Comment by Porkai-Pandian** [comment]
@thatguy9129 as per our discussions, we found the application id in Manifest file is incorrect and '/' missing in Application ID URI, after updating these values you're able to sign in successfully. Please let us know once you're able to create the incident.

**Comment by Porkai-Pandian** [comment]
@eendrulat as discussed, issue is resolved with new deployment, hence closing the issue, thanks for your support

**Comment by mwceadmin** [comment]
Hello, I am running into the same issue. I have deployed it few times now. I have added the optional claim to manifest and change it to 2 for AccessTokenAcceptedVersion. I verified spelling, multiple times as well. 

this is what i see in the log 
![image](https://user-images.githubusercontent.com/83797434/180111134-b769c57c-380e-47f5-99ae-8af07f256637.png)

Deployment was successful. all I see in teams is the "login" button but when I click on it it just goes away - the error above is what shows in the logs. 
Please advise.
