### ISSUE TITLE
Unable to get pass the login screen

### ISSUE THREAD

**Issue by Couzgeez** [OfficeDev/microsoft-teams-emergency-operations-center#130]
The first day I tested the app, everything was working fine. Today i'm stuck on the main screen and I can't pass the login screen. From the dev console I can see this error message:

Access to XMLHttpRequest at 'https://zz1eocsimpleauth.azurewebsites.net/auth/token' from origin 'https://zz1eoc.azurewebsites.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AshwiniShrirao** [comment]
@Couzgeez, 
Can you please reproduce the issue again in browser version of teams and share the console logs and network trace for further troubleshooting this issue? 

Please refer similar issue #111. Please let me know if that helps.

**Comment by Couzgeez** [comment]
Thanks for the comeback. I finally found the issue which was a security issue. It is now working.

**Comment by v-asshrirao** [comment]
@Couzgeez, 
Hope you are doing well.
Regarding the issue you were having, can you please help us understand how it got fixed and the steps you have followed to fix this issue?
