### ISSUE TITLE
Deploy to Your Azure Subscription - No Subscription

### ISSUE THREAD

**Issue by BubbaP51** [OfficeDev/microsoft-teams-emergency-operations-center#132]
We have a GCC Tenant and have created the TEOC sharepoint site, registered Azure AD application, now when I go to step 3. to Deploy to Azure, click on Subscription, it is blank with a note along the bottom stating "no available items", also the resource group states "Loading" and region states "Loading"

When bypassing the Deploy to Azure link in the Deployment Instructions and using an Azure quick deploy link, I receive the same issue.

I created the site using the EOC-Provision.  I did not use GCCH since we are only GCC.  I'm beginning to wonder if GCC is not able to deploy their own.  

Any help appreciated... Bubba

![Screenshot](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/142053767/250e1ba7-d474-4357-ab78-e7bbf7f3f9a4)

**Comment by v-asshrirao** [comment]
@BubbaP51, Thank you for reporting this.
Can you please confirm below,

Are able to see your subscriptions in CLI?  _**az account list --output table**_ 
Are you getting this issue in both edge and chrome browser?

**Comment by BubbaP51** [comment]
@v-asshrirao 

Same issue in both edge and chrome

Response to:  az account list --output table
The following tenants don't contain accessible subscriptions.  Use 'az login --allow-no-subscriptions' to have tenant level access.
No subscriptions found for "tenant name".

**Comment by v-asshrirao** [comment]
@BubbaP51, Thank you for the details. Looks like you don't have any subscription.
 Without subscription you will not be able to deploy TEOC app.
