### ISSUE TITLE
Unable to get past Login screen in Teams

### ISSUE THREAD

**Issue by Coffi007** [OfficeDev/microsoft-teams-emergency-operations-center#134]
I have completed the steps to create the EOC app. I am unable to get past the login screen in Teams. I am attaching the log from Teams web browser. 
[Unauthorized.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12423592/Unauthorized.txt)

**Comment by v-asshrirao** [comment]
@Coffi007, thanks for reaching out to us.
We will need more information to help you with this.
Step 1:
Can you please confirm if deployment was successful?
You can validate this by navigating to,
Resource Group > Overview > Deployment

Step 2:
If deployment is successful, validate if authentication setup is configured correctly. [Step 3 from Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-set-up-authentication).
Resource Group > App Service > Configuration

Can you replicate the issue in the browser and share the console logs and network trace to me for troubleshoot on this issue?

**Comment by Coffi007** [comment]
Yes deployment was successfully completed. I verified everything from step three is configured correctly. I had already shared the log from the Teams web browser. I am attaching it again in a note pad.

**Comment by v-asshrirao** [comment]
@Coffi007 , Can you please share manifest files with us to analyse this issue further.
Also please refer issue #13 where user reported similar issue.

**Comment by Coffi007** [comment]
Here is the Manifest file.

**Comment by Coffi007** [comment]
Her is the manifest from the app registration

**Comment by v-asshrirao** [comment]
@Coffi007, Can you please upload the file here in this issue ticket through GitHub rather than attaching it in email? I could not receive any links or attachments sent via email.

**Comment by Coffi007** [comment]
Actually, the login issue is resolved not that I changed the access token value to 2.

Now I am logged in but the page is not loading. Here is a screen shot of the console code error.
***@***.***

**Comment by Coffi007** [comment]
This is configured properly .

[sharepointnaming.docx](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12431127/sharepointnaming.docx)

**Comment by Coffi007** [comment]
Here is the latest log file
[teams.microsoft.com-1692900430469.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12432247/teams.microsoft.com-1692900430469.log)

**Comment by v-asshrirao** [comment]
@Coffi007 , Looks like you have done configuration in Web App, however this configuration has to be done in App Service.
Can you please update that and  follow this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.

**Comment by v-asshrirao** [comment]
@Coffi007, Everything looks correct. 
Can you please perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version) and confirm if its working?
