### ISSUE TITLE
Deployment Sync Failing

### ISSUE THREAD

**Issue by dthuss** [OfficeDev/microsoft-teams-emergency-operations-center#135]
Attempting to upgrade from V1 to V2. In the deployment center I click Sync. It fails. I have included the message below. I have reviewed a similar issue and confirmed that the WEBSITE_NOTE_DEFAULT_VERSION is currently 16.13.0 (https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/27 )

![2023-08-25_13-37-03](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/143137549/aa9fa0f7-a497-4e52-9f1e-53024925a6a9)

Error message references FabricBot

**Comment by v-asshrirao** [comment]
@dthuss , Can you please share actual deployment error.
Click on Commit ID and then click show logs. Share logs with us to troubleshoot further.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/0a5ecbd1-6937-4300-9eaa-0c8ca050ae49)

**Comment by dthuss** [comment]
See below:

Command: deploy.cmd
Restoring npm packages for EOC-TeamsFx (this can take several minutes)
"C:\home\site\repository"
Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"

up to date in 21s

246 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> teamsfx-template-tab@0.1.0 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[3740:006A7818]   475472 ms: Mark-sweep 496.1 (523.1) -> 493.3 (523.8) MB, 4840.6 / 0.1 ms  (average mu = 0.423, current mu = 0.099) allocation failure scavenge might not succeed
[3740:006A7818]   479921 ms: Mark-sweep 496.9 (523.8) -> 494.4 (524.8) MB, 4390.8 / 0.1 ms  (average mu = 0.270, current mu = 0.013) allocation failure GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01585D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run-script build
An error has occurred during web site deployment.
Browserslist: caniuse-lite is outdated. Please run:\r\n  npx update-browserslist-db@latest\r\n  Why you should do it regularly: https://github.com/browserslist/update-db#readme\r\n\r\n<--- Last few GCs --->\r\n\r\n[3740:006A7818]   475472 ms: Mark-sweep 496.1 (523.1) -> 493.3 (523.8) MB, 4840.6 / 0.1 ms  (average mu = 0.423, current mu = 0.099) allocation failure scavenge might not succeed\r\n[3740:006A7818]   479921 ms: Mark-sweep 496.9 (523.8) -> 494.4 (524.8) MB, 4390.8 / 0.1 ms  (average mu = 0.270, current mu = 0.013) allocation failure GC in old space requested\r\n\r\n\r\n<--- JS stacktrace --->\r\n\r\nFATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory\r\n 1: 01585D3F v8::internal::Heap::AllocateExternalBackingStore+1551\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50622.6321\bin\Scripts\starter.cmd deploy.cmd

**Comment by v-asshrirao** [comment]
@dthuss ,
We will need few more details to troubleshoot this issue.
1. Confirm App Service Plan. Navigate to App service and click App Service Plan.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/3c604d8e-667e-42d2-8f36-06926684f450)
2. List of Apps sharing this App Service. Navigate to App service and click App Service Plan. Now, from setting click Apps to get list of Apps using same App Service.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/e9ab6c2c-d118-4476-8999-97d2b5b82ad8)

**Comment by dthuss** [comment]
I had downgraded the Service Plan - going to try again with it at S2

**Comment by v-asshrirao** [comment]
@dthuss, Please do let us know if that is working.

**Comment by dthuss** [comment]
This worked - thank you for your assistance!

**Comment by v-asshrirao** [comment]
@dthuss , Thank you for your confirmation. I will mark this issue as closed now.
