### ISSUE TITLE
App not loading all the way.

### ISSUE THREAD

**Issue by RobertUSsystems** [OfficeDev/microsoft-teams-emergency-operations-center#136]
App Load on Teams and passes authentication stuck on welcome screen. Same issue within the Teams web App. I am attaching the console log for Teams webapp.
[teams.microsoft.com-1692996590548.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12443497/teams.microsoft.com-1692996590548.log)

**Comment by v-asshrirao** [comment]
@RobertUSsystems , Thanks for reaching out to us.
I believe you have provisioned the SharePoint site for TEOC before deploying the solution in Azure. If yes, can you please check the REACT_APP_SHAREPOINT_SITE_NAME configuration in your app service ? (In Azure portal, navigate to TEOC resource group, open app service and click on Configuration)

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/11fe9711-19b7-4c41-902d-eaf92db3a92d)

It should be just the site name, if you have provided the full URL of the site by any chance, please update that to sitename as shown above and click ok and Save it.

Then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.

Please refer similar issue #134

**Comment by RobertUSsystems** [comment]
The settings are all correct and the site is still not loading. Please refer to the errors listed in the log file I sent originally.

**Comment by v-asshrirao** [comment]
@RobertUSsystems , Thanks for your confirmation. As per the errors in log files, there is some issue in reaching SharePoint site you have provisioned.
1. Can you please confirm if site name is not using any special characters except 'underscore, dashes, single quotes, and periods (_,-,',.), and is not starting or ending with a period.'.
2. Also confirm if you are using the same site name which is used while provisioning.
3. Can you navigate to SharePoint provisioned site and share that screenshot with us just to validate its up and running.

**Comment by RobertUSsystems** [comment]
The SharePoint site name is EOC. We are using the same site name while provisioning. The SharePoint site is accessible, and all lists/libraries have been installed.

**Comment by v-asshrirao** [comment]
@RobertUSsystems , Thanks for confirming this. 
As per the logs shared by you, the site name is coming as "EOC%E2%80%8E".
Just validate if in configuration also its EOC only. If yes, can you please perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version) and confirm if its working?

**Comment by RobertUSsystems** [comment]
I double checked everything and reran the error log to get the latest error code. I am attaching the log.
[Teams log 082923.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12466302/Teams.log.082923.log)
