### ISSUE TITLE
Login Window Disappears

### ISSUE THREAD

**Issue by ma-dockins** [OfficeDev/microsoft-teams-emergency-operations-center#137]
Hi, 

I followed the steps for the TEOC Deployment Guide and was able to added the app to Teams. When I attempt to login, a window appears and redirects then closes. The window is blank. I checked the other submitted issues but did not see a resolution.

**Comment by v-asshrirao** [comment]
@ma-dockins, Thank you for reaching out to us.
Can you please reproduce the issue again in browser version of teams and share the console logs for further troubleshooting on this issue?

**Comment by ma-dockins** [comment]
I don't see those options. Below is what I have when attempting to access console logs for TEOC:

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/144259717/cfaa11bb-161f-4608-814b-c227d169ec93)

**Comment by v-asshrirao** [comment]
@ma-dockins , 
Please open TEOC app in web version of teams and follow below steps for generating console logs.
1. Open Developer Tools. 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/a7dcfb3e-ace3-4db4-b4e5-0bdcf247e28e)
2. Select console and all levels.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/4248ee76-5023-4480-b3cf-8b348a531309)
3. Refresh the browser and share logs with us.

**Comment by ma-dockins** [comment]
Thank you! Attached are the logs 
[teams.microsoft.com-1695140881634.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12664331/teams.microsoft.com-1695140881634.log)

**Comment by v-asshrirao** [comment]
@ma-dockins, 
From the logs you have shared, the issue is related to CORS policy.

Refer similar issue #111. Please let us know if that helps.

**Comment by ma-dockins** [comment]
Hi,

I followed the link you provided and verified all information is provided as instructed. The issue still persists.

**Comment by ma-dockins** [comment]
Hi,
[teams.microsoft.com-1696449006735.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12807606/teams.microsoft.com-1696449006735.log)

I was able to resolve the CORS error. However, I am not encountering an internal 500 server error. I have attached the console logs.

**Comment by v-asshrirao** [comment]
@ma-dockins,

Thank you for sharing the logs,
Can you please share manifest file with us for further investigation.
Also, please confirm if deployment was successful.

**Comment by ma-dockins** [comment]
Hello,

I am still experiencing the 500 internal server error. I've attached the manifest. 


[teoc.zip.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12819480/teoc.zip.zip)

**Comment by ma-dockins** [comment]
Hi,

All 7 Deployments succeeded.

[TEOCHCPHeadquarters.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12821144/TEOCHCPHeadquarters.txt)

**Comment by v-asshrirao** [comment]
@ma-dockins, We have verified the manifest files shared. 
We have found that along with WebSiteURL placeholder you have also updated the value for WebSiteURL under developers.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/73a74ad6-b9cf-4fad-a038-15b4a9f24225)
Which is causing an issue. Replace that with below value and let us know if that work.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/e8705edb-3591-4091-8a0c-becea94d15ed)

**Comment by v-asshrirao** [comment]
@ma-dockins, Can you please navigate to **Resource Group > Deployments** and share screenshot with us.
We know you have confirmed that deployment was successful, but just for validation we will need details if simpleAuthProvision deployment is successful or not as its throwing 500 error.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/6cf23138-5e55-47ce-96a5-773c5e9f727f)

Also request you to kindly refer similar issue reported by user #94

**Comment by v-asshrirao** [comment]
@ma-dockins, 
Can you please try to restart the simple auth app service once and check if its working. 
If that is not working, you will have to do the deployment from scratch with new resource group by deleting the existing resource group.
