### ISSUE TITLE
Create Incident Fails: Tenant admin has not enabled Unified Group Creation

### ISSUE THREAD

**Issue by ztaylorMNP** [OfficeDev/microsoft-teams-emergency-operations-center#138]
Hi,

I have been assisting a client to get the TEOC app installed and running in their tenant, but we are running into the error "Tenant admin has not enabled Unified Group Creation" whenever the testing user tries to create an incident.  The Unified Group Creation permission has been intentionally disabled as part of the client's internal policies.

Is the ability for all users to create 0365 groups a requirement for the TEOC app to create incidents?  Must Unified Group Creation be enabled?  

If it is a required setting, it should be added to the install documentation.

**Comment by v-asshrirao** [comment]
@ztaylorMNP, All users creating incident should have permission for creating groups. This is requirement for TEOC App, we will be adding this to instalment guide in next release.
