### ISSUE TITLE
UnknownTeamsAppManifestExceptionType Error When Uploading

### ISSUE THREAD

**Issue by thatguy9129** [OfficeDev/microsoft-teams-emergency-operations-center#14]
I updated the local manifest file according to the instructions, zipped and uploaded to the Teams Admin center. When I do this, I get the following error:

##Mgmt.AppCatalog.LOBApp.Upload.BadRequest.UnknownTeamsAppManifestExceptionType

```
{
  "$schema": https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json,
  "manifestVersion": "1.11",
  "version": "0.5",
  "id": "bef61400-db9b-41d4-a617-403deb7bbe77",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams Customer Advocacy Group",
    "websiteUrl": https://aka.ms/teamsapptemplates,
    "privacyUrl": https://privacy.microsoft.com/en-us/privacystatement,
    "termsOfUseUrl": https://www.microsoft.com/en-us/servicesagreement
  },
  "icons": {
    "color": "resources/color.png",
    "outline": "resources/outline.png"
  },
  "name": {
    "short": "TEOC",
    "full": "Microsoft Teams Emergency Operations Center (Preview)"
  },
  "description": {
    "short": "Microsoft Teams Emergency Operation Center (Preview)",
    "full": "The Microsoft Teams Emergency Operations Center (TEOC) solution template leverages the power of the Microsoft 365 platform to centralize incident response, information sharing and field communications using powerful services like Microsoft Lists, SharePoint and more. An open-source solution supported by Microsoft it provides core functionality out of the box or can be extended to meet specific agency requirements."
  },
  "accentColor": "#FFFFFF",
  "bots": [],
  "composeExtensions": [],
  "configurableTabs": [
    {
      "configurationUrl": https://xxxxxxx.azurewebsites.net/index.html#/config,
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Teams EOC",
      "contentUrl": https://xxxxxxx.azurewebsites.net/index.html#/tab,
      "websiteUrl": https://xxxxxxx.azurewebsites.net/index.html#/tab,
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "xxxxxxx.azurewebsites.net"
  ],
  "webApplicationInfo": {
    "id": "xxxxxxxxxx33",
    "resource": "api://xxxxxxx.azurewebsites.net/xxxxxxxxxx33"
  }
}
```

The ID being used is the App (client) ID under my Registered App. Under Permission Policies in Teams, all Microsoft apps are allowed. Third-Party apps are not enabled. Custom apps are allowed.

**Comment by v-ashrirao** [comment]
@thatguy9129, thank you for raising the query.
Upload the app from Teams Desktop App, navigate to **Manage Your Apps** and **Upload a Custom App**

Let us know if additional information is needed on this.

**Comment by thatguy9129** [comment]
Tried, that, get "Something went wrong, please try again later."

**Comment by Porkai-Pandian** [comment]
Hi @thatguy9129, 

We've not validated the app installation in GCC-high tenant, hence cannot confirm on this, but we're working on supporting for GCC-high as well in the future. However, it might be related to an [issue](https://techcommunity.microsoft.com/t5/teams-developer/mgmt-appcatalog-lobapp-upload-badrequest/m-p/3281493) which happened yesterday with Teams custom app upload as well. Please let us know if you've any issues in accessing the app in GCC and commercial accounts.

**Comment by thatguy9129** [comment]
Thanks, I was able to get it added to a non-GCC tenant.

**Comment by SamErde** [comment]
@thatguy9129, is this working in a GCC-High tenant yet? Thanks!

**Comment by v-prigunasek** [comment]
Hi @SamErde ,
Not yet, we are planning to release the next major version of the TEOC app in couple of weeks and that upcoming version will be supported in GCCH tenant as well. Thanks!
