### ISSUE TITLE
Can't upload app to teams

### ISSUE THREAD

**Issue by Far-Song** [OfficeDev/microsoft-teams-emergency-operations-center#141]
Hi,
I followed the steps through to step seven. Everything went smoothly before, but when I uploaded the application to Teams, I reported this error "Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error”
![图片](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/53267340/17dc4850-5e01-4c2e-bb44-aeaa514ccfcf)
I've tried uploading from the web page, and I've also tried uploading from the Teams client. All show this error.
Could you help me see where the problem is? Attached is the list.
[manifest_copy.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12725807/manifest_copy.txt)

Azure services and SharePoint seem to be running normally.
![图片](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/53267340/16909a1d-79e0-4f75-b7f0-cf89eb5d0a59)
![图片](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/53267340/88108d3d-d59f-4404-82a9-42319a3eb5d4)

Thanks!
Yuan

**Comment by v-asshrirao** [comment]
@Far-Song, Thank you for reaching out to us. 
Can you please share manifest files with us to troubleshoot the error.

**Comment by Far-Song** [comment]
There is a txt file in the middle of the article. Because .json cannot be uploaded.

**Comment by Far-Song** [comment]
[manifest_copy.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12726051/manifest_copy.txt)

**Comment by Far-Song** [comment]
Local appPackage manifest
[manifest_copy.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12726285/manifest_copy.txt)

App registration manifest
[HFXEOC-copy.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12726290/HFXEOC-copy.txt)

**Comment by Far-Song** [comment]
Just now, I successfully uploaded it. Unbelievable
grateful! Close this ticket.
