### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hepburnhelpdesk** [OfficeDev/microsoft-teams-emergency-operations-center#142]
The initial powershell script (EOC-Provision.ps1) failed saying I didn't have access. But must have created part of it as then would fail saying "Site creation failed. Site name cannot contain symbols..."
I tried running it manually, line by line, which completed but it doesn't look like it worked. as I get a plain vanilla looking sharepoint site.

The rest of the install seems to have worked. But there are no log files I can find to diagnose what has gone wrong.
The app doesn't seem to do anything or go anywhere. There are no real means to diagnose what is going on.

When I try to go to the Azure app   https://teoc.azurewebsites.net/index.html#/tab I just get a blue spinning wheel.

Please help.

**Comment by hepburnhelpdesk** [comment]
Very fundamental installation process. It needs to write log files with diagnosis information and verification processes.
There are no illustrations of what to expect or how to verify it worked, just illustrations of the process.

**Comment by v-asshrirao** [comment]
@hepburnhelpdesk, Can you please confirm if deployment was successful.
Can you navigate to the resource group and navigate to deployment and share that screenshot with us, just to validate deployment was successful.   

Also, can you please share the exact error you were getting while running provisioning script?

**Comment by hepburnhelpdesk** [comment]
I have pretty much full access to Sharepoint.
The first error I get is:  Site creation failed. Site name cannot contain symbols other than underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period.
Then I give myself: Site Admin and owner and it works.

When I go to the Resource Group page I get:


Resource Group Deployment log:
Command: deploy.cmd
Restoring npm packages for EOC-TeamsFx (this can take several minutes)
"C:\home\site\repository"
Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

npm notice 
added 1662 packages in 7m
npm notice New major version of npm available! 8.19.2 -> 10.2.0

246 packages are looking for funding
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
  run `npm fund` for details
npm notice Run `npm install -g npm@10.2.0` to update!
npm notice 
Building the client app (this can take several minutes)

> teamsfx-template-tab@0.1.0 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Compiled with warnings.

[eslint] 
src\components\IncidentDetails.tsx
  Line 1349:56:  Array.prototype.map() expects a return value from arrow function     array-callback-return
  Line 2003:31:  'additionChannelsPromise' is assigned a value but never used         @typescript-eslint/no-unused-vars
  Line 2745:58:  Array.prototype.filter() expects a return value from arrow function  array-callback-return

src\components\Tasks.tsx
  Line 170:25:  Nested block is redundant  no-lone-blocks

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  721.09 kB  build\static\js\main.da5b23ca.js
  41.36 kB   build\static\css\main.9011790f.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

Creating app_offline.htm
KuduSync.NET from: 'C:\home\site\repository\EOC-TeamsFx\tabs\build' to: 'C:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: 'asset-manifest.json'
Copying file: 'auth-end.html'
Copying file: 'auth-start.html'
Copying file: 'deploy.png'
Copying file: 'favicon.ico'
Copying file: 'hello.png'
Copying file: 'index.html'
Copying file: 'publish.png'
Copying file: 'static\css\main.9011790f.css'
Copying file: 'static\css\main.9011790f.css.map'
Copying file: 'static\js\main.da5b23ca.js'
Copying file: 'static\js\main.da5b23ca.js.LICENSE.txt'
Copying file: 'static\js\main.da5b23ca.js.map'
Copying file: 'static\media\ActiveBridgeIcon.3bb0430e4e11c4b1a05bc9287151abbf.svg'
Copying file: 'static\media\ActiveIcon.f9fb4e63a199b5a04c5e13fa13e0b149.svg'
Copying file: 'static\media\ActiveItems.f0ecbe804cfe98e18401.svg'
Copying file: 'static\media\ActiveItems.f0ecbe804cfe98e184010f0b83475fee.svg'
Copying file: 'static\media\ActiveItemsSelected.b022496617d20cf7fa3d.svg'
Copying file: 'static\media\AddIcon.337046ac938daca1b01eedaa2cfaa0ee.svg'
Copying file: 'static\media\AddRole.0ca4dd3bb815809c0cb66af6bc9bf7cb.svg'
Copying file: 'static\media\AdminSettings.f76bba3b08cb99702d659f247e889ecc.svg'
Copying file: 'static\media\AllItems.279e451759322fcdb78e.svg'
Copying file: 'static\media\AllItems.279e451759322fcdb78e5a915309832c.svg'
Copying file: 'static\media\AllItemsSelected.0e42daa2e8e96694eb40.svg'
Copying file: 'static\media\AppLogo.26a3793d228728847b3126c0fbc6895e.svg'
Copying file: 'static\media\ButtonEditIcon.ad8f1f82093ae8ef72bc1449607b1622.svg'
Copying file: 'static\media\ClosedIcon.0683460b84f933c270d4b644e90a5c23.svg'
Copying file: 'static\media\ClosedItems.2c7115a1dbc9d7ccfe97.svg'
Copying file: 'static\media\ClosedItems.2c7115a1dbc9d7ccfe977494f43ab3cf.svg'
Copying file: 'static\media\ClosedItemsSelected.aef43204e73fe0596c47.svg'
Copying file: 'static\media\CloudIcon.20b3b7211a482637c83fd5a402a2aeec.svg'
Copying file: 'static\media\DeleteBoldIcon.55c3e3d0fd8c097640e7679d927d161a.svg'
Copying file: 'static\media\DeleteIcon.a9c07dc43f11c90d1c8cab1fef2a193d.svg'
Copying file: 'static\media\EditIncidentBoldIcon.9c7fc4ba96cdf347c01eed699cc97d66.svg'
Copying file: 'static\media\EocSubheader.950e5cf5e7e724298368.svg'
Copying file: 'static\media\FeedbackIcon.094038d0d04f8fe46faad448feef693f.svg'
Copying file: 'static\media\GridEditIcon.40dbf33163a94797f988b6d5b6acda00.svg'
Copying file: 'static\media\HelpIcon.2940cb9a30a2f328c3e508eddcb8717a.svg'
Copying file: 'static\media\IncidentHistoryBoldIcon.67e37ceb9b097477a06bda2f67504d6a.svg'
Copying file: 'static\media\IncidentHistoryIcon.34da49f56ea19810ea6b60ade15bd641.svg'
Copying file: 'static\media\InfoIcon.c1493eeb7d8e103d753de9a914f99063.svg'
Copying file: 'static\media\ListViewIcon.bcca38dfd531abcb5ff034a8daa9b9fc.svg'
Copying file: 'static\media\Manage Incident Types.2bca030dd668209af9c464fb5fc24cbe.svg'
Copying file: 'static\media\Manage Roles.2ab947374f17d480e534099538ab8264.svg'
Copying file: 'static\media\ManageIcon.9e649e392204438abd3a980f7d5eb64f.svg'
Copying file: 'static\media\ManageIconActive.e5ca47a765314f4833679979b08361d5.svg'
Copying file: 'static\media\NewsIcon.5e23ac466f605fa578d437ce42c720d7.svg'
Omitting next output lines...
Finished successfully.

**Comment by v-asshrirao** [comment]
@hepburnhelpdesk, 
Can you please share few more details which will help us to troubleshoot better.
1. Can you share the site name you are using when running provisioning script?
Please note 'Site name cannot contain symbols other than underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period.'
2. Can you also share screenshot to verify if deployment is successful,
Navigate to resource group created and share deployment screenshot.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/f9bc4065-726b-4571-81aa-2bb5c9bad597)

**Comment by hepburnhelpdesk** [comment]
TenantName = hepburnshirecouncil
AdminEmail = webeoc@hepburn.vic.gov.au
SiteName = hepburnwebeoc

When I try to upload files (Screen Caps) I get Something went really wrong, and we can't process that file.....
[WEB Capture.docx](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12851333/WEB.Capture.docx)
