### ISSUE TITLE
Blank App in Teams

### ISSUE THREAD

**Issue by bderry71** [OfficeDev/microsoft-teams-emergency-operations-center#143]
We've got a issue where the app loaded once and was able to see it once. Then realized it took over the Chat Channel of where ever I put the Tab. So I deleted it and made a new channel then added the tab back. Then it came up blank. Then I deleted the whole team and rebuilt it. Added the second Channel then added it back to a tab. It still came up blank.

How do I get the logs you want?

**Comment by v-asshrirao** [comment]
@bderry71 , Please follow below steps to generate logs.
1. Open teams in browser. 
2. Open developers tools. 
3. Open console and make sure all below options are checked.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/001cef14-c5fa-4005-8c53-f7364db7fb05)
4. Refresh browser and try reproducing the issue and share the logs generated in console.

**Comment by bderry71** [comment]
[teams.microsoft.com-1696880269062.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12849786/teams.microsoft.com-1696880269062.log)

**Comment by v-asshrirao** [comment]
@bderry71 , Thank you for sharing the logs with us.
Can you please confirm if you are able to access SharePoint site and root site collection.

**Comment by bderry71** [comment]
Yes, I can get to the Site as I built it.

**Comment by v-asshrirao** [comment]
@bderry71, Please allow us some time to analyse this and we will get back to you ASAP.

**Comment by bderry71** [comment]
OK. I clicked the link and this is what I got back.

`<div id="content"><div class="tabs tabs-tall "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="Filter JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">

  |  
-- | --
error |  
code | "InvalidAuthenticationToken"
message | "Access token is empty."
innerError |  
date | "2023-10-19T15:09:10"
request-id | "6981799b-48a7-434d-aa08-6d11d3726fa1"
client-request-id | "6981799b-48a7-434d-aa08-6d11d3726fa1"

</div></div></div></div>`

**Comment by bderry71** [comment]
I was never prompted for login with that link.

**Comment by bderry71** [comment]
I also tried it with a Outlook.office365.com/mail session and it gave the same error:

`{"error":{"code":"InvalidAuthenticationToken","message":"Access token is empty.","innerError":{"date":"2023-10-19T17:04:35","request-id":"ae5b16aa-2d2e-4f00-a750-d640f451dc16","client-request-id":"ae5b16aa-2d2e-4f00-a750-d640f451dc16"}}}`

**Comment by v-asshrirao** [comment]
@bderry71, Did you try that with Graph API?
Can you please share screenshot of all the permissions you have configured for the App and if admin consent is granted for that?
<img width="632" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/34de49d8-cb44-4caf-aff1-345de895f161">

**Comment by bderry71** [comment]
Here is the current permissions setup.
![Screenshot 2023-10-20 at 9 05 54 AM](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/35855106/6974a0bd-3dfb-42b1-a4ca-c34319484ce3)

**Comment by v-asshrirao** [comment]
@bderry71, Please allow us some time to analyse this issue.
Meanwhile can you please try to add TEOC app in some other channel or open that as an app in teams instead of adding that in channel and let us know if its working?

**Comment by v-asshrirao** [comment]
@bderry71,Thank you for your patience.
Can you please confirm if you are the only one who is facing the issue and can you please also confirm if you have tried adding TEOC app directly instead of adding that in channel?

**Comment by vjanaga-exelixis** [comment]
We followed the deployment guide and performed all the steps, We are also facing the same issue when we add launch the app in Teams we are getting blank dashboard except Welcome message.

We also tried adding the app via channel and directly app also. in both the scenarios we are getting the blank screen.

Please find the attached Logfile, Blank app screenshot, Azure App Permissions
[TeamsEOC_Log.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13215651/TeamsEOC_Log.log)

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/d82ef594-9a71-42a0-8344-0bf7b9697b8a)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/af10db2f-bfcb-4f28-bb3f-241f2bb14e7f)
It would be great we can have update on the issue as we have tried all the possible options.
