### ISSUE TITLE
An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by KVNJSU** [OfficeDev/microsoft-teams-emergency-operations-center#144]
Hello,

I finally was able to install the entire solution, however everytime I try to submit an Incident it fails.

The user that has the application open and running is UPDTEOC_Admin and this user is actually the user that deployed the entire solution. This user has full admin rights on the underlying SharePoint. So I am confused why it does not let me submit an incident. And yes I selected a Start Date & Time, however it always gets removed once the error has occured. 

Thank you!

![2023-10-13_09-34-23](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/103125389/2d04db68-f144-4284-a6a1-a49880c6b07b)

**Comment by v-asshrirao** [comment]
@KVNJSU, Thank you for reporting this.
Can you open TEOC app in web version of teams and share console logs along with network trace with us, this will help us troubleshoot the issue.

**Comment by KVNJSU** [comment]
[teams.microsoft.com-1697464696570.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12917690/teams.microsoft.com-1697464696570.log)

**Comment by KVNJSU** [comment]
[teams.microsoft.com-1697464784604.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/12917704/teams.microsoft.com-1697464784604.log)
![2023-10-16_09-00-00](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/103125389/4c77c5a3-375d-4cd3-8ec9-a380ce9d9ae1)

**Comment by v-asshrirao** [comment]
@KVNJSU, It looks like there is restriction applied in your tenant for users to create M365 groups. Please check with your tenant administrator about the M365 group creation policy settings.

Please refer similar issue #113.

**Comment by KVNJSU** [comment]
@v-asshrirao Thank you for your help! The issue you linked pointed me in the right direction, I was able to create a special group. https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide

Again, thank you! This issue is resolved and can now be closed.
