### ISSUE TITLE
Deployment Script Fails

### ISSUE THREAD

**Issue by tjackson-bcg** [OfficeDev/microsoft-teams-emergency-operations-center#149]
While deploying the app, it creates the SP site but fails at what looks like List creation. The path to the XML is not long nor contains double quotes like most of the issues I see. I've deleted the site and rerun the script several times. I've also re-registered the PNP app accepting all permissions. Running as a global admin. What next?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/149440028/2d161d02-77cc-4df6-9769-34a3e21c9ac3)

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/149440028/60ed61b9-b958-48ba-8f3c-a395ebe39d4e)

**Comment by v-asshrirao** [comment]
@tjackson-bcg, Thank you for reporting this.
Can you please confirm if you are in GCC or GCCH tenant?
If its GCCH tenant you will have to run provisioning script for GCCH which will ask for PNP App Client ID which you have registered as mentioned.

Please do let us know if this helps.

**Comment by tjackson-bcg** [comment]
We have a GCC tenant, not GCCH.

**Comment by v-asshrirao** [comment]
@tjackson-bcg, 
We hope you are running the script with SharePoint Administrator user.

Can you please confirm which version of PnPPowershell you are using?

**Comment by tjackson-bcg** [comment]
When we are prompted for Azure login, we are specifying a global admin user which will have Sharepoint permissions by default. We are using version 2.2.114 of the PnP.PowerShell module in Powershell

**Comment by v-asshrirao** [comment]
@tjackson-bcg ,
Request you to kindly update the PnP version. Please run below commands and then try to run provisioning script again.
**Uninstall-Module -Name PnP.PowerShell -AllVersions -Force**

**Install-Module PnP.PowerShell -RequiredVersion 1.12 -Force**

Please let us know if this help.

**Comment by tjackson-bcg** [comment]
Downgraded PnP to 1.12 and re-ran the script. Same issue occurs. I was also using Powershell 7 originally and am now using Powershell 5.2. There is a slightly different error now.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/149440028/17bd3347-db44-4775-b059-7b0064a92e55)
