### ISSUE TITLE
Teams app is blank

### ISSUE THREAD

**Issue by msternick** [OfficeDev/microsoft-teams-emergency-operations-center#150]
I've successfully deployed everything with no errors but I do not see anything in the Teams app.
<img width="1231" alt="2023-11-03 13_55_39-TEOC _ Microsoft Teams classic" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/b730b5f9-9b9d-41e7-9a5b-6410356106f8">

**Comment by v-asshrirao** [comment]
@msternick, 
Open TEOC app in web version of teams and share console logs and network trace.

Also share manifest files with us to troubleshoot the issue further.

**Comment by msternick** [comment]
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13266360/manifest.json)
[teams.microsoft.com-1699272578670.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13266361/teams.microsoft.com-1699272578670.log)
<img width="724" alt="2023-11-06 07_29_49-network_trace" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/dbe3c2f6-55fd-4642-8d50-4bdf82c24e6e">


The network trace is a a screenshot of the only error popping up saying my index.html file can't be found.  Thank you for the help!

**Comment by msternick** [comment]
<img width="1223" alt="2023-11-06 08_36_31-Microsoft Teams classic" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/94a36f0a-7bc3-4cdc-9668-f9980a475ff1">

quick update...I realized that the simpleauth web site created was not the domain and updated everything to point to eocteams.azurewebsites.net (including the app config).  I'm now getting prompted for a login but pressing the button just flashes a pop up and it goes away (I even disabled pop up blocker).

**Comment by v-asshrirao** [comment]
@msternick, Can you please share the updated logs.

**Comment by msternick** [comment]
So I ran through everything and did fix the login prompt.  Now I get the same error as the user who just reported after me.  I did check the app service REACT_APP_SHAREPOINT_SITE_NAME and updated it to TeamsEOCSite...also had to fix the End Point.  Take note of this call in the browser to graph...is this correct?
<img width="1216" alt="Graph call error 2023-11-06 09_24_07-Microsoft Teams classic" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/59ae966c-3f9b-4b06-8fd3-fb6f89aadfb2">

**Comment by msternick** [comment]
@v-asshrirao any luck?  I have a customer who is looking at implementing this solution.

**Comment by v-asshrirao** [comment]
@msternick, Site name in graph is incorrect, Its coming as 'TeamsEOC' it should be 'TeamsEOCSite', Please make sure to update the REACT_APP_SHAREPOINT_SITE_NAME and restart the app service.

Please let us know if this helps?

**Comment by msternick** [comment]
@v-asshrirao I did that, site name is still wrong

**Comment by v-asshrirao** [comment]
@msternick, 
Can you please confirm if you have restarted the AppService after updating the value?

**Comment by msternick** [comment]
@v-asshrirao yes I restarted the app service after the value was updated

**Comment by v-asshrirao** [comment]
@msternick, Can you please confirm if it resolve the error?

**Comment by msternick** [comment]
@v-asshrirao it did not resolve the error

**Comment by v-asshrirao** [comment]
@msternick, Can you please share the console logs and network trace with us

**Comment by msternick** [comment]
[teams.microsoft.com-1699368292815.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13281783/teams.microsoft.com-1699368292815.log)

I'm not sure how to share the network trace with you.  I won't allow me to upload a .har file here

**Comment by v-asshrirao** [comment]
@msternick,

Site Name is still not updated, which is why its not working.
https://graph.microsoft.com/v1.0/sites/m365x85651792.sharepoint.com:/sites/TeamsEOC?$select=id 404 (Not Found)

Please try to restart the simpleAuthAppService as well. Sometimes it will take some time to reflect.

**Comment by msternick** [comment]
@v-asshrirao I've waited for awhile after refreshing  both services and no luck.

**Comment by v-asshrirao** [comment]
@msternick, Can you please share the screenshot of REACT_APP_SHAREPOINT_SITE_NAME ,configuration which you have done?

**Comment by msternick** [comment]
<img width="1222" alt="REACT_APP_SHAREPOINT_SITE_Name_2023-11-08 09_06_15-EOCTeams - Microsoft Azure" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/89e32648-b0ee-4835-8de4-a4d19bcb9257">
@v-asshrirao  here you go

**Comment by msternick** [comment]
@v-asshrirao  my sharepoint site
<img width="1216" alt="2023-11-08 09_08_53-Teams EOC Site - Home" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/72033157/58b9984e-0121-4efb-8b74-77710d0e2de5">

**Comment by v-asshrirao** [comment]
@msternick, 
Okay, can you try clearing the browser cache and launch the TEOC app to see whether that works? If you still see any issues, can you check the following - In Azure portal, navigate to TEOC resource group, open app service and click on Advanced Tools, click on Go and then click on App Settings.
<img width="469" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/360091ba-f216-4a53-ac36-eff974fc91e2">
Check for the REACT_APP_SHAREPOINT_SITE_NAME variable and see if that has correct site name without any special characters.
<img width="478" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/4d57bd18-5a2b-4938-817c-40017063cfce">

**Comment by v-prigunasek** [comment]
Hi @msternick ,

I see you have updated the site name in App settings. Could you please perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version) to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.
