### ISSUE TITLE
Blank Dashboard in Teams

### ISSUE THREAD

**Issue by vjanaga-exelixis** [OfficeDev/microsoft-teams-emergency-operations-center#151]
We followed the deployment guide and performed all the steps, We are facing the issue when we add launch the app in Teams we are getting blank dashboard except Welcome message.

We also tried adding the app via channel and directly app also. in both the scenarios we are getting the blank screen.

Please find the attached Logfile, Blank app screenshot, Azure App Permissions
[TeamsEOC_Log (2).log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13266577/TeamsEOC_Log.2.log)
![TeamsEOC_blank](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/78230012-8716-4f40-bbd6-ce07487cfb03)
![TeamsEOC_AppPermissions](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/7ebfe8ce-fa8c-4194-80fd-b1324018b354)

We also tired removing the app and re adding again but we are getting the same issue.
It would be great we can have update on the issue as we have tried all the possible options.

**Comment by msternick** [comment]
@vjanaga-exelixis any luck?  I have a customer who is looking to implement this solution.

**Comment by vjanaga-exelixis** [comment]
Hi,
We are not able to see the REACT_APP_SHAREPOINT_SITE_NAME configuration in app service. We are getting the below configuration settings
![AppService_ConfigurationSettings](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/8cb2c3f8-068c-46f1-9aa5-cfa775c01653)

Please find the attached mainfest file

[TEOC.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13335452/TEOC.json)

Please let us know if you need any other information

**Comment by v-prigunasek** [comment]
Hi @vjanaga-exelixis,

It seems like you don't have enough permissions to view the Application settings. Can you please reach out to the Azure Administrator or the respective internal team to get the value updated for REACT_APP_SHAREPOINT_SITE_NAME app settings  to **TeamsEOCSite** instead of the full URL ?
Once that is updated, then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service. Once that is done, open the app in teams and verify if that works as expected.

**Comment by vjanaga-exelixis** [comment]
Hi,
As per your instructions we have updated the REACT_APP_SHAREPOINT_SITE_NAME app settings to TeamsEOCSite and restarted the app service.
After that when we click on the link [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), its redirecting to the step3 Sync latest version. and while performing sync step we stuck here. we are able to see the previous action step. please find the screenshot
![TEOC_Log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/101700267/f13a43d0-c6a3-44f7-bbb6-693a9181e7e5)

Could you please provide the instructions for resolving this issue. Please let me know if you need any other information.

**Comment by v-asshrirao** [comment]
@vjanaga-exelixis , Can you try clearing the browser cache and launch the TEOC app to see whether that works? If you still see any issues, can you check the following - In Azure portal, navigate to TEOC resource group, open app service and click on Advanced Tools, click on Go and then click on App Settings.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/c4290fa4-2b3f-42e9-9d56-418790d8ce7b)

Check for the REACT_APP_SHAREPOINT_SITE_NAME variable and see if that has correct site name without any special characters.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/44842aba-5a12-4a95-9ab4-24b390401b84)
