### ISSUE TITLE
Launch Incident issue

### ISSUE THREAD

**Issue by rhawkins1** [OfficeDev/microsoft-teams-emergency-operations-center#152]
In order to launch a TEOC incident all members of our organization must have be able to create teams. Is there a way to launch an incident while limiting this to specific users?

**Comment by v-saikirang** [comment]
Hi @rhawkins1,

Thanks for reaching out to us. When a new incident is created, a teams is also created in the back end. So every user who is creating an incident needs to have the  permission to create teams.

Please let us know if you need additional information.
Thanks.

**Comment by rhawkins1** [comment]
I understand. But, when we try to create incidents, we have found that all members of the organization must be able to create Teams, not just the person creating the incident. We would like to limit the ability to create teams to just users who create incidents. Is this possible?


RACHAEL HAWKINS
MANAGER, PROJECTS
Avelo Airlines

[Transparent Phone Icon #197438 - Free Icons Library]
(346) 299-5725 x8047
[Office Address Icon #33907 - Free Icons Library]
12 Greenway Plaza, 4th Floor, Mailbox #30, Houston, TX 77046
 ***@***.*** <https://aveloair.com/>
Follow Avelo on:
LinkedIn<https://www.linkedin.com/company/avelo-airlines> | Twitter<https://twitter.com/AveloAir> | Facebook<https://www.facebook.com/aveloair> | Instagram<https://www.instagram.com/aveloair>
Connect with me on LinkedIn<https://www.linkedin.com/in/rachael-hawkins/>


From: v-saikirang ***@***.***>
Sent: Tuesday, November 14, 2023 6:20 AM
To: OfficeDev/microsoft-teams-emergency-operations-center ***@***.***>
Cc: Rachael Hawkins ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-emergency-operations-center] Launch Incident issue (Issue #152)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

Hi @rhawkins1<https://github.com/rhawkins1>,

Thanks for reaching out to us. When a new incident is created, a teams is also created in the back end. So every user who is creating an incident needs to have the permission to create teams.

Please let us know if you need additional information.
Thanks.

**Comment by v-saikirang** [comment]
Hi @rhawkins1, You can limit the access to create M365 groups to few users also by creating a group and assigning to users to that group. Please refer to [link](https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide) for details.

Please let me know if you need more information.
Thanks.
