### ISSUE TITLE
Auth Issue with TEOC App in Teams 

### ISSUE THREAD

**Issue by Liveingeo** [OfficeDev/microsoft-teams-emergency-operations-center#153]
Hi Team,

All the deployments steps are followed as per the deployment guide and now when we try to access the TEOC app from teams it given a login button on click of which nothing happens just a pop-up shows up and goes without any results.

<img width="1260" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/148341800/91c2aa6c-c441-4706-9eea-d00d93cc262e">

 on the console the below logs are recorded:
 
<img width="601" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/148341800/e17f68c1-664d-4a1c-be5b-ce64a51a5c05">

**Comment by v-prigunasek** [comment]
Hi @Liveingeo ,

Thanks for reaching out. I would suggest you validate some of the below items.
1. Verify the deployment is successful without any errors.
2.  Check the azure app manifest file to ensure all the changes are done as per the [documentation.](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-set-up-authentication)
3. If you don't see any issues with these, please replicate the error in browser version of teams and share us the log file and  network trace (Har file) for further troubleshooting.

**Comment by Liveingeo** [comment]
Hi Team,

Any update on this issue fix.

**Comment by v-prigunasek** [comment]
Hi @Liveingeo ,

Thanks for sharing the Har file. Can you please open the baseresourcesimpleauth app service and try adding https://baseresource.azurewebsites.net as an allowed origin in the CORS settings? 

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/98514691/7200e1aa-642c-4fb0-b304-5de94469b277)

Then restart that Simple Auth app service and verify the behavior. If the issue still persists, I would recommend you to do the fresh deployment from the scratch with the new unique base resource name. Please let us know if you need any additional information.

**Comment by Liveingeo** [comment]
Hi @v-prigunasek ,

We added https://baseresource.azurewebsites.net/ as an allowed origin in the CORS settings and restarted the  Simple Auth app service but the issue still persists. 

We can try a fresh installation but could you let us know if there is anything which we need to be mindful of in this attempt as we followed the deployment steps last time as well?

**Comment by Liveingeo** [comment]
@v-prigunasek : With the redeployment the issue got resolved , I believe it was the  Base Resource name needs to be all lowercase without special char or space was the key to the fix.
