### ISSUE TITLE
EOC Site name Fails

### ISSUE THREAD

**Issue by CBoltonAU** [OfficeDev/microsoft-teams-emergency-operations-center#154]
Everything is fine up until entering the Site name.  Anything we try returns the error cannot contain symbols etc.
![Untitled](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/152133705/b3cdb778-635f-4d16-9231-98729c0613de)

**Comment by v-asshrirao** [comment]
@CBoltonAU, Thank you for reporting this.
Can you please confirm below points,
1. User trying to run PowerShell script has SharePoint Administrator Access.
2. PowerShell is running as Administartor.
