### ISSUE TITLE
Update to Incident Status does not Change the Dashboard columns showing the status

### ISSUE THREAD

**Issue by Liveingeo** [OfficeDev/microsoft-teams-emergency-operations-center#155]
Hi Team,

The changes done to the Incident Status list does not reflect on the dashboard, it only shows All, Planning , Active and Closed. For e.g. i added a new status Enhanced that shows up in the drop drop during Incident creation but even if a incident is created with the new status it does not appear as a new status column in dashboard.

<img width="400" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/148341800/a6bd1dae-b4ef-4208-9f85-8918767926bc">

And if the existing status Active , planning or closed are renamed then on click of new incident it keeps loading.

Is the customisation of the incident status not reflected on the Dashboard.

<img width="1021" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/148341800/1b32b26c-1249-4239-99b1-8af183160c49">

**Comment by v-asshrirao** [comment]
@Liveingeo, 
We don't have this feature currently, but thank you for your feedback.
We will try to add this feature in our future releases if possible.
