### ISSUE TITLE
Incidents created by one user is not editable by other user with Access to the dashboard.

### ISSUE THREAD

**Issue by Liveingeo** [OfficeDev/microsoft-teams-emergency-operations-center#156]
Hi Team,

The Incident dashboard is to be manged by a team if emergency responders , but the incident created by a user is only editable by that user, when other users tries to edit it gives below error:

<img width="791" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/148341800/98d9a2d2-f061-42b8-bb1b-9216266a0249">

Could you guide us on what permission is missing.

**Comment by v-asshrirao** [comment]
@Liveingeo,
Only Incident Commander or Secondary Incident Commanders will be able to update the incident.
If user want access to edit incident he must be in any of the roles.

**Comment by Liveingeo** [comment]
Thanks @v-asshrirao for the quick response, am I right to say that the user creating the incident is the Incident commander by default and the ones you add to the Incident commander section are the secondary Incident commanders.

**Comment by v-asshrirao** [comment]
@Liveingeo, We have separate role added as secondary incident commander under roles assignment > Roles dropdown.
We can add secondary incident commander by assigning that role to the user who need access to edit the incident.
 
<img width="282" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/63199fdf-c876-4d36-bab7-b2c883639e03">

**Comment by rochhb** [comment]
(please note that I am not a T-EOC user, but have experience in emergency response planning to contribute)
using the role assignment that appears to reflect NIMS-ICS, I would recommend that an incident to be editable by anyone assigned to the role of IC, Deputy IC, and Planning. Although an IC may be able to create / edit an incident, the role to manage the incident information usually falls to the Planning Section. So, for TEOC functionality to reflect the real-life management of incident response, the incident must be able to be managed by those 3 roles. All other functions would be coordinating with IC and Planning, including submitting their own set of incident documentation that IC or Planning would be able to add to the incident as it expands/evolves and resolves. If the incident is so complex that it requires the other response roles / Sections, then it is Planning Section that would be coordinating the flow of incident reporting.
(Now all I have to do is get internal support to deploy the TEOC app...hmmm!!! Happy to receive feedback on this comment, as on TEOC benefits/challenges from others in support of own response system)

**Comment by v-asshrirao** [comment]
@rochhb, Thank you for your suggestion. We are planning to add this in our upcoming release.

**Comment by v-asshrirao** [comment]
@Liveingeo, Can you please confirm if you need more details or we can close this issue?

**Comment by v-asshrirao** [comment]
@Liveingeo, We will close this issue. In case more details required please create new ticket.
