### ISSUE TITLE
Create New Incident and Manage buttons not visible

### ISSUE THREAD

**Issue by chrisaanz** [OfficeDev/microsoft-teams-emergency-operations-center#158]
Hi there, I've been successfully running TEOC for a while and recently the "Create New Incident" and "Manage" buttons have disappeared. 

Nothing has been changes to cause this issue. Note, the Teams app has been recently updated to the New Teams app. 

Can anyone please provide some advise to resolve this issue and any known compatibly issues with the New Teams client.

**Comment by v-asshrirao** [comment]
@chrisaanz, Thank you for reporting this.
It looks like Admin enabled Role based setting in the App which is why "Create New Incident" and "Manage" buttons are not visible to you.

Please refer similar issue #146

**Comment by chrisaanz** [comment]
This would not have been enabled and I can't see where roles are enabled in the app to stop this functionality.  Can you please provide some further details.

**Comment by chrisaanz** [comment]
Hi there, just wondering if you can provide some additional recommendations to resolve this issue. Thanks

**Comment by v-asshrirao** [comment]
@chrisaanz, Apologies for delayed response.
Can you please confirm below,
Navigate to admin settings > Role Settings and check if the setting is enabled and share screenshot.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/f19f73e4-fd0f-43b9-8ec4-a89b67429035)

Navigate to SharePoint site and from site contents open TEOC-Config list and check below setting,
<img width="374" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/73534a36-16bd-4cbe-b088-ea7a7ca5bb51">

**Comment by FENZInfrastructure** [comment]
Hi there, I changed the TEOC-Config value to false and the buttons have now appeared. 

Are you able to explain please what has changed that required us to update the value? This was definitely not manually changed by anyone.

Thanks

**Comment by chrisaanz** [comment]
Issue has been resolved. Thanks you your assistance.
