### ISSUE TITLE
update the Location field with a specific list with csv or sharepoint list or adding to the program

### ISSUE THREAD

**Issue by markre1278** [OfficeDev/microsoft-teams-emergency-operations-center#159]
Hello i was hoping to update the location field with a specific list of locations, is that possible?  Can it be  a sharepoint list that can be updated regularly?

**Comment by v-asshrirao** [comment]
@markre1278, Thank you for your suggestion.
Currently location field is free text field where user can add any value. So you will not be able to update it with specific locations. However, we are planning to update that as location picker in our future release.
