### ISSUE TITLE
Authentication window disappearing

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#160]
Hi we have followed the instructions and have added the EOC app to a team but when go to login for the first time as described [here](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#first-load-experience). 

The authentication window will appear for a brief second and then close immediately. Did I misconfigure something that would cause that?

**Comment by BCG-cmori** [comment]
Also to note this is the error that populates when viewing the the developer tools. 

![eoc-dev](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/130778120/cbe1b5c1-8873-428e-974d-bea49f80a8b4)

**Comment by v-asshrirao** [comment]
@BCG-cmori, Thank you for reporting this.

Please refer similar issue #153. 
Let us know if this helps.

**Comment by BCG-cmori** [comment]
I went ahead and trying it from a clean start. I am now getting this error. 

![error message](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/130778120/3054dbb8-cf61-4a38-9440-cd9f6a65ec0c)
