### ISSUE TITLE
TEOC Sign-in Error

### ISSUE THREAD

**Issue by stchurch2** [OfficeDev/microsoft-teams-emergency-operations-center#161]
Just went through Setup of TEOC. I am trying to sign-in to TEOC and I am getting an error... Double checked the Redirect Url From Step 4. any assistance would be appreciated. Thanks 

![Teams_Teoc](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/67389934/771cf692-4fca-4896-b932-3a1563f46b5c)
![TEOC](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/67389934/881c00aa-3967-4f5f-a7bd-9b863aa5964b)

**Comment by v-asshrirao** [comment]
@stchurch2, Thank you for reporting this.
We will need some information from you to troubleshoot this.
Please confirm is deployment was successful and all resources are created.
Open TEOC app in browser version of teams and share console logs and network trace with us.

**Comment by stchurch2** [comment]
Hi 
Thanks you for the reply. YEs the deployment was successful. I opened Teoc in edge browser opened (classic) teams and launched Teoc.  having trouble with har file since this site does not accept it. Please advise. Thanks again
[Teoc_Console.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13978110/Teoc_Console.log)

**Comment by v-asshrirao** [comment]
@stchurch2,
I could see from the logs that this request was failing - POST https://login.microsoftonline.com/your-org-tenant-id/oauth2/v2.0/token 400 (Bad Request)

This error normally occurs when there are some configuration issues in the [authentication setup](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-set-up-authentication). Can you please verify this step again and make sure all the URLs are correctly configured? If everything is right and you still see issues, please share manifest files with us for troubleshooting.

**Comment by stchurch2** [comment]
Hi 
I went through authentication setup again and still having same issue.

**Comment by v-asshrirao** [comment]
@stchurch2,
We request you to kindly share the manifest files with us so that we can validate and help you with this.

**Comment by stchurch2** [comment]
Hi
I have started over. I am at step 4  Set-up Authentication. I will continue with the build out. I have had other issues come up at work so that is why there was a delay.

**Comment by v-asshrirao** [comment]
@stchurch2, You can find Teams WebApp Client Id from the App Registration you have done in [Step 2](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#2-register-azure-ad-application).
Navigate to the App Registration and copy the Application ID from the overview section.
<img width="566" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/7c73e45f-3a69-4bf5-9b61-e8a77f0d038d">

**Comment by stchurch2** [comment]
Hi 
Sorry for the delay. So I started completely over.  I am working on completing this today. I will give update soon. Thank you  for your Patience.

**Comment by stchurch2** [comment]
I am finished with the uploading all the steps. I do not see Teoc in Teams.

**Comment by stchurch2** [comment]
Hi 
I finally have it running have to go into teams admin center and allow Teoc as a custom app. Thanks For your Time!!

**Comment by v-asshrirao** [comment]
@stchurch2,
Glad to hear that it worked. We will go ahead and close this ticket now.

**Comment by stchurch2** [comment]
the fix was to  delete everything and start over. Once that was done the last step which is not mentioned in the how to was to go to teams admin center  permission policies  and selected the Teoc custom app from there in the "custom apps" I selected allow specific apps and block all others. Teoc launched and opened with no issues
