### ISSUE TITLE
Standard TEOC Channels and Automatic File Import

### ISSUE THREAD

**Issue by GrapevineEM** [OfficeDev/microsoft-teams-emergency-operations-center#162]
I have two things I am working on and am looking for ideas. 

When an incident is created, a team is created in MS Teams that contains a standard list of channels. I'd like to modify that list to reflect the sections within my Emergency Operations Center organization. 

The second thing I'd like to do is create an automation that imports a set of job aids, forms, and other important files to a channel immediately when it is created. These files would come from a document library that is maintained in SharePoint.

Any ideas on how I can do this?

**Comment by v-asshrirao** [comment]
@GrapevineEM, Thank you for your queries,
Adding custom channels for incident feature is already planned for next release.
Uploading files when incident is created feature is something we are planning to take in our future releases based on feasibility and priority.

I will be closing this ticket for now please reopen or create new ticket if you have any queries.
