### ISSUE TITLE
Costs

### ISSUE THREAD

**Issue by cpdonohue** [OfficeDev/microsoft-teams-emergency-operations-center#167]
I can see the cost estimates, but what drives those costs?  Is it the number of incidents, number of participants, or something else? 
Thanks.

**Comment by v-asshrirao** [comment]
@cpdonohue, Cost estimate is not based on the number of incidents or number of participants, its just the resources we are using and the App Service Plan we are selecting that will decide the cost. 
For using this application as mentioned in the wiki we have to use S2 Service Plan.

Hope this helps. In case you need additional details please let us know.

**Comment by cpdonohue** [comment]
OK I can see that.  What drove the decision to use S2/Premium V2?  Can we use a lower say S1/Standard?  Or what would cause us to move up to a S3?  Just trying to get a sense so we can estimate costs.

**Comment by v-asshrirao** [comment]
@cpdonohue, 
You will need minimum 3.5GB of memory for building the app that is the reason why we are using S2 App service plan.

**Comment by v-asshrirao** [comment]
@cpdonohue, We will go ahead and close this ticket.
If you need more information related to this, you can reopen this or create new ticket.
