### ISSUE TITLE
Email signup link on microsoft.com is broken

### ISSUE THREAD

**Issue by schmeed** [OfficeDev/microsoft-teams-emergency-operations-center#168]
https://aka.ms/teocgetstarted on https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/emergency-operations-center/ ends up in a 404.

I realize this isn't an issue with this code directly, but I also know it's infinitely impossible to submit microsoft.com website issues effectively.

**Comment by v-asshrirao** [comment]
@schmeed, 
Please allow us some time. We will try to check this and get back to you ASAP.

**Comment by schmeed** [comment]
I see the form is now available.  Link working.  Closing issue as resolved.
