### ISSUE TITLE
EOC Demo or learning session?

### ISSUE THREAD

**Issue by rochhb** [OfficeDev/microsoft-teams-emergency-operations-center#171]
Does anyone know if MS offers demo for Teams EOC or offer self-driven learning session to demonstrate the solution once built/deployed?

The following link from the MS EOC website used to provide opportunity for MS to contact you: https://aka.ms/teocgetstarted . The link is no longer working.

thanks!

**Comment by v-asshrirao** [comment]
@rochhb, We are looking into this issue. Please allow us some time and we will try to get back to you ASAP.

**Comment by v-saikirang** [comment]
Hi @rochhb,

MS does not provide any Demos. But you can refer to [Github Wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki) section and [https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/emergency-operations-center/](https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/emergency-operations-center/) for more information on the App.

Thanks.
