### ISSUE TITLE
Line 72- Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -Warning … - File not found

### ISSUE THREAD

**Issue by IFIT-BruceG** [OfficeDev/microsoft-teams-emergency-operations-center#172]
I've got the TEOC script to run all the way to line 72 where the command is "Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -WarningAction SilentlyContinue". There it stops with a "File not found" error. I have confirmed that the file is right where the variable says it should be.

CODE SNIP IT FROM THE POWERSHELL RUN:

================================================================================== 
PnP.PowerShell module found
Creating lists in XXXXX Site site <--(Site name hidden on purpose)
File Path is C:\TEMP\Cybersecurity_Incident_Response_Plan\TEOC\TEOC_Installation\Deployment\provisioning <-- (I added this and the following line for troubleshooting clarity)
Press ENTER to continue...: <--(Added by me)
Invoke-PnPSiteTemplate: C:\Temp\Cybersecurity_Incident_Response_Plan\TEOC\TEOC_Installation\Deployment\provisioning\EOC-Provision.ps1:72
Line |
  72 |      Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -Warning …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | File not found
PS C:\Temp\Cybersecurity_Incident_Response_Plan\TEOC\TEOC_Installation\Deployment\provisioning>

==================================================================================
AS CAN BE SEEN FROM THE LAST LINE ABOVE, I AM IN THE CORRECT FOLDER WHEN I RUN THE "EOC-Provision.ps1" FILE IN THE FIRST PLACE. 
SHOULDN'T THE COMMAND "Invoke-PnPSiteTemplate: ..." BE LOOKING FOR THE "EOC-SiteTemplate.xml" FILE, AND NOT THE "EOC-Provision.ps1" FILE?

WHEN I RUN THE COMMAND "get-Module -Name PnP.PowerShell -ListAvailable", IT RETURNS THE FOLLOWING:

Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
Manifest   2.3.0                 PnP.PowerShell                      Desk      {Add-PnPAdaptiveScopeProperty, Add-PnPEntraIDGroupMember, Add-PnPEntraIDGroupOwner, Add-PnPEntraIDServiceP…

==================================================================================
BELOW IS THE PROPERTIES OF THE "EOS-Provision.ps1" FILE SHOWING THE PATH TO THE FILE. 
THE "EOC-SiteTemplate.xml" FILE IS IN THE SAME FOLDER LOCATION.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/6fa1ce05-4753-4cb5-9340-1628d33e8c38)

HOPEFULLY THERE IS AN EASY FIX FOR THIS

**Comment by v-asshrirao** [comment]
@IFIT-BruceG, Thank you for reporting this.
Can you please confirm if you have provided full path for xml as shown in the screenshot below and as mentioned in the wiki?
<img width="509" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/362cf29a-06ca-438e-84f6-7585570554cc">
Invoke-PnPSiteTemplate is looking for the xml file.
Can you please provide xml file path as mentioned and let us know if its working for you?

**Comment by IFIT-BruceG** [comment]
v-asshrirao,

The two phrases, “Illegal headspace error” and “Brain Fart” equally describe my inability to see and comprehend that simple bit of information as it was written in the Wiki.
Thank you for taking the time to point this out to me, I am now able to progress to the next stage of setting up TEOC!

Thank you,

Bruce Garoutte
Network Security Engineer
Industrial Finishes and Systems, Inc.

***@***.***
541-206-4393 – cell
industrialfinishes.com<https://industrialfinishes.com/>

***@***.***

**Comment by v-saikirang** [comment]
Hi @IFIT-BruceG ,

Thanks for confirming. I am closing this ticket. Please open a new issue if you still face any issues.

Thanks.
