### ISSUE TITLE
toggle for "Create or Modify Team Channels"

### ISSUE THREAD

**Issue by Jeffrey-AJG** [OfficeDev/microsoft-teams-emergency-operations-center#173]
With the switch turned off on `Create or Modify Team Channels`, we assume that it should not create a new team or channel. However, when we click on the button `Create New Incident`, it creates a team and channel in MS Teams. 

![TEOC](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160767195/f9b05162-cc67-469b-8588-72bb4429db68)

**Comment by v-saikirang** [comment]
Hi @Jeffrey-AJG,

Thanks for reaching out to us. Creating an incident will always create a Team and few default channels like General, Announcements e.t.c. The option "Create or Modify Team Channels" is an additional setting that will allow you to customize or create additional channels on top of the default channels. The TEOC solution is centered around an Incident linked to a Teams so the team can co-ordinate and leverage Teams effectively. So a Teams and default channels will always be created.

I hope i have clarified your question.  I am closing this ticket for now. But please let us know if you need more information.
Thanks.
