### ISSUE TITLE
Newbie Customization for Teams App

### ISSUE THREAD

**Issue by sebastianjimenezseti** [OfficeDev/microsoft-teams-emergency-operations-center#176]
Hello dev team,

First of all, I want to express my gratitude for creating such a comprehensive and well-thought-out app. As a newcomer to Teams apps, I'm eager to make some customizations to enhance this magnificent base.

Could you please provide instructions on how to run the tab app locally? Alternatively, any guidance on developing around this foundation would be greatly appreciated.

Thank you!

Best regards,

**Comment by v-ajaysahu** [comment]
@sebastianjimenezseti , Thank you for reporting this.
You can follow Customization Link from [Wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Customizations). Kindly let us know if you need anything else apart from this.
