### ISSUE TITLE
TEOC Teams app V3 shows new features in "Old" Teams, but shows legacy features in "New" Teams

### ISSUE THREAD

**Issue by kilianb-cosp** [OfficeDev/microsoft-teams-emergency-operations-center#177]
Updated Teams EOC to v.3 from v.1.  Update went fine, but had issues updating the Teams app.  Ended up deleting the existing Teams app and recreating it with the updated JSON zip file.  However, when looking in Teams, using the "New" Teams, the app is reported as version 1.0 and the dashboard looks the same as before.  When reverting to the "Old" Teams, the new dashboard features appear and the version is reported as 3.0.  We will have the users continue to use the "Old" Teams until the app is fixed for the "New" Teams.  I have included screen captures of both the "Old" and "New" Teams versions.  In the attached Word file, the "Old" Teams is in Dark Mode, and the "New" Teams is in Light Mode.
[TeamsEOC Update Screen Caps.docx](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14424038/TeamsEOC.Update.Screen.Caps.docx)

**Comment by v-ajaysahu** [comment]
@kilianb-cosp , Thank you for reporting this.
We've verified this in New Teams and we're not able to reproduce it. This could be a Cache issue. Can you please clear your cache and try again.
Kindly let us know if you're still facing this issue.
