### ISSUE TITLE
An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by IFIT-BruceG** [OfficeDev/microsoft-teams-emergency-operations-center#179]
I just got the TEOC operational. I'm running version 3.0.0. When I attempt to create a new Incident I receive the following error message "An error has occurred, please try to create your incident again". 

![Screen Capture of error](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/82645d26-0077-4571-ba06-47ebbd623478)

I followed the suggestion from a similar incident, " [Error creating incident #174](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/174)" and I added my user account to the Group Administrator Azure role.  This did not fix the issue for me.

Also, in the above incident, the following was requested, "Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.". 
If you need the same information from me, then you will need to tell me where to find each of these.

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG , Thank for reporting this.
Yes, we will need console logs and network trace in order to troubleshoot the issue.
Here are the steps to share the console logs and network trace -

1. Open Teams in browser
2. You need to Open Developer tool using F12 key or Ctrl+Shift+i or Go to Browser Menu and More Tools and then Click on Developer Tools and keep it Open
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/48afb80c-7cae-47d4-9cd1-11927cc66fa6)
3. Open TEOC application and try to replicate the issue.
4. Click on Console from developer tool and select everything copy it and share it.
5. Click on Network from developer tool click on down arrow button to export the network logs.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/e9a5e6a8-170c-4c23-b987-c36cfa7ec6ac)
6. And share the network logs.

And for Manifest file you should have generated it while creating Team app Package. Please share the Manifest file.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu Thank you for the quick reply and easy to follow instructions.
This is from the Console after attempting to create a incident. FTR. I can view the map under the “Map Viewer” tab, if that helps at all.

09:50:26.401 Source map error: request failed with status 404 Resource URL: https://statics.teams.cdn.office.net/hashed/lazy-ng1-mod-settings-dropdown-components.min-3ab6971.js Source Map URL: [[staticsPath]]/hashed/lazy-ng1-mod-settings-dropdown-components.min-a0f8b34.js.map
[teams.microsoft.com_Archive [24-03-08 09-55-49].har.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14541714/teams.microsoft.com_Archive.24-03-08.09-55-49.har.txt)

09:50:34.852
The returned id_token is not parseable. [3.1-app.min-7fda228.js:1:19434896](https://statics.teams.cdn.office.net/hashed/3.1-app.min-7fda228.js)

I have attached the network logs and the manifest file as you requested.

[teams.microsoft.com_Archive [24-03-08 09-55-49].har.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14541719/teams.microsoft.com_Archive.24-03-08.09-55-49.har.txt)
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14541726/manifest.json)

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG , Thank you for sharing the details.
We went through the logs, there is nothing related to TEOC. However, in Manifest file we found below points -

-  Website URL is incorrect. It has multiple HTTPS.
<img width="670" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/5995e181-80fc-4416-82f1-eb13fcfb07a2">

-  Valid Domains has extra Space.
<img width="359" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/ea19d580-eb5f-4566-9192-345ea21da4a1">

- App is old version. Request to upgrade it to 3.0.

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu 

I have made the corrections that you pointed out. I removed the old TEOC Tab from the Teams app, and re-loaded the new "teoc.zip" file containing the corrections. I have attempted to create an incident and receive the same "An error has occurred..." message. Below is a screen shot of that in case I'm missing something there.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/dd305b7d-14c3-45b2-ae64-7add4062842c)

I am confused over the version number thing. In the TEAMS app, it shows as "Current Version: 3.0.0., but in the online 'appvalidation' it show version 2.0. Screen shot below. I downloaded the TEOC on February 12, 2024, so shouldn't it be the correct version?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/9ab22c6f-c691-454e-84c5-6a1e7adad2a1)

If I do need to upgrade it, can you send me a link to the instructions on how to do that please?
Also, for good measures, I have added the most recent Console and Network log files from the Teams Web site Developer Tools.

[admin.teams.microsoft.com_Archive [24-03-12 13-14-08].har.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14578420/admin.teams.microsoft.com_Archive.24-03-12.13-14-08.har.txt)
[Web Console 3.12.24.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14578421/Web.Console.3.12.24.txt)

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG , 
In App Validation also TEOC version should be 3.0. Also, we had a release on 23rd Feb 2024.
Could you please download the latest version. And follow the Upgrade instruction from [here](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version).

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu 

I'm in!!  Thank you for all your help with this.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/4ff3a5a0-6f0e-4d05-acc1-a905c9dc8733)
