### ISSUE TITLE
Missing button to "Create New Incident"

### ISSUE THREAD

**Issue by MetalTark** [OfficeDev/microsoft-teams-emergency-operations-center#180]
Hi,
I'm experiencing some odd things with this app.  I got it successfully deployed on Tuesday and it worked briefly before having some authentication issues.  The issues resolved themselves yesterday, but now I no longer get the button to "Create New Incident" in the top of the app.  I am experiencing this with site Members and Site Owners.  Please see screenshots of the button appearing correctly previously and not appearing anymore.  Any guidance would be appreciated!  
![WithNewIncident](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/99422174/6156b23f-a90e-4cda-ac4a-b1529229bc94)
![No New Incident](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/99422174/dbc613e1-4efb-4f07-8458-54eb60c01436)

**Comment by v-ajaysahu** [comment]
@MetalTark , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network traces which will help us to troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by MetalTark** [comment]
Hi, here is what I'm seeing in the console when loading the app in the Teams web client.  

[teams.microsoft.com-1710257723503.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14575050/teams.microsoft.com-1710257723503.log)

![ConsoleLogImage](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/99422174/cc22dea1-20c0-4b36-8b0d-1b500a2693bb)

**Comment by MetalTark** [comment]
Here's the manifest file.  I'm unable to get the network traces at the moment, please let me know if that is imperative.  
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14575114/manifest.json)

**Comment by MetalTark** [comment]
Also, I updated to 3.0 but I'm still having the same issue being able to create a new incident.

**Comment by v-ajaysahu** [comment]
@MetalTark , Thank you for sharing the details.
If you've enabled Roles, then you need to assign users who can create new incident.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/81e0d957-cd2b-44a7-97d4-492bce927e68)
To Verify whether roles are enabled or not, you can go to TEOC Site and Open TEOC-Config List check value of Enable Roles.

**Comment by kilianb-cosp** [comment]
We enabled mapping and roles, and this posting was very helpful.  Thank you.

**Comment by MetalTark** [comment]
Hi @v-ajaysahu, thanks much for responding.  I verified Roles are enabled (value is set to True) but I don't see a hyperlink to Assign Roles like you do.  Where do I assign roles?  Thank you!

**Comment by v-ajaysahu** [comment]
@MetalTark , 
Once you enable the Roles you need to Click on Save.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/3a4e4e2e-e01c-4537-83da-d1a2b6499e93)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/dea27771-46e0-4b76-bce1-2767046f9bc7)
Once your configuration is saved then only Assign Roles link will appear. 
If you are still facing the issue, then kindly share the Console Logs and Network traces.

**Comment by MetalTark** [comment]
My TEOC List looks and functions much differently than yours.  See screenshot.  Mine is just free text values, not a Y/N field.  
![TEOC-Config List](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/99422174/f7ba2e67-0425-4e1e-b726-42d96d7b3095)

**Comment by MetalTark** [comment]
OK, I think I figured it out.  I found a "TEOCUserRoles" list here and added my email address to this and the Create New Incident button appeared.  Should I do anything to upgrade/fix my lists?  

/Lists/TEOCUserRoles
