### ISSUE TITLE
Permissions and user guides

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#181]
Hi we noticed that unless a person is added into an incident by the owner/creator they can only view the incident, not modify it. Is there a way to allow multiple users the ability to modify incidents? 

Also is there any documentation that can be provided to users on how the application works? Like a user guide?

**Comment by v-ajaysahu** [comment]
@BCG-cmori , Thank you for reporting this.
Incident Commander and Secondary Incident Commander will have owner rights whereas other Roles will be added as member to the team. Incident Commander and Secondary Incident Commander will have rights to modify incidents.
Kindly let us know if you need anything else apart from this.

**Comment by BCG-cmori** [comment]
I was looking for documentation that could be provided to users so they understand how the app works.

**Comment by v-ajaysahu** [comment]
@BCG-cmori , 
We've [Solution Overview](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview) where we have detailed information about the TEOC app. 
Kindly let us know if you need anything else apart from this.
