### ISSUE TITLE
Update to Version 3.0

### ISSUE THREAD

**Issue by devansinleesburgva** [OfficeDev/microsoft-teams-emergency-operations-center#182]
I am currently on version 2.  How do I upgrade to version 3?

**Comment by v-ajaysahu** [comment]
@devansinleesburgva , Thank you for reporting this.
Kindly follow this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version) to upgrade TEOC app to the latest version.
