### ISSUE TITLE
Teams EOC app screen is blank

### ISSUE THREAD

**Issue by dfoelker** [OfficeDev/microsoft-teams-emergency-operations-center#183]
There were no errors when setting up the Teams EOC App but when launching the app, the header information is displayed but the rest of the screen is blank (no login requested).  I get the following errors in the App Service log when I reload the EOC app at the client:

2024-03-26T17:48:56  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 400.0 - Bad Request</title><style type="text/css"></style>
</head><body><div id="content"><div class="content-container"><h3>HTTP Error 400.0 - Bad Request</h3><h4>Bad Request</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li></li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;WindowsAuthentication</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;AuthenticateRequest</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;ExtensionlessUrlHandler-Integrated-4.0</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://TeamsEOCbase:80/sites/gov833023.sharepoint.com:/sites/gov833023.sharepoint.com/sites/DWFEOCSite?$select=id</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\sites\gov833023.sharepoint.com:\sites\gov833023.sharepoint.com\sites\DWFEOCSite</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>The request could not be understood by the server due to malformed syntax.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=400,0,0x00000000,20348">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>

**Comment by v-ajaysahu** [comment]
@dfoelker , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network traces which will help us to troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by v-ajaysahu** [comment]
@dfoelker , thank you for sharing the details.
However, shared content is not Console logs which we are looking for.
Here are the steps to share the console logs and network trace -

1. Open Teams in browser
2. You need to Open Developer tool using F12 key or Ctrl+Shift+i or Go to Browser Menu and More Tools and then Click on Developer Tools and keep it Open
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/47fdd013-6dd5-42da-afc2-e5e0a637b03f)

3. Open TEOC application and try to replicate the issue.
4. Click on Console from developer tool and select everything copy it and share it.
5. Click on Network from developer tool click on down arrow button to export the network logs.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/f12676d5-46c8-4bcb-9c67-e7955c28be44)

6. And share the network logs.

And for Manifest file you should have generated it while creating Team app Package. Please share the Manifest file.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages

**Comment by dfoelker** [comment]
[EOC Logs.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14776445/EOC.Logs.zip)
The requested files are in the attached zip file.  
Thank you.

**Comment by v-ajaysahu** [comment]
@dfoelker , thank you for sharing the logs.
We went through the logs.  Here are things which we found from the logs -

1. You're getting an error while accessing SharePoint site -
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/f65532d6-82d6-4026-850b-0ebd96cc1f51)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/c53e23d4-3e61-4fda-9f6a-ba7915e9e4c3)
2. Kindly verify whether site URL is correct also verify API Permissions for App registrations as per this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#5-add-permissions-to-microsoft-graph-azure-ad-app).

**Comment by dfoelker** [comment]
Hello.
Thank you for your help with this.

The SharePoint URL is:
https://gov833023.sharepoint.com/sites/DWFEOCSite
This is a GCC Tenant.

The permissions appear to be correct:
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/106116570/9e4c1d5f-3fdb-496c-b504-4697dac46b7c)

**Comment by v-ajaysahu** [comment]
@dfoelker ,
Can you please check site permission it should be as per this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#1-provisioning-teoc-site)?

**Comment by dfoelker** [comment]
Hello,

Yes, I did confirm the site permissions.  I believe that I made some mistake when setting up the service or app.  I have deleted everything and am going to try again.  I hope to have time in the next couple of days to do this.

I have to say that setting this up is a cumbersome and time consuming process.  It also appears to be very susceptible to mistakes.  It seems to me that there should be some way to streamline this.


Regards,
Daniel Foelker
Teams Voice Technical Specialist
Modern Work, State & Local Government

Office:  Tel:+14255385442
Mobile: Tel:+16084223225<tel:+16084223225>
***@***.******@***.***>

***@***.***

**Comment by v-ajaysahu** [comment]
@dfoelker ,
We've noted your suggestion.
Kindly let us know once you re-deploy.
