### ISSUE TITLE
Site Provisioned without XML

### ISSUE THREAD

**Issue by asdraper27** [OfficeDev/microsoft-teams-emergency-operations-center#184]
We recently deployed a new instance of TEOC, and after distribution and adding the application to one of our Teams, I see that none of the data / lists were provisioned as part of the EOCSiteTemplate.XML.  There are no lists populated on the Site, so any paths referencing a list return a path not found.  Is is possible to provision the missing data without creating a new instance on a different site?

**Comment by v-ajaysahu** [comment]
@asdraper27 , Thank you for reporting this.
Yes, you can run the provision script if you are not able to find any lists, while running the PS script make sure to provide the full path for xml as shown in the screenshot below and as mentioned in the wiki -
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/f049b419-cca7-44da-a9af-61464b78d492)
Invoke-PnPSiteTemplate is looking for the xml file.
Can you please provide xml file path as mentioned and let us know if it is working for you?

**Comment by asdraper27** [comment]
I provided the path the first time I ran the script, but it is possible that I mistyped something.  Now when I run the script, it states the site exists and exits from the script.


Adam Draper

Lead Infrastructure Technician

Will County ICT Department

(815) 774-7466

***@***.***





________________________________
From: v-ajaysahu ***@***.***>
Sent: Wednesday, March 27, 2024 4:14 AM
To: OfficeDev/microsoft-teams-emergency-operations-center ***@***.***>
Cc: Adam Draper ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-emergency-operations-center] Site Provisioned without XML (Issue #184)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION:This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

________________________________
@asdraper27<https://github.com/asdraper27> , Thank you for reporting this.
Yes, you can run the provision script if you are not able to find any lists, while running the PS script make sure to provide the full path for xml as shown in the screenshot below and as mentioned in the wiki -
image.png (view on web)<https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/f049b419-cca7-44da-a9af-61464b78d492>
Invoke-PnPSiteTemplate is looking for the xml file.
Can you please provide xml file path as mentioned and let us know if it is working for you?

**Comment by v-ajaysahu** [comment]
@asdraper27 ,
Kindly note-down the site URL, delete the site from Admin Center from both Active and Deleted sites. Then, you need to wait for at least 30 minutes and try to re-run the script with the same Site Name.
