### ISSUE TITLE
Logo Customization Teams App

### ISSUE THREAD

**Issue by CEXT0ne** [OfficeDev/microsoft-teams-emergency-operations-center#185]
I followed the logo customization instructions, but this logo does not change in the teams app. How do you change this logo or modify this logo? Or, what is the appropriate method of updating the logo if it needs to be changed? In the example the logo is circled in red.

![1023](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165174952/481ce330-e9ef-41db-8dc3-6ed9565913b3)

**Comment by v-ajaysahu** [comment]
@CEXT0ne , Thank you for reporting this.
The feature you are looking for is not available. Kindly let us know if you need apart from this.
