### ISSUE TITLE
"This channel has been deleted" message when trying to select incident in TEOC main page

### ISSUE THREAD

**Issue by IFIT-BruceG** [OfficeDev/microsoft-teams-emergency-operations-center#186]
While at the main page view of TEOC and selecting the "TEST 3.0-1" incident, I receive the message, "This channel has been deleted" How can I remove this incident from this main page?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/b984e581-2191-4197-8032-8d040350df6a)

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/de688f14-6dfe-4272-930b-99509d6a8c35)

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
Since you've deleted the channel, and you want to remove incident from TEOC app. For this you need to navigate to "**TEOC-IncidentTransaction**" List in TEOC SharePoint site. Search for that item and delete it from the list.

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu It took a little research to find the "TEOC-IncidentTransaction" List in the TEOC SharePoint site location, but once I did, that did the trick.
