### ISSUE TITLE
How do I close an incident?

### ISSUE THREAD

**Issue by IFIT-BruceG** [OfficeDev/microsoft-teams-emergency-operations-center#187]
There is a tab for "Closed", but I can not figure out how to actually close an incident.

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG , Thank you for reporting this.
To Close an incident, you need to edit the incident and change the status to close.
You refer this [link](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#incident-details-dashboard) for reference.

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu Found it under "Incident Status". It is not there when an incident is created, but once it is created, then "Closed" will show up. Got it! Thanks!
