### ISSUE TITLE
Occasional bug in the TEOC Active Dashboard

### ISSUE THREAD

**Issue by IFIT-BruceG** [OfficeDev/microsoft-teams-emergency-operations-center#188]
This has happened to me a few times over the past week, but I am not able to re-create it at will. I will timeline what I was doing the last time it happened, in hopes that it helps to shed light on the incident and what I’ve had to do to correct it each time.
Prelude: I have an active TEOC (test) Incident. When I select the General tab, then select Active Dashboard, I can see Incident Details / Map Viewer tabs and any incident that I have created. In this case, that is only TEST-2.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/608cc6b9-4fec-43fd-87d5-e5d52ebd7f43)
Selecting the Active Dashboard icon for the TEST-2 incident will take me to that incidents Active Dashboard – 2. In this dashboard there is a < Back | Active Dashboard link. Selecting this link will take me back to the original Active Dashboard, with the Incident Details / Map Viewer as shown above.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/b152a88e-2613-417f-aece-c9a38dca2daa)
So, what happens is, sometimes, this < Back | Active Dashboard link disappears. When this happens, there is no easy way back to the Active Dashboard, with the Incident Details / Map Viewer.
The last time this happened, I had left the Active Dashboard – 2 open in its Teams view and navigated to the I.T. Department Team Site and selected the TEOC tab at the top of the page. I was then taken to the greeting screen, but where the information should have been displayed, it was blank.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/3a332e29-68ff-4a98-bc5b-23069434cc93)
When I navigated back to the 2-TEOC-TEST-2… screen, the < Back | Active Dashboard link was now missing and there was no way to get back to it.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/7710ab3a-d207-478a-b7de-628eecad2aa1)
The only way that I’ve found to get back is to log out of TEAMS, then log back in.

**Comment by IFIT-BruceG** [comment]
It took a while to re-create this issue, but I finally manged to do so by right-clicking in the "< Back | Active Dashboard" area of the 2-TEOC-TEST... teams environment and selecting "Refresh". This caused the Teams app to crash/shutdown, and I had to relaunch it.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/160539116/8c77469d-67a3-4464-8084-d47170b24c59)

Upon the relaunch, the described incident happened.
Logging out and back into Teams and going directly to the "2-TEOC-TEST... "teams environment, did not clear the issue this time. I logged out and back into teams Teams a second time and went to the "I.T. Department Team Site/TEOC/TEST-2 (incident)/Active Dashboard, and this appeared to work there. I then switched back to the "2-TEOC-TEST..." teams environment, and it was back to normal.

The requested logs are attached below.

[console-export-2024-4-4_11-30-8.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14875976/console-export-2024-4-4_11-30-8.txt)




[teams.microsoft.com_Archive [24-04-04 11-29-24].har.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14875983/teams.microsoft.com_Archive.24-04-04.11-29-24.har.txt)

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
We're not able to reproduce this defect. Can you share the steps/recordings to reproduce this issue.

**Comment by IFIT-BruceG** [comment]
I'm not sure how to trigger this event other than letting the Active Dashboard sit idle for a while. Overnight will usually do it.
For example, if I am in the actual Incident environment, under Active Dashboard/Active Dashboard, and just leave it there over night. When I check it in the morning, it will usually be messed up.
I've tried many things to force it to fail, but nothing seems to work twice. Perhaps it is just a time time thing. I'll see if tomorrow morning is a fail or not.

**Comment by IFIT-BruceG** [comment]
Letting the program simmer all night worked, it was in the state reported when I got to it this morning. Unfortunately, the screen video capture that worked yesterday when I couldn't get TEOC to crash did not work this morning when it did. ¯\_(ツ)_/¯

The screenshots though would be the same as what I showed at the beginning of this post. No "back" link on the Incident Team page, and just a white screen on the department/TEOC screen.
The files are below, but I had to trim 13 Megs from the beginning of the network logs to get it to the max 25 Megs requirement. Hopefully this helps, as this is making TEOC unusable for us, and that would be a shame.

BTW, I closed the previous incident and created a new one for this, in case it was a glitch in the incident, but the results are the same.

[console-export-2024-4-12_8-7-49.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14960940/console-export-2024-4-12_8-7-49.txt)

[teams.microsoft.com_Archive [24-04-12 08-10-05].har - Copy.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14960953/teams.microsoft.com_Archive.24-04-12.08-10-05.har.-.Copy.txt)

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
I apologize for the inconvenience caused.
Can we connect to resolve this issue? Please share your email address so that we can connect with you to fix it.

**Comment by IFIT-BruceG** [comment]
Sounds good to me.

Email address is below.

Thank you,

Bruce Garoutte
Network Security Engineer
Industrial Finishes and Systems, Inc.

***@***.***
541-206-4393 – cell
industrialfinishes.com<https://industrialfinishes.com/>

***@***.***

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
Can you share email address and your available time from GitHub. If you respond via email then the email address will be hidden, and we won't be able to contact you.
If you want, you can delete it once we connect with you.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/6bb214ec-d4c9-4d4d-8b95-8217c784fded)

**Comment by IFIT-BruceG** [comment]
b.garoutte@industrialfinishes.com
Please do remove my email once you have it
All times are in PST
Monday-May 6 | 9:00 AM - 4:00 PM
Tuesday - May 7 | 12:00 PM - 4:00 PM
Wednesday - May 8 | 11:30 AM - 4:00 PM

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
Thank you for sharing the details.
I've setup a meeting at 9:00 AM - 9:30 AM PST on May 6.

**Comment by v-ajaysahu** [comment]
@IFIT-BruceG ,
Following our discussion, the issue identified in New Teams will be resolved in the upcoming release. In the meantime, please continue to use the TEOC app within Classic Teams.

**Comment by IFIT-BruceG** [comment]
@v-ajaysahu 
Thank you for clearing that up for me. I shall continue to work on our TEOC site and instructions manual now.
