### ISSUE TITLE
Reset Incident number back to 1

### ISSUE THREAD

**Issue by Scarymoon13** [OfficeDev/microsoft-teams-emergency-operations-center#189]
Hello, I made a series of test incidents and now want to reset the incident number back to 1. I did this previously by deleting the List items in TEOC-IncidentTransactions and deleting the teams. When i tried it again today (after creating more over the last week), the incident number was continuing from the last one (ie starting at 6 instead one 1). Did i miss somewhere? I tried searching for this in the closed tickets but could not find a similar question.

**Comment by v-ajaysahu** [comment]
@Scarymoon13 , thank for reporting this.
Since Incident data is stored in SharePoint List, ID cannot be reset to 1 again.

**Comment by Scarymoon13** [comment]
Thank you for the prompt response. I removed that data from the SharePoint List. Essentially, there is no data there. Where else is that data referenced?

**Comment by Scarymoon13** [comment]
Going to close this. The team was fine with it not starting at number 1. Thank you for confirming.
