### ISSUE TITLE
Deployment was successful and App loaded in Teams. But no logon button under Welcome

### ISSUE THREAD

**Issue by matt-mansol** [OfficeDev/microsoft-teams-emergency-operations-center#190]
I think I've missed something or entered something incorrectly in the config. 

The deployment completed successfully:

_Enter site template XML schema file path: C:\Administrative\TEOC\Deployment\provisioning\EOC-SiteTemplate.xml
Enter tenant name: (contoso): mansol
Enter tenant admin email: teoc-admin@mansoldomain.com
Enter site name. Allowed characters for site name are underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period.: TeamsEOCSite_                                          
_PnP.PowerShell module found
Checking if site already exists at /sites/TeamsEOCSite
Site doesn't exist, creating new site at /sites/TeamsEOCSite
https://mansol.sharepoint.com/sites/TeamsEOCSite
Creating lists in TeamsEOCSite site
App Provision complete.__

I can open the App in Teams and it displays the header info and 'Welcome 'username'.' but nothing under that.

I initially had the problem where I overlooked adding the accessTokenAcceptedVersion and updating the value from null to 2 in the application manifest. But I haven't been able to see why this isn't working. I can see that there are "400 (Bad Request)" in the console logs which are attached. But I don't understand where to update that config to correct.

Please help :)
[TEOCConsoleLog.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/14880411/TEOCConsoleLog.txt)

**Comment by v-ajaysahu** [comment]
@matt-mansol , thank you for reporting this issue.
We went through logs which you've shared. App is not able to access SharePoint site. Please check the API permission and Site Permission.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/db8b3272-1040-4924-9ae8-fe3d055b6105)

**Comment by matt-mansol** [comment]
I have checked and confirmed the API permissions appear to be set correctly. 

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165987064/f5ba8ecc-186f-488d-a242-9a5629e8955d)

And I can confirm that the "Everyone except external users" is invited as a Member [Edit] to the site.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165987064/4de4753d-5fb7-4929-95ee-8c0c553c826f)

**Comment by matt-mansol** [comment]
Ok. I deleted the Apps and did it again. This time, I am now presented with a Login button in the Teams App, but when I click it I am presented with the error 


**Sign in**
Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier '938d39e6-f039-40d0-bfe6-656e01d0281b' was not found in the directory 'Managed Solutions'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by matt-mansol** [comment]
Yes I did.

However, I can see that even after removing the app again from Teams Admin Center, that the old App is still listed in MS Teams  webclient. If I try and uninstall from the webclient it has an error message.

_There was an issue while trying to remove TEOC. Please try again_

Presuming this is due to the app no longer being available. I've also added the app back in, and tried to uninstall from the webclient. It results in the same error. 

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165987064/7f820caa-92c0-4a94-adbc-4d966910f598)

**Comment by matt-mansol** [comment]
I have managed to fix the app. Turns out it was a cached 'personal app'. I had to clear my local client v2 cache.
And then I simply had to upload the new version and wait for it to be available to me.

However, I'm back to where I began with the blank TEOC app.  I can open the App in Teams and it displays the header info and 'Welcome 'username'.' but nothing under that.

In reviewing the console log - I'm getting different errors this time. 

[240419-TEOCConsoleLog.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15031237/240419-TEOCConsoleLog.txt)

**Comment by matt-mansol** [comment]
I can appreciate that this isn't a paid service. But honestly, the lack of help is a bit disappointing. 

TEOC is a great idea and I'd love to be able to demonstrate this to my team but if I can't get it working, it might be more feasible to go with a better developed product where there is vendor support.

**Comment by v-ajaysahu** [comment]
@matt-mansol ,
I apologize for the inconvenience caused.
Can we connect to resolve this issue? Please share your email address so that we can connect with you to fix it.

**Comment by v-ajaysahu** [comment]
@matt-mansol ,
Can you share email address and your available time from GitHub. If you respond via email then the email address will be hidden, and we won't be able to contact you.
If you want, you can delete it once we connect with you.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/9629585b-3d7d-4cce-af13-6d2bdb2c4dd8)

**Comment by matt-mansol** [comment]
Apologies v-ajaysahu, I didn’t realise.

My email address is  ***@***.******@***.***>

And I’m next available 07/05/24 from 08:30am AEST (+10) onwards. I’m happy to try and be available at different times if necessary.

Thanks again for your help with this.



Matthew Jenkins
Senior Systems Engineer
P 1300 626 765
e ***@***.***
w www.mansol.net.au
d https://www.mansol.net.au/disclaimer
IT Systems - Microsoft Specialists
Comms | Data | Security | Electrical | Coolers
Internet and Networking
Qld Electrical Contractor Licence No: 75447
With over fifty people committed to providing the best IT and Internet support possible.
Great people, great service, reliable computing.

**Comment by v-ajaysahu** [comment]
@matt-mansol ,
Sharing my email address. Please email me so that we can connect since we are still not able to view your email address.
v-ajaysahu@microsoft.com

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/ed28c3bf-1ce9-4683-a81c-4ecdbe13c609)

**Comment by v-ajaysahu** [comment]
@matt-mansol ,
I have scheduled a meeting for the 8th of May 2024 at 3:30 PM AEST. 
I hope this schedule works for you.

**Comment by matt-mansol** [comment]
That works fine!

Thank you so much. I look forwarding to speaking with you.


Matthew Jenkins
Senior Systems Engineer
P 1300 626 765
e ***@***.***
w www.mansol.net.au
d https://www.mansol.net.au/disclaimer
IT Systems - Microsoft Specialists
Comms | Data | Security | Electrical | Coolers
Internet and Networking
Qld Electrical Contractor Licence No: 75447
With over fifty people committed to providing the best IT and Internet support possible.
Great people, great service, reliable computing.

**Comment by v-ajaysahu** [comment]
@matt-mansol ,
Thank you for attending the meeting. Based on our discussion, please redeploy the application with the correct resource base name. After deployment, confirm if the application is functioning properly.

**Comment by matt-mansol** [comment]
Thank you again for your assistance Ajay! 

As we found yesterday afternoon:

Re-deploying the resource with a correct base name (lower case) fixed the problem.

Uninstalling and re-adding the app in Teams then removed the cache and enabled us to see the working Ops Centre successfully.
