### ISSUE TITLE
Upgraded to Version 3 from scratch but nothing shows up in the Teams EOC App 

### ISSUE THREAD

**Issue by devansinleesburgva** [OfficeDev/microsoft-teams-emergency-operations-center#193]
We did a fresh install of TEOC version 3 and brought on outside help to configure.  We followed the directions very carefully over two days BUT when the end user actually adds the APP to Teams nothing showing up in the TEAMS EOC tab (screen shot attached).  There is info in the "about" screen (see attached).

How can we go about trouble shooting this?
![TEOC 3 About Screen](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/1f39671e-0d5d-487f-87ba-adfe9f22bafb)
![TEOC 3 Main Screen](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/6f4a697b-efcd-466a-9f01-06a3b68eaa2e)

I just made the app available on Wednesday morning and added it to my Teams, but the screen shots are what I see.  I don't know if it takes time to populate?  There wouldn't be any cases or anything in there, but there is now way to add.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva , , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by devansinleesburgva** [comment]
I am attaching console logs/manifest
[TEOC Console Log.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15223878/TEOC.Console.Log.log)
[manifest 2.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15223977/manifest.2.txt)

![Network Tab For TEOC](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/3c808c8c-e7fb-43de-b3fc-eac32c0106ad)

Please let me know if you need anything else-- we really want to get this up and running.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Thank you for providing the logs and the manifest file. 
Please update the 'Valid Domains' in the manifest file and upload it to the Teams Admin portal. For further guidance, please follow the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages).
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/15b5d68a-6444-4149-9c6b-c1c932399cfb)

**Comment by devansinleesburgva** [comment]
Sorry, I sent you the wrong manifest file.  The one we used is attached.

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________

**Comment by devansinleesburgva** [comment]
Correct manifest is attached above.  Can you please take another look and let us know how to proceed.  If you need any other files let me know.  Thank you.

**Comment by devansinleesburgva** [comment]
[Uploading manifest.json…]()

**Comment by devansinleesburgva** [comment]
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15236813/manifest.json)

**Comment by devansinleesburgva** [comment]
Uploaded it to GitHub.

Thank you,

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Thank you for providing the manifest file. 
The "Valid Domains" value is incorrect; it should be the domain name of the App Service where the TEOC application is hosted, as shown in the screenshot below. For further guidance, please follow the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages).
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/be9fdea6-109f-4f50-9a57-ee8cef7c5f52)

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
The "Valid Domains" value should be "toleoc.azurewebsites.net," but it has been entered as "teoc.azurewebsites.net." Please correct this in your manifest file and check if it resolves the issue. 
To obtain the domain name, refer to the App Service URL entered in your manifest file, as indicated in the screenshot provided. Alternatively, you can go to the Azure Resource group, select the App Service, and find the domain name in the overview section.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/e6edd141-8cab-4cba-8ef0-33572bade464)

**Comment by devansinleesburgva** [comment]
When we correct the manifest can we just use the Teams Admin Center to upload a new version (see attachment) using the corrected manifest and the resources folder?
![Upload New TEOC Version](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/b7ffa736-d518-4e90-859e-48214e0b1c9b)

**Comment by devansinleesburgva** [comment]
Unfortunately the same issue remains.
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15250687/manifest.json)

What other steps can we take?

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Have you removed the app from the Teams Admin Portal? If not, please do so and attempt again. 
If the issue persists, kindly share your email address and availability in GitHub, and I will arrange a meeting to address this matter.

**Comment by devansinleesburgva** [comment]
So are you saying to delete the exiting app for Teams Admin Portal and then re-add it by uploading the corrected manifest and resource folder?

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Correct, remove the application and then upload the zip file containing the proper manifest and resource folder.

**Comment by devansinleesburgva** [comment]
I will try that now and get back with you.  Thank you.

**Comment by devansinleesburgva** [comment]
Just deleted it.  I'm going to let it set for 24 hours and then re-add it with the updated manifest/resource.  I'll be back in touch.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Please inform us of the outcome after you have redeployed the TEOC App.

**Comment by devansinleesburgva** [comment]
I added the new app this morning and made it available to install, but it isn't showing up yet as an option in Teams.  I will try to add again this afternoon and will definitely reach out with the outcome.

Thank you,

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________

**Comment by devansinleesburgva** [comment]
I added the App back with the updated Manifest, but unfortunately it is the same result.  I have attached a shot of the app when it opens.  Just a Welcome screen with "Welcome David" but nothing below it.
![TEOC Screen Shot on May 9](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/a804ce40-9788-4ce3-b6b8-cde21aa15a87)

We really do want to get this up and running so let us know what other steps we can take.

**Comment by devansinleesburgva** [comment]
By the way - we are running "new" Teams.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
This usually occurs when the base resource name contains capital letters. Can you confirm this?
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/da53a0dd-2d7c-4587-939b-8e28c72a83d6)

**Comment by devansinleesburgva** [comment]
Where can I find the base resource name after deployment?

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Here are the steps to locate the base resource name after deployment:

1. Navigate to the resource group.
2. Click on 'Deployments' from the settings menu in the left pane.
3. Select the link that begins with 'Microsoft.Template'.
4. Click on 'Inputs' in the left pane.
5. Here, you will find the base resource name you have entered.

**Comment by devansinleesburgva** [comment]
The base resource name is:  toleoc (no capital letters).

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Please share your email address and available time. So that we can connect with you and resolve this.

**Comment by devansinleesburgva** [comment]
My email is:  devans@leesburgva.gov

I am available now thru 1PM Eastern time or almost all day on Monday if those times work for you.  Thank you.

**Comment by devansinleesburgva** [comment]
Send me a meeting request and we can hook up - maybe do a screen share?

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
I have scheduled a meeting with you. We can join it there.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva ,
Since the TEOC application is operational, I am closing this request.
