### ISSUE TITLE
TEOC - Randomly Broken?  Login button suddenly appeared, and no users or admins can login

### ISSUE THREAD

**Issue by thricestrat** [OfficeDev/microsoft-teams-emergency-operations-center#194]
No changes made, app registration and apis exposed look fine.  Issue not present in mobile teams client.  How do i fix this?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/44477569/b24de82d-c574-437d-966b-a742f2570ac8)

**Comment by v-ajaysahu** [comment]
@thricestrat ,  Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by thricestrat** [comment]
Issue stopped after 2 days of TEOC being down, we attributed it to service health alert but could be wrong, thanksSent from my iPhoneOn May 2, 2024, at 3:32 AM, v-ajaysahu ***@***.***> wrote:﻿
@thricestrat ,  Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by v-ajaysahu** [comment]
@thricestrat ,
Since the issue has been resolved, we're closing this request.
