### ISSUE TITLE
Can't Upgrade to v3

### ISSUE THREAD

**Issue by thatguy9129** [OfficeDev/microsoft-teams-emergency-operations-center#195]
I am trying to upgrade from v0.5.1 to v3.0. I am following the guide published here: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version

I get to Step 5 and go to sync the latest version and I get the attached error. 
![2024-04-29_151810](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/41638796/bdb850ff-0118-440d-b385-25068676946a)

Please assist?

**Comment by v-ajaysahu** [comment]
@thatguy9129 , Thank you for reporting this.
Can you try again by Redeploy Commit button and confirm.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/9e2f0b5c-a0de-49b8-a107-40e44ea48482)

**Comment by thatguy9129** [comment]
This got lost in my email. I tried the redeploy but that didn't work.
