### ISSUE TITLE
Fresh Install of TEOC 3 Failed

### ISSUE THREAD

**Issue by devansinleesburgva** [OfficeDev/microsoft-teams-emergency-operations-center#196]
After installing Version 3 from Scratch when I open the Teams App on the landing screen I get a screen labeled Microsoft Teams Emergency Operations Center and a Welcome David and then a blank white screen.  Please see attachment and advise on how to correct.
![TEOC Landing Page](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/136514657/49a1369c-f8e5-43f8-a698-aba741c8fb30)

**Comment by v-ajaysahu** [comment]
@devansinleesburgva , Thank you for reporting this.
Please open teams in browser, then open the app and share console logs and network trace which will help us troubleshoot the issue.
Also request you to share the manifest files with us.

**Comment by v-ajaysahu** [comment]
@devansinleesburgva , 
Closing this issue since this issue is already reported. Please provide your input to below issue.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/193

**Comment by devansinleesburgva** [comment]
I am attaching our manifest files/console logs/network trace.

Please reach out after you have had a chance to review these.

Thank you,

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________

**Comment by devansinleesburgva** [comment]
[manifest.json](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15203764/manifest.json)
[TEOC Console Log.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/15203767/TEOC.Console.Log.log)

**Comment by devansinleesburgva** [comment]
I had two cases opened on this, please see the one sent on on Friday, 5/3 to case 196.  I believe I added the same files to 193 in Teams.

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________

**Comment by devansinleesburgva** [comment]
David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)

________________________________
From: David Evans ***@***.***>
Sent: Friday, May 3, 2024 2:20 PM
To: OfficeDev/microsoft-teams-emergency-operations-center ***@***.***>; OfficeDev/microsoft-teams-emergency-operations-center ***@***.***>ply.git

Cc: Mention ***@***.***>; ***@***.*** ***@***.***>Subject: Re: [OfficeDev/microsoft-teams-emergency-operations-center] Fresh Install of TEOC 3 Failed (Issue #196)

I am attaching our manifest files/console logs/network trace.

Please reach out after you have had a chance to review these.

Thank you,

David A. Evans
Senior Systems Administrator
Town of Leesburg
703-737-7153 (desk)
571-440-1108 (cell)
________________________________
