### ISSUE TITLE
Azure 

### ISSUE THREAD

**Issue by sstrong56** [OfficeDev/microsoft-teams-emergency-operations-center#198]
Hi There is there a way not to have to use Azure with this, I run a county EMO ECC and would like to use this in teams. We have 365 and SharePoint, OneDrive and our own file server. My County does not have Azure.
Thanks for any response the project looks great.
Shane

**Comment by v-ajaysahu** [comment]
@sstrong56 ,  Thank you for reporting this.
This entire project built using Azure service and MS Graph API, so you need to use Azure in order to use the APP.
