### ISSUE TITLE
App is not loading - Showing blank interface

### ISSUE THREAD

**Issue by tofighi** [OfficeDev/microsoft-teams-emergency-operations-center#199]
I followed all steps and got to when I tried to add it on Tabs (both desktop and online versions), I had the following issue. The following is for Web version. I was wondering if this issue is related to azurewebsites.net or my setup. Could you please help?

![Blank page](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/804298/f4934b5d-7e39-43c3-961b-43b6eb8074af)

**Comment by v-ajaysahu** [comment]
@tofighi , Thank you for reporting this.
Please verify that the Azure App Service URL is accurate. If confirmed, kindly open Teams in a browser, launch the app, and share the console logs and network trace to assist in troubleshooting the issue. Additionally, please provide us with the manifest files.

**Comment by tofighi** [comment]
I found out the problem was about using "resource group" name instead of "app service" name in URL. Now I fixed it in all places and I could use it in both Teams and Web interface.
However, now other problems occurring such as not creating an ID for each incident, or it 

<img width="722" alt="problem" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/804298/ae467099-6640-4c1a-b8e7-3840b112fa09">


However, after a few hours, it seems it is working correctly. It just makes me nervous that can I trust the product as I do not know how to find issues and solve them. Could you please let me know how to access logs of the program?

**Comment by v-ajaysahu** [comment]
@tofighi ,
Indeed, you can update "NaN" values via SharePoint, which is identical to the item ID. To access the logs, you can view them from Log Analytics, or you can also view them through the browser's developer tools console window.

**Comment by tofighi** [comment]
Thank you!
