### ISSUE TITLE
Test Inc

### ISSUE THREAD

**Issue by kiranraghavendra1988** [OfficeDev/microsoft-teams-emergency-operations-center#20]
INC Summary - XYZ down
Business impact - To be confirmed.

**Comment by v-saikirang** [comment]
HI @kiranraghavendra1988,

Thanks for your feedback. Can you please elaborate on the issue you are facing with TEOC app so we can help you accordingly.
Thanks.

**Comment by v-saikirang** [comment]
Hi @kiranraghavendra1988,

We are closing this ticket since we did not get get any response. Please create a new ticket for any issues.

Thanks.
