### ISSUE TITLE
Issue with Unidentified NaN Entry in Incident Management Dashboard

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#201]
We've encountered an anomaly in our Incident Management Dashboard within the Teams Emergency Operations Center where one of the incident entries is showing as "NaN" (Not a Number) under the 'Incident Id' column. This issue appears isolated as we were able to create another incident entry successfully post this occurrence. However, the presence of the "NaN" entry raises concerns about potential underlying issues in our incident management process or data integrity.

We seek clarification on whether there's any specific cause behind this anomaly. Additionally, we request assistance in completely removing this "NaN" incident from our system. As part of our cleanup process, we also wish to know the best practices for deleting previous test incidents that are no longer required. This includes the cleanup of associated resources such as team chats, Office 365 groups, and other assets created with these incidents.

Could you please provide guidance on how to effectively manage and delete these incidents while ensuring compliance with data retention policies and system integrity? We aim to maintain a clean and accurate incident management environment. Thank you.

![TEOC](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/130778120/4bb161b6-237d-4991-86b0-68d96ecfb7f2)

**Comment by v-ajaysahu** [comment]
@BCG-cmori , Thank you for reporting this.
There might be some issue while updating Incident Id "NaN".  To reproduce this, we will need console logs or network trace so that we can provide solution.
To clean-up you need to remove the Teams site from SharePoint admin center and then navigate to TEOC site and open "TEOC-IncidentTransaction" List, delete the list item.
In this way you can clean-up the Incidents which you don't want to keep it.

**Comment by BCG-cmori** [comment]
Thanks for getting back to me so quickly! This is the first time we've seen the "NaN" issue pop up, and it doesn't seem to be a regular thing. We're going to go ahead and remove that entry as you suggested. If it comes up again, I'll definitely reach out for more help.

Also, I was wondering if there's a simpler way to give everyone on the team access to incidents? We're trying to avoid having to add each person one by one for every incident, which would really help us save time and boost our efficiency. Any tips or extra advice on this would be super helpful. Thanks!

**Comment by v-ajaysahu** [comment]
@BCG-cmori ,
Currently, adding 'Everyone' is not an option; however, you can add multiple users to a specific role. To save time, you can set them as default users for that selected role.
