### ISSUE TITLE
TEOC Provisioning error

### ISSUE THREAD

**Issue by Electric-Velcro** [OfficeDev/microsoft-teams-emergency-operations-center#204]
Getting this error when attempting initial setup:

PnP.PowerShell module found
Checking if site already exists at /sites/TEOC_SITE_2
Site doesn't exist, creating new site at /sites/TEOC_SITE_2
https://xxxxxxxxx.sharepoint.com/sites/TEOC_SITE_2
Creating lists in TEOC_SITE_2 site

Error Message:  File not found

App Provisioning failed.

**Comment by v-dimplek** [comment]
@Electric-Velcro Thank you for reporting this.
Please confirm the path of the EOC-SiteTemplate.xml file. Make sure you have entered the fully qualified path of the XML file (e.g., C:/Scripts/EOC-SiteTemplate.xml). Additionally, here is the deployment guide link for your reference.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#1-provisioning-teoc-site
