### ISSUE TITLE
need help with Azure deploy step

### ISSUE THREAD

**Issue by srikanthchel** [OfficeDev/microsoft-teams-emergency-operations-center#205]
I am facing issue in step 3 "Deploy to your Azure subscription" and receiving below authentication error.  I have tried verifying with My IT team and they are saying I am not allowed to deploy any resources directly and it should be deployed by using ARM template. Can you please help me with resolution to proceed with this step.  please find the attached screenshots for reference. 
<img width="908" alt="image (1)" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171292427/d24ca260-96fb-47be-9a05-3c1fc110b813">
<img width="588" alt="image (2)" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171292427/3c6f746e-57be-4eb0-be33-495a65eee265">

Raw error: {

  "code": "InvalidTemplateDeployment",
  "message": "Deployment failed with multiple errors: 'Authorization failed for template resource 'agcompanyteoc' of type 'Microsoft.Web/serverfarms'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.Web/serverfarms/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.Web/serverfarms/agcompanyteoc'.:Authorization failed for template resource 'agcompanyteoc' of type 'Microsoft.Web/sites'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.Web/sites/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.Web/sites/agcompanyteoc'.:Authorization failed for template resource 'agcompanyteoc/web' of type 'Microsoft.Web/sites/sourcecontrols'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.Web/sites/sourcecontrols/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.Web/sites/agcompanyteoc/sourcecontrols/web'.:Authorization failed for template resource 'agcompanyteoc-log-analytics' of type 'Microsoft.OperationalInsights/workspaces'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.OperationalInsights/workspaces/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.OperationalInsights/workspaces/agcompanyteoc-log-analytics'.:Authorization failed for template resource 'agcompanyteoc' of type 'Microsoft.ManagedIdentity/userAssignedIdentities'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.ManagedIdentity/userAssignedIdentities/agcompanyteoc'.:Authorization failed for template resource 'agcompanyteocsimpleAuth/appsettings' of type 'Microsoft.Web/sites/config'. The client 'srikanth.chelumuri@corteva.com' with object id 'd7449c30-0e78-491a-b541-ccb208ae8e4f' does not have permission to perform action 'Microsoft.Web/sites/config/write' at scope '/subscriptions/eff9ccf8-5eae-42aa-bf3a-49c75b802074/resourceGroups/IT-TEOC-PROD/providers/Microsoft.Web/sites/agcompanyteocsimpleAuth/config/appsettings'.'"
}

**Comment by v-ajaysahu** [comment]
@srikanthchel , Thank you for reporting this.
Based on the raw error shared, it appears that you lack the necessary permissions to create resources under the selected Subscription. Please verify your permissions.

**Comment by srikanthchel** [comment]
Thank you Ajay, can I know what are the permissions are needed in Azure subscription to deploy this resource. Can we have a quick 30 min call, I can ask my cloud engineer to join call with us. I will schedule a call depending on your availability.

**Comment by v-ajaysahu** [comment]
@srikanthchel ,
Certainly, kindly provide your email id and your availability, and we will arrange the schedule accordingly.

**Comment by srikanthchel** [comment]
Thanks Ajay, My email address is ***@***.******@***.***>. I am available on Monday 10th June at 9 AM CST to 10 AM CST.

Thanks & Regards,
Srikanth Chelumuri
From: v-ajaysahu ***@***.***>
Sent: Thursday, June 6, 2024 7:58 AM
To: OfficeDev/microsoft-teams-emergency-operations-center ***@***.***>
Cc: Chelumuri, Srikanth ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-emergency-operations-center] need help with Azure deploy step (Issue #205)

@srikanthchel , Certainly, kindly provide your email id and your availability, and we will arrange the schedule accordingly. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message


@srikanthchel<https://urldefense.com/v3/__https:/github.com/srikanthchel__;!!Eq8rgdkfa9r_yJvCTg!ywxxD6HlsdTd2jz_VoiR3HWEWquKmdPvz2e-wawP6IUNaZzTCfI0C5pRNY9cZToAvn8UsVTH-4xgsd3n_9LAFYKNRLGIBHet$> ,
Certainly, kindly provide your email id and your availability, and we will arrange the schedule accordingly.

**Comment by v-ajaysahu** [comment]
@srikanthchel ,
Please share your email address using GitHub, if you are sharing from email, we won't be able to view it.

**Comment by v-ajaysahu** [comment]
@srikanthchel ,
A meeting has been scheduled to address and troubleshoot the issues you are experiencing.

**Comment by v-ajaysahu** [comment]
@srikanthchel ,
Following our meeting discussion, the issue you're encountering stems from your Organization Policy on the Azure Portal, which restricts resource creation only from Pipeline. This restriction will cause a deviation from our standard deployment procedures, and as such, we will be unable to provide support. 
It's important to be aware that customizing the solution to fit your organizational needs may lead to complications when upgrading to newer versions in future releases.
I'm closing this issue, however please let us know if you need more information.
