### ISSUE TITLE
TEOC Stuck at Login Prompt in MS Teams

### ISSUE THREAD

**Issue by Chinmay25-Syn** [OfficeDev/microsoft-teams-emergency-operations-center#208]
We have followed all the required steps and deployed the TEOC app.

The app is now stuck at login prompt 

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171906614/ad558bbd-307e-4bdc-a606-61d5887b8faa)
![TEOC_LoginPrompt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171906614/6516da78-7e76-4323-801b-8e1e2b9f4b3c)

**Comment by v-ajaysahu** [comment]
@Chinmay25-Syn , Thank you for reporting this.
Please launch Teams in your browser, then access the developer tools and open the TEOC app. Share the console logs and network traces to assist in troubleshooting the issue. 
Additionally, please provide us with the manifest files.

**Comment by Chinmay25-Syn** [comment]
> @Chinmay25-Syn , Thank you for reporting this. Please launch Teams in your browser, then access the developer tools and open the TEOC app. Share the console logs and network traces to assist in troubleshooting the issue. Additionally, please provide us with the manifest files.

@v-ajaysahu I have attached the logs and manifest files as requested

[TEOC_Logs.zip](https://github.com/user-attachments/files/15760088/TEOC_Logs.zip)
[manifest.json](https://github.com/user-attachments/files/15760091/manifest.json)

**Comment by v-ajaysahu** [comment]
@Chinmay25-Syn ,
Thank you for providing the logs. 
After reviewing them, it appears that the issue may stem from the Client ID and Tenant ID you have supplied. Could you please verify if the Client ID and Tenant ID are accurate? If they are, kindly confirm the Client Secret as well.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/0ee6d59a-d6e3-41f8-b21b-ec0523427422)

**Comment by Chinmay25-Syn** [comment]
@v-ajaysahu 

Thanks for the valuable inputs

We have updated the correct api under Expose API in azure as there was some minor error, we are able to login but unfortunately we cant see the Search / Manage / Create new Incident options , could you please help as this happening both in client and also in web teams
![Capture](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171906614/2902c965-fd19-48ad-88ef-77be27693941)

**Comment by v-ajaysahu** [comment]
@Chinmay25-Syn ,
Please confirm that the Client Secret is correct and verify that the base resource name has been entered accurately according to our [deployment guidelines](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide). 
If it is correct, please share you email address and your available time so that we can connect and troubleshoot this issue.


![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/b45d66c3-368c-4192-8d4e-9c8ca5d15625)

**Comment by Chinmay25-Syn** [comment]
@v-ajaysahu Yes the base resource name is correct and deployment was successfull

My email address is Chinmay.joshi@syngenta.com

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171906614/5de592f3-8a97-4460-9eb4-15328723cf1c)

**Comment by Chinmay25-Syn** [comment]
@v-ajaysahu  Yes the base resource name is correct and deployment was successfull

My email address is Chinmay.joshi@syngenta.com

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/171906614/7dcf156f-4ca6-480a-bc53-9598fe499934)

**Comment by v-ajaysahu** [comment]
@Chinmay25-Syn ,
Kindly provide your available time so that we can schedule an MS Teams meeting to troubleshoot this issue.

**Comment by Chinmay25-Syn** [comment]
@v-ajaysahu We can connect now if you are available

**Comment by v-ajaysahu** [comment]
@Chinmay25-Syn ,
As per our discussion, it appears that Site Name has been entered incorrectly. Please remove the resource group and try again.
