### ISSUE TITLE
TEOC v3.1 Incident black screen - Active Dashboard blank screen - Admin setting not working

### ISSUE THREAD

**Issue by CEXT0ne** [OfficeDev/microsoft-teams-emergency-operations-center#209]
I was informed by one of my users that the TEOC active dashboard has been displaying a blank screen and was previously working. I updated our Prod and Dev environment to version 3.1 and it did not correct the issues with the active dashboard. Active dashboard still works in our dev environment.

After the update our dev environment in the web client has intermittent issues with a blank screen when attempting to create and incident. In our prod environment in the web client, it only loads to a blank screen when trying to create an incident. I would like to note the active dashboard was functioning and stopped working. After updating we started experiencing more problems in the web client. Active dashboard also does not work in Prod using the desktop client.

If log files are needed is there a way to securely transfer the files instead of leaving the files open to the public?

**Is this problem related to:**
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/188

**Browser:** Microsoft Edge
**TEOC:** 3.1

**Example 1: Create Incident**
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165174952/3b4b9498-69b9-4b1c-b35c-9fdf89eadcaf)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165174952/fca2c7ff-13bf-4f7f-909e-8f8387e5c317)

**Example 2: Active Dashboard/Admin Settings**
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165174952/1e52bf06-f86a-48ca-8d70-fc54edaed3f2)

**Comment by v-ajaysahu** [comment]
@CEXT0ne , thank you for reporting this issue.
Yes, we will require the console and network logs; please also include the Manifest file. As we do not have a private link for you to share the logs, you may post them here. Once we acknowledge receipt, you may then remove them.

**Comment by CEXT0ne** [comment]
[TEOC.zip](https://github.com/user-attachments/files/15826670/TEOC.zip) Manifest app Package

**Comment by CEXT0ne** [comment]
[AdminSettings.log](https://github.com/user-attachments/files/15826810/AdminSettings.log)
[CreateIncident.log](https://github.com/user-attachments/files/15826811/CreateIncident.log)
[ActiveDashboardLog.log](https://github.com/user-attachments/files/15826812/ActiveDashboardLog.log)

LOGS

**Comment by CEXT0ne** [comment]
Have you received the files so I can delete them?

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
Yes, you can delete the files.

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
Thank you for providing the logs. After reviewing the logs you shared, could you please confirm if the deployment was successful and also verify which theme is currently in use?

**Comment by CEXT0ne** [comment]
The deployment was successful from what I remember. Can you guide me to where I can review the template?

**Comment by CEXT0ne** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/165174952/88bada06-48b1-47d7-b2b4-8f144564556d)

**Comment by CEXT0ne** [comment]
@v-ajaysahu Are you able to give me more information on what you mean by theme?

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
From the screenshot provided, it appears that you are using a High Contrast Theme on your Windows system. Could you please specify which theme is currently applied to your system? 
Also, share your email address and available time so that we can schedule an MS Teams meeting to troubleshoot this issue.

**Comment by CEXT0ne** [comment]
I tried all themes inside of teams and it still does not work. The high contrast screenshot was from Azure not teams. After providing my email I will need you to delete it immediately from the post or confirm you have received it so I can delete it.

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
Once I have acknowledged it, you may delete it.

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
I have got your email address; you may delete the post. Could you please share your available time so that we can schedule a MS Teams Meeting.

**Comment by CEXT0ne** [comment]
2-3pm EST 20240618

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
We operate in the IST time zone, so 2 - 3 PM EST would be too late for us. Can I schedule it for 10-11 AM EST instead?

**Comment by CEXT0ne** [comment]
I will not be available at that time. I already have meeting scheduled.

**Comment by CEXT0ne** [comment]
11am-12pm EST 20240620

**Comment by v-ajaysahu** [comment]
@CEXT0ne ,
Following our conversation, we have also conducted an internal verification. The issue with the Active dashboard not functioning arises from using both DEV and Prod TEOC within the same tenant, coupled with the update to the production's external App Id. This is due to the code utilizing the external App Id, which presents a limitation. 
To resolve this, you must either revert the production TEOC app's external App Id to the previously added Id or customize the app accordingly. Please note, we do not provide support for customization.
