### ISSUE TITLE
Blank screen (no login button)

### ISSUE THREAD

**Issue by sulenmn** [OfficeDev/microsoft-teams-emergency-operations-center#21]
Hi, 

One of our SharePoint site members, can't access to TEOC. Member gets blank screen only. Please advise.
Other users have no issue accessing to TEOC so far. (but incident submission error)
 
![image](https://user-images.githubusercontent.com/105066366/167165626-a5e083fb-5d6c-4c54-ad4e-6d011474c250.png)

Thank you

**Comment by v-saikirang** [comment]
Hi @sulenmn,
Thanks for your feedback.
Can you please ask the user to open the app in an incognito browser and share the console logs so we can try to identify the issue.
Can you also confirm if the user is added to the Members group in SharePoint.
Thanks.
Thanks.

**Comment by v-saikirang** [comment]
Hi @sulenmn,

Can you please confirm if you have followed the steps to upgrade mentioned in the attached document. If yes, can you confirm if you have seen the success message under Logs. If not done already please complete the steps and retry.
If you still see the issue can you open the app in browser and share the console logs.
[TEOC-Upgrade-Steps.docx](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/8675065/TEOC-Upgrade-Steps.docx)

And can you also respond to my earlier message about user access issue.
Thanks.

**Comment by sulenmn** [comment]
![image](https://user-images.githubusercontent.com/105066366/168373845-b9f28edb-6519-4166-b236-b289838284d0.png)

It is success. But still shows error when create an incident. Please advise.

**Comment by Porkai-Pandian** [comment]
Hi @sulenmn, can you please share the screenshot of the error or console log error you're getting while creating incident.

**Comment by sulenmn** [comment]
![image](https://user-images.githubusercontent.com/105066366/168389942-ef992574-ff6a-4b5b-9f76-2011a7d5ae3f.png)

**Comment by Porkai-Pandian** [comment]
Seems you've not selected date and time, pls select it and try again, if you still get error, kindly share the error message from the browser console

![image](https://user-images.githubusercontent.com/87537966/168391020-c2579eed-23e8-4fdb-9bad-984216d2ce59.png)

**Comment by sulenmn** [comment]
Hi @Porkai-Pandian and @v-saikirang , 

Thank you, 
We locked down the team or group creation to only admins.
It says "CreateTeamGroup". Does creating a new incident create a new Team every time?

![image](https://user-images.githubusercontent.com/105066366/169571016-142dcd32-536e-4554-b631-b92d03a53dee.png)

Please advise.

Thank you again,

**Comment by sulenmn** [comment]
hi @v-saikirang @Porkai-Pandian 

I still get this error. Please advise.
![image](https://user-images.githubusercontent.com/105066366/170075299-5c410c0c-20aa-4d45-95c5-4b13dd3ca566.png)

Thank your for your help

**Comment by v-saikirang** [comment]
Hi @sulenmn,
Please allow us some time. We will get back to you on this ASAP.
Thanks.

**Comment by sulenmn** [comment]
@v-saikirang 
Thank you. Actually we figured it out internally and able to create incidents now.
But other members still getting blank screen.
![image](https://user-images.githubusercontent.com/105066366/170347271-9581de1d-e2e5-4d17-9be6-f8cc239b71fd.png)

**Comment by v-saikirang** [comment]
Hi @sulenmn,
Thanks for your patience.
May I know if this is happening for all the other users or only few users. Can you please share the console logs from the user who is having this issue. And can you also please confirm if the user saw "Login" button first time they accessed the app.

Thanks.

**Comment by v-saikirang** [comment]
Hi @sulenmn,

We are planning to close the issue in next 3 days due to inactivity. Please let us know if you are still seeing any issues.

Thanks.

**Comment by sulenmn** [comment]
Hi @v-saikirang 

Other users than me getting blank screen. 
![image](https://user-images.githubusercontent.com/105066366/172963813-03aa22d6-0800-470e-ba19-a9698b0576d4.png)

**Comment by v-ashrirao** [comment]
@sulenmn, Thanks for sharing error details with us.
We will need few more details to understand this issue. Can you please check and confirm,
1. If user is able to access root site? e.g. **https://{Your Tenant Name}.sharepoint.com**
2. If users getting blank screen have access to TEOCSite? e.g. **https://{Your Tenant Name}.sharepoint.com/sites/TEOCSite**

**Comment by sulenmn** [comment]
hi @v-ashrirao 

1. Yes, they can access to the root site. They are site collection admins
2. No blank screen to TEOCSite. They can access to TEOCsite without any issues.

Thank you

**Comment by Porkai-Pandian** [comment]
No response from the user for the email sent, marking this item as closed, please create new issue if in case issue still occurs.
