### ISSUE TITLE
Azure Deployment Failure

### ISSUE THREAD

**Issue by humbergp** [OfficeDev/microsoft-teams-emergency-operations-center#211]
Command: deploy.cmd
Restoring npm packages for EOC-TeamsFx (this can take several minutes)
"C:\home\site\repository"
Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/abort-controller@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-auth@1.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-client@1.9.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-http-compat@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-lro@2.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-paging@1.6.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-rest-pipeline@1.16.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-tracing@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-util@1.9.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/keyvault-keys@4.8.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/logger@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@10.2.2',
npm WARN EBADENGINE   required: { node: '14 || >=16.14' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }

up to date in 6s

276 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> teamsfx-template-tab@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

TS7016: Could not find a declaration file for module '@microsoft/applicationinsights-web'. 'C:/home/site/repository/EOC-TeamsFx/tabs/node_modules/@microsoft/applicationinsights-web/dist/applicationinsights-web.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/microsoft__applicationinsights-web` if it exists or add a new declaration (.d.ts) file containing `declare module '@microsoft/applicationinsights-web';`
  [0m [90m 4 |[39m [36mimport[39m { [33mMessageBar[39m } [36mfrom[39m [32m'@fluentui/react/lib/MessageBar'[39m[33m;[39m
   [90m 5 |[39m [36mimport[39m { [33mTooltipHost[39m } [36mfrom[39m [32m'@fluentui/react/lib/Tooltip'[39m[33m;[39m
  [31m[1m>[22m[39m[90m 6 |[39m [36mimport[39m { [33mApplicationInsights[39m } [36mfrom[39m [32m'@microsoft/applicationinsights-web'[39m[33m;[39m
   [90m   |[39m                                     [31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m
   [90m 7 |[39m [36mimport[39m { [33mClient[39m } [36mfrom[39m [32m"@microsoft/microsoft-graph-client"[39m[33m;[39m
   [90m 8 |[39m [36mimport[39m [33mReact[39m [36mfrom[39m [32m'react'[39m[33m;[39m
   [90m 9 |[39m [36mimport[39m [33mCol[39m [36mfrom[39m [32m'react-bootstrap/esm/Col'[39m[33m;[39m[0m

Failed exitCode=1, command=npm run-script build
An error has occurred during web site deployment.
npm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/abort-controller@2.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-auth@1.7.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-client@1.9.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-http-compat@2.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-lro@2.7.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-paging@1.6.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-rest-pipeline@1.16.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-tracing@1.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-util@1.9.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/keyvault-keys@4.8.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/logger@1.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: 'lru-cache@10.2.2',\r\nnpm WARN EBADENGINE   required: { node: '14 || >=16.14' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by v-ajaysahu** [comment]
@humbergp , thank you for bringing this issue to our attention.
Please delete the resource group and attempt the process once more.

**Comment by humbergp** [comment]
I deleted the related resources within the resource group and the process redeployed successfully.  Thank you!

**Comment by v-ajaysahu** [comment]
@humbergp ,
Thank you for the confirmation. As your issue has been resolved, I am closing this issue. Should you have any further concerns, please feel free to add your comments here.
