### ISSUE TITLE
App crashes once a role is selected

### ISSUE THREAD

**Issue by mnferoz** [OfficeDev/microsoft-teams-emergency-operations-center#212]
Hello, We have been able to provision this App within our environment at our organization. However, when we click on the Select Role dropdown while creating a new Incident the App crashes and we end up going to a blank screen. FYI, the dropdown looks as follows:

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/16942994/89e8750f-72e6-4881-aac5-98b4dbd65d1a)

Regarding the Deployment Guide and its steps, we were able to perform every step as mentioned in the document with the exception of step https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/pull/1. When running the provisioning script, the SharePoint Site would create but the script would return stating App Provisioning failed. However, once we go to the newly created SharePoint site and add the one running the Script to the Site Collection Administrators, the script then runs okay. The needed SharePoint Lists still didn't exist, and we had to manually look at the XML file and create the needed SharePoint Lists for the Teams EOC App to launch as expected.
 
Can you please assist with any suggestions relating to how we can fix and resolve this issue related to the Select Role dropdown? Thanks!

**Comment by v-ajaysahu** [comment]
@mnferoz , thank you for bringing this issue to our attention.
Please inform us of the specific issue encountered during the site provisioning. Was the script executed with Tenant Admin rights? 
Additionally, to address the issue with the Role dropdown selection, open Teams in your browser, activate the developer tools, then initiate the app and provide the console logs and network trace to help in our troubleshooting efforts.
