### ISSUE TITLE
Issues publishing the app

### ISSUE THREAD

**Issue by JayPdsn** [OfficeDev/microsoft-teams-emergency-operations-center#213]
After following the deployment guide we are receiving this when launching the app

"Sorry, but we're having trouble signing you in. 

AADSTS700016: Application with identifier 'bffbc2b1-676e-47ac-9bdc-f71a81b2a08c' was not found in the directory 'Tenant Name Here'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

Request Id: 0c2269be-5cfe-4a47-aa2a-054638c93200
Correlation Id: 2ac2df87-2d86-44fe-8c67-4083cf66d4f7
Timestamp: 2024-06-25T20:21:45Z
Message: AADSTS700016: Application with identifier 'bffbc2b1-676e-47ac-9bdc-f71a81b2a08c' was not found in the directory 'Tenant Name Here'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

This was installed by an administrator of the tenant. Any idea on how to check if the authentication request was sent to the wrong tenant?

**Comment by v-ajaysahu** [comment]
@JayPdsn , thank you for reporting this issue.
To confirm whether the tenant or Client ID is correct, you or the tenant admin should check within the Azure Resource group. Navigate to 'Deployments' from the settings in the left pane, select "Microsoft.Template," and then choose 'Inputs' from the left pane to view the input parameters passed. If the Tenant or Client ID is accurate, proceed to the app service ending with "simpleAuth," click on 'Configuration'/'Environment Variables' to verify the client Secret. If either is incorrect, please delete the resource group and attempt the process again.
Also, verify entered Client ID is same in Manifest which you or tenant admin have uploaded to teams Admin. If it is incorrect, remove the app from Teams Admin and reupload it with correct client Id.

**Comment by JayPdsn** [comment]
Got this issue fixed. Thank you much!
