### ISSUE TITLE
Location entry field will not hold data and prevents new incident from being created

### ISSUE THREAD

**Issue by Faulkner-Michael-FLETC** [OfficeDev/microsoft-teams-emergency-operations-center#214]
The Location field does not keep entered information and will not load any map point when clicking the icon. This prevents me from being able to create a new Incident.  I do not have the map option selected and do not have a Bing map key. 

 
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/174053476/b8ff7f98-2b6d-4ab6-b480-a66930afff16)
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/174053476/79c9618f-5c84-4500-995a-420f9d353712)

**Comment by v-ajaysahu** [comment]
@Faulkner-Michael-FLETC , thank you for reporting this issue. 
Please open Teams in your browser and then open the developer tools. Next, launch the app, attempt to replicate the error, and share the console logs and network trace with us to troubleshooting the problem.
