### ISSUE TITLE
Upgrade Failed

### ISSUE THREAD

**Issue by thatguy9129** [OfficeDev/microsoft-teams-emergency-operations-center#215]
I am trying to upgrade from v0.5.1 to v3.0. I am following the guide published here: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version

I get to Step 5 and go to sync the latest version and I get the attached error. (verbose error: [new 4.txt](https://github.com/user-attachments/files/16022116/new.4.txt))

![2024-06-17_080202](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/41638796/10a9c864-e689-4b08-bde6-b016341360f8)

**Comment by v-ajaysahu** [comment]
@thatguy9129 , thank you for reporting the issue. 
Based on the error screenshot, it seems that the 'GENERATE_SOURCEMAP' has not been set in the application settings of the App Service. Please ensure to include it. Also, note that the latest version of the app is 3.1.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#5-add-new-application-setting-generate_sourcemap-in-the-app-service
