### ISSUE TITLE
Problem with site provisioning

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-emergency-operations-center#217]
I'm getting a similar error to others when doing the provisioning. We've made sure that we're not quoting any of the entries and that we have short enough names. This is being run with admin rights on the workstation and Global Administrator rights in the tenant. Permissions shouldn't be an issue here. We're trying new site names, so deleted sites aren't an issue. Any idea what to try next?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/61463212/1bda62c8-0a52-48a9-8f33-e4fe74e1a76b)

**Comment by JayPdsn** [comment]
Did you set the execution policy & unblock the file? 

<img width="915" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/5780fdcf-ff76-4f07-b35d-82d3f9443a6b">

**Comment by glblinck** [comment]
Yes. Both of those were done. The script executes.

**Comment by Jimothymc** [comment]
I also have this issue, script executes but fails at the provisioning with the exact same error.

**Comment by v-ajaysahu** [comment]
@glblinck , thank you for reporting this issue.
Please ensure that you are executing these scripts on PowerShell 7.2 or later, as it is a prerequisite for using PnP PowerShell. Additionally, update PnP PowerShell and attempt to run the scripts again.

**Comment by Jimothymc** [comment]
I am running 7.4.2, if you have access to a new Vm can you please test?
I have followed the steps to the letter, there is another post that stated they had to edit the script to get it working, so 3 people all having the same issue indicates there is an issue of sorts, 

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/216

**Comment by glblinck** [comment]
> @glblinck , thank you for reporting this issue. Please ensure that you are executing these scripts on PowerShell 7.2 or later, as it is a prerequisite for using PnP PowerShell. Additionally, update PnP PowerShell and attempt to run the scripts again.
> 
> https://pnp.github.io/powershell/articles/installation.html

The PowerShell and PnP PowerShell versions were fine. The script was erroring on the site creation:
`New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Title $SiteName -Url $TenantURL$EOCSiteURL -Owner $AdminEmail -ErrorAction Stop -WarningAction SilentlyContinue`
The admin email used here was a group, not an individual account, so it couldn't apply the owner. It now has a user account listed as admin, and it's working fine.
