### ISSUE TITLE
App header only displaying in MS Teams

### ISSUE THREAD

**Issue by JayPdsn** [OfficeDev/microsoft-teams-emergency-operations-center#218]
We followed the deployment guide and are only seeing the header inside of Teams. We have redeployed several times and are receiving the same result. All resources have been double checked. 

<img width="1248" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/54b19ed7-07ef-423c-b216-f6f7dc579e6f">

<img width="1019" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/23def88c-d25b-4f5e-ab25-cd9ce98491f4">

<img width="1027" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/2a035fe0-5337-44c2-a43b-e7e8028cf903">

<img width="1209" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/46325cc1-f6c7-4ed8-9467-6a5ac097c30f">

Does anyone have time for a Teams meeting to assist? Thanks in Advance!

**Comment by v-ajaysahu** [comment]
@JayPdsn , thank you for reporting this issue.
The screenshot you have provided does not detail your error. Please open Teams in your browser, then access the developer tools, launch the app, and share the console logs and network trace to help us troubleshoot the problem. Also, please provide the manifest file that you zipped and uploaded to the Teams Admin.

**Comment by JayPdsn** [comment]
Thanks for the quick response! Absolutely


[TeamsEOCTblShooting.zip](https://github.com/user-attachments/files/16053525/TeamsEOCTblShooting.zip)

**Comment by JayPdsn** [comment]
Let me know when you have the files so I can remove from the post.. Thanks

**Comment by v-ajaysahu** [comment]
@JayPdsn ,
Yes, we have received the shared files. You may proceed to delete them. We will need some time to review the contents and will provide our feedback accordingly.

**Comment by JayPdsn** [comment]
Files removed. I definitely understand. Appreciate the help.

**Comment by v-ajaysahu** [comment]
@JayPdsn ,
After reviewing the shared logs, it appears that the base resource name may contain capital letters, or the SharePoint Site name could be incorrect. To confirm this, navigate to the Azure Resource group, select 'deployments', and then choose "Microsoft.template". Next, select 'inputs' to check the values that were entered. The Base Resource name should not include any capital letters, and the SharePoint Site name should not include the full URL; it should only be the name of the SharePoint site provisioned in step 1 (for example, the exact site name from the URL, such as 'TeamsEOCSite').

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription

**Comment by JayPdsn** [comment]
The base resource name does look correct (all lowercase). 

It does look like the the full URL was entered. Is this editable? Do we have to remove the resource group and redeploy?

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/173822398/b23e7ca8-0b16-470b-972d-5e9b16fc9532)

**Comment by JayPdsn** [comment]
Okay we will delete the teocresourcegroup and redeploy. I will let you know if this works. Thank you much for the help.

**Comment by JayPdsn** [comment]
That worked. Thanks
