### ISSUE TITLE
User assignment to Incident

### ISSUE THREAD

**Issue by n9jle** [OfficeDev/microsoft-teams-emergency-operations-center#219]
Once a user is assigned to a particular incident , they are available to be assigned to multiple other incidents at the same time. Is there a workaround for this? And, if skills need to be added to the worker (ESF #2, Planning, Damage Assessment, etc.) is it the best practice to add those to a new table in TEOC?

**Comment by v-ajaysahu** [comment]
@n9jle , thank for reporting this issue.
Indeed, you can include the same user in multiple incidents. However, if you prefer that the user not be part of any other incident, then you should not include them when creating the incident from the TEOC. 
Regarding your second query, are you asking if you want to add more details pertaining to the user?

**Comment by v-ajaysahu** [comment]
To achieve this, you can create a New Role and ensure to select "Save default users for this role" during the process. This way, in the future, if someone chooses this new role, users will automatically populate. 
I hope this resolves your query.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#create-incident

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/154988719/673f80a9-3d1d-4a96-aba9-d90230917a7a)
