### ISSUE TITLE
Unable to geocode address in Location column on Assessment List

### ISSUE THREAD

**Issue by eendrulat** [OfficeDev/microsoft-teams-emergency-operations-center#22]
When signing in as a guest user, the Assessment List 'Location' field does not geocode addresses as they are entered. I see the following error in the network log that appears to be associated with behavior:

===============

```
{
	"error": {
		"code": "10001",
		"message": "AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2022-04-12T01:12:29.2293309Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2022-04-18T23:03:44.0000000Z'.\r\nTrace ID: 4b15ec88-c643-4890-8ee8-b4e82f7ada00\r\nCorrelation ID: aa043ea0-a0bc-1000-ce5c-4e71b88a02d4\r\nTimestamp: 2022-05-16 18:25:03Z",
		"@error.redirectUrl": "https://cestp3.sharepoint.com/sites/TEOC_3/Lists/TEOCAssessments/AllItems.aspx?reauthid=2.MXwwfA.M_GVuwnwruwefSDPm4MKHMakFQchC_dR53nb_4G3OC8kk_fxhNnE08eF1KVQOiPko4eyD3jbgTe2TpgQFjEV9qGYaCwIkjxsc5gnllXPVcTymxGiGCredhNtAYqJmSAxuxbC2dYn3epx3w6cwAETFoCBfptNLQA4jhjltYekIqfu74QkTbaiVhAbMbt-6Wul8Gk9RHBJjrhV7zJJPaQBAgsqiNK0Uhmw4ayAJsybNifYbRaXh5j8BDRQpx1AOoBssN57Vl80lY0it8KUCxZi8nUFYiFDzHDHfPaertU7o_zfGcIuUdTdvUI_iXgKCOh3J7Y-hBQfCKwPVUbFegKrxQ"
	}
}

```

The behavior works as expected when signed in as a licensed Microsoft 365 user.

![geocodeIssue](https://user-images.githubusercontent.com/527590/168664094-16b41bf6-9474-4d2b-b4b5-a661fb0e9b5a.png)

**Comment by v-saikirang** [comment]
Hi @eendrulat,
We were able to replicate this issue on our tenant. And unfortunately this seems to be the default behavior of the Share Point list and "Location" column for guest account. This is not related to Teams or EOC app specifically. This issue would show up when you open the share point list directly and we are just embedding the list in our Teams channel. So we have no control over this.
We will notify this issue with appropriate team and hoping for resolution in future. Please continue to use the app with Office 365 users for now. Thanks for your feedback.

**Comment by v-saikirang** [comment]
Hi @eendrulat,

Please confirm if we can close this ticket for now.
Thanks.

**Comment by eendrulat** [comment]
Yes, thanks for the info - good to close this.
