### ISSUE TITLE
Display issue: Drop-downs with lots of whitespace

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-emergency-operations-center#220]
Using the new Teams client with this solution, I'm getting lots of whitespace around the items in the drop-down fields. This seemed to start when we transitioned from classic Teams to new Teams. Would you have any solution to this? I know it's just a display issue, but it's annoying for users.
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/61463212/e836f593-5f5c-4895-8797-4aa3c4451b77)

**Comment by v-ajaysahu** [comment]
@glblinck , thank you for reporting this issue.
We will address this scenario in upcoming release.

**Comment by v-saikirang** [comment]
Hi @glblinck,
We have fixed this issue in the new v3.2 release. Once you upgrade the issue will be gone. We are closing this ticket for now. Please let us know if you see any issues.
Thanks.

**Comment by glblinck** [comment]
[celebrate]     Glenn Blinckmann reacted to your message:
________________________________
