### ISSUE TITLE
Not seeing full screen - only top and welcome banner

### ISSUE THREAD

**Issue by GitRomney** [OfficeDev/microsoft-teams-emergency-operations-center#221]
All the required resources are deployed, code deployed successfully from GitHub external Git repo, and TEOC manifest updated with our App Service and App Registration settings, but the TEOC page is incomplete. We're not able to see the incident list or any actions available. We've checked the manifest over and over and reviewed the attached har logs but can't figure it out. I've attached the manifest and network logs. Thanks in advance for your help.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/66702506/c613bc23-5e1b-46d2-be4a-6e47eeb9b84f)

**Comment by v-ajaysahu** [comment]
@GitRomney , thank for reporting this issue.
Please allow us some time to review the shared logs. We will provide our feedback accordingly.

**Comment by GitRomney** [comment]
May I remove the logs now, for privacy?

**Comment by v-ajaysahu** [comment]
@GitRomney ,
Yes, you can delete it. I have downloaded the logs.

**Comment by v-ajaysahu** [comment]
@GitRomney ,
After reviewing the shared logs, it appears that the base resource name or the SharePoint site name is incorrect. To confirm this, you need to go to the Azure Resource Group, select Deployments, and then choose "Microsoft.Template". Next, click on 'Inputs' in the left pane to view the values you have entered. 
The Base Resource name should not include any uppercase letters, and the SharePoint Site Name should not be the full Site URL; it should only be the site name. For instance, if the site URL is https://example.sharepoint.com/sites/TEOCSite, then the input should be just 'TEOCSite'. If that's the case, you need to delete the resource group and then repeat the process.
Please check and confirm.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription

**Comment by GitRomney** [comment]
Working with our Cloud Operations team, they suggest that the values are correct. We had this working correctly with the same values in a Build environment. Now that we've moved to a Production environment, it isn't working. We don't see any difference in the values. 

Would you be available to meet tomorrow, Friday, 7/12 8am-10am; 11am-12pm; or 1pm-5pm Central Daylight Time? My email is joel.mehr@nm.org, if you are able to send a Teams Meeting invite. Thank you!

**Comment by v-ajaysahu** [comment]
@GitRomney ,
As per your suggested time, I've scheduled a Teams Meeting at 8am Central Time.

**Comment by v-ajaysahu** [comment]
> @GitRomney , After reviewing the shared logs, it appears that the base resource name or the SharePoint site name is incorrect. To confirm this, you need to go to the Azure Resource Group, select Deployments, and then choose "Microsoft.Template". Next, click on 'Inputs' in the left pane to view the values you have entered. The Base Resource name should not include any uppercase letters, and the SharePoint Site Name should not be the full Site URL; it should only be the site name. For instance, if the site URL is https://example.sharepoint.com/sites/TEOCSite, then the input should be just 'TEOCSite'. If that's the case, you need to delete the resource group and then repeat the process. Please check and confirm.
> 
> https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription

@GitRomney ,
As discussed in our meeting, the SharePoint Site URL is incorrect. As suggested, you need to delete the resource group and repeat the process.

**Comment by GitRomney** [comment]
Adjusting to use just the site name and not the entire URL was indeed the solution. I think part of our confusion stemmed from settings being cached, so when we thought we were changing something, the app wasn't reflecting the change until much later. We rebuild from scratch using just the site name (e.g., "TEOCSite") and not the entire URL (e.g., "https://example.sharepoint.com/sites/TEOCSite"), and now everything is displayed as expected.

Looking through support cases, we seem to not be the only ones who made this mistake. Perhaps, in Step 6, part iv in the "3. Deploy to your Azure subscription" section of the deployment guide, you might want to add a line to avoid confusion. Maybe say, "Note: add just the site name. For example, if the URL of your SharePoint site is "https://example.sharepoint.com/sites/TEOCSite," add "TEOCSite" and not the entire URL." 

![image](https://github.com/user-attachments/assets/6b0f703a-eedd-4603-85a3-35e53c104ef1)

**Comment by v-ajaysahu** [comment]
@GitRomney ,
Thank you for your suggestion; we will update the deployment guide accordingly. As your issue has been resolved, I am closing this issue.
