### ISSUE TITLE
Location Rejects input on Create New Incident

### ISSUE THREAD

**Issue by RyboTech** [OfficeDev/microsoft-teams-emergency-operations-center#223]
When creating a new incident in the "New Teams", the location rejects all input.  Any combination of alphanumeric values is cleared once focus leaves the entry text box.

The "Map" icon does not work either.  

It appears that something is trying to show up, like a pop-up, but under the text box.  It goes away after it tries to appear.

https://github.com/user-attachments/assets/fcb0e90a-1af5-4200-a464-3bb1a9dcd817

**Comment by v-saikirang** [comment]
Hi @RyboTech. Thanks for reaching out to us.

Can you please verify if you have configured the Permissions for Office 365 Exchange Online according to the instructions provided in the following documentation.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#6-add-permissions-for-office-365-exchange-online

**Comment by RyboTech** [comment]
This did fix it.  Thank you.

I followed the direction before.  I did press the Grant Admin Consent.  

How could that one permission get removed?

Also, FYI, the documentation is does not take into account that Azure has moved to Microsoft Graph.  The Calendar.Read is in that group.

Thanks again for your help!

**Comment by RyboTech** [comment]
This has been fixed.
