### ISSUE TITLE
Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -WarningAction SilentlyContinue - Error Message:  Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by BrandtC-NAIT** [OfficeDev/microsoft-teams-emergency-operations-center#224]
I debug ran the script and here is what happened:

```
[PS] 'C:\Users\---MY LOGIN---\Documents\One-Offs\TEOC\microsoft-teams-emergency-operations-center\Deployment\provisioning\EOC-Provision.ps1'

Enter site template XML schema file path: C:\Users\---MY LOGIN---\Documents\One-Offs\TEOC\microsoft-teams-emergency-operations-center\Deployment\provisioning\EOC-SiteTemplate.xml
C:\Users\op.brandtc\Documents\One-Offs\TEOC\microsoft-teams-emergency-operations-center\Deployment\provisioning\EOC-SiteTemplate.xml
Enter tenant name: (contoso): ---OUR TENANT---
Enter tenant admin email: ---A VALID EMAIL IS HERE---
Enter site name. Allowed characters for site name are underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period.: Facilities_Emergency_Management
PnP.PowerShell module found

Checking if site already exists at /sites/Facilities_Emergency_Management

Site doesn't exist, creating new site at /sites/Facilities_Emergency_Management

https://---OUR TENANT---.sharepoint.com/sites/Facilities_Emergency_Management

Creating lists in Facilities_Emergency_Management site

Error Message:  Attempted to perform an unauthorized operation.

```
It fails on this line of code, line #66:
`Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -WarningAction SilentlyContinue`

I've moved the File around to different locations to make sure the file is accessible. Tried running the script an non & privileged PowerShell.

NOTE: any ---VALUE PLACEHOLDER--- is me removing the content for security reasons in this post.

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,

Thanks for reaching out to us.

Please ensure that you are executing these scripts on PowerShell 7.2 or later, as it is a prerequisite for using PnP PowerShell. Additionally, update PnP PowerShell and attempt to run the scripts again.

https://pnp.github.io/powershell/articles/installation.html

Please let us know if this worked.

Thanks.

**Comment by BrandtC-NAIT** [comment]
Same issue under PowerShell 7.4.1 and Updated PnP Module

`Error Message:  Attempted to perform an unauthorized operation.`

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,

Can you please try creating a different site name without under scores
"Enter site name. Allowed characters for site name are underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period.: Facilities_Emergency_Management"

**Comment by BrandtC-NAIT** [comment]
Tried that, no spaces, only Mixed Caps: FacilitiesEmergencyManagement

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,

Can you please check if the SP site is created and if any lists are created.

**Comment by BrandtC-NAIT** [comment]
As reported by the SharePoint Team: https://imgur.com/a/SebYcA8](url)

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,

Can you please share a screenshot directly here instead of the link.

Thanks.

**Comment by BrandtC-NAIT** [comment]
![image (6)](https://github.com/user-attachments/assets/c1ccd801-c960-4f6b-b9c2-97f4725cc5d4)
![image (5)](https://github.com/user-attachments/assets/4620c74b-e4d2-48e1-bcfc-a7986f94b17c)
![image (4)](https://github.com/user-attachments/assets/632a0b65-35af-441b-8928-b825f4b7635c)
![image (3)](https://github.com/user-attachments/assets/1f9dfcce-988f-494b-86ec-3ba88dd6e7fc)
![image (2)](https://github.com/user-attachments/assets/56b2b2d9-4e73-4df7-bed0-d1c87501d51f)
![image (1)](https://github.com/user-attachments/assets/7fa54d7b-ca46-4bec-a11a-c3f1875274fc)
![image](https://github.com/user-attachments/assets/ee499ba7-cc83-4269-95a9-66d52f4f4021)

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,
Thanks for sharing the screenshots. Please make sure you are added as site collection admin to the share point site and try to tweak the script to run only the lists creation. Update the URL variable with full site URL since the site is already created.

 Connect-PnPOnline -Url $TenantURL$EOCSiteURL -Interactive

    Write-Host "Creating lists in $SiteName site"

    Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -WarningAction SilentlyContinue
          
    Write-Host "App Provision complete."

**Comment by BrandtC-NAIT** [comment]
`2.5.0                PnP.PowerShell`

Hardcoding in the path with the below changes did the trick:

`# Write-Host "Checking if site already exists at $EOCSiteURL"
    # $site = Get-PnPTenantSite -Url $TenantURL$EOCSiteURL -ErrorAction SilentlyContinue

    # if ($null -ne $site) {
    #     Write-Host "Site already exists, exiting the PowerShell script"
    #     return;
    # }
    # else {
    #     Write-Host "Site doesn't exist, creating new site at $EOCSiteURL"
    # }

    # try {
    #     if (($TenantURL + $EOCSiteURL).Length -lt 128) {
    #         New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Title $SiteName -Url $TenantURL$EOCSiteURL -Owner $AdminEmail -ErrorAction Stop -WarningAction SilentlyContinue
    #     }
    #     else {
    #         Write-Host "Site creation failed. Site URL cannot have more than 128 characters." -ErrorAction Stop
    #         return
    #     }
    # }
    # catch {
	#     Write-Host "`nError Message: " $_.Exception.Message
    #     Write-Host "Site creation failed. Site name cannot contain symbols other than underscore, dashes, single quotes, and periods (_,-,',.), and can't start or end with a period."
    #     return;

    # }

    $TenantURLEOCSiteURL = "https://---OUR TENANT---.sharepoint.com/sites/FacilitiesEmergencyManagement"
    
    Connect-PnPOnline -Url $TenantURLEOCSiteURL -Interactive

    Write-Host "Creating lists in $SiteName site"

    Invoke-PnPSiteTemplate -Path $FilePath -ErrorAction Stop -WarningAction SilentlyContinue
          
    Write-Host "App Provision complete."`

NOTE: any ---VALUE PLACEHOLDER--- is me removing the content for security reasons in this post.

**Comment by v-saikirang** [comment]
Hi @BrandtC-NAIT,

So as i understand the issue is cleared now. Please confirm if i can close the ticket.
Thanks.

**Comment by BrandtC-NAIT** [comment]
@v-saikirang please do close the ticket. Issue is now resolved.
