### ISSUE TITLE
Bad Requests when opening App in Teams

### ISSUE THREAD

**Issue by clarkec2** [OfficeDev/microsoft-teams-emergency-operations-center#225]
Hello, 

When attempting to open the app after deploy I am met with large amounts of white space. When inspecting the traffic I see 3 bad requests being sent to SharePoint and Graph which I believe is what is causing the blank space. 

![image](https://github.com/user-attachments/assets/d58da918-fd8e-4e30-b5c3-37d651881c64)

HTTP/1.1 400 Bad Request
Content-Length: 3490
Content-Type: text/html; charset=utf-8
Date: Mon, 15 Jul 2024 21:58:23 GMT
Server: Microsoft-IIS/10.0
Cache-Control: private
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET

<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            </font>

    </body>
</html>

For the Graph requests...

HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 5c565874-52ec-49cc-9720-673c9d38b396
client-request-id: b46382f9-1626-9969-af8d-88e7d7e49715
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"4","ScaleUnit":"000","RoleInstance":"CH01EPF00007336"}}
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id, ReadWriteConsistencyToken, Retry-After, SdkVersion, WWW-Authenticate, x-ms-client-gcc-tenant
Date: Mon, 15 Jul 2024 21:58:24 GMT

and

HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 7f3ab65f-a96f-4f52-9a9d-71b1a30caab5
client-request-id: 7098cef7-48f8-66fc-e9f6-6ae24a0454d4
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"4","ScaleUnit":"000","RoleInstance":"CH01EPF00007336"}}
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id, ReadWriteConsistencyToken, Retry-After, SdkVersion, WWW-Authenticate, x-ms-client-gcc-tenant
Date: Mon, 15 Jul 2024 21:58:24 GMT

**Comment by v-ajaysahu** [comment]
@clarkec2 , thanks for reporting this issue.
Please launch Teams in your browser, then access the developer tools and open the TEOC app. Share the console logs and network traces to assist in troubleshooting the issue.
Additionally, please provide us with the manifest files.

**Comment by clarkec2** [comment]
We were able to fix it, it was an issue with the SP site used. Now when attempting to test the app I am unable to use the location field, no matter what is inputted the field automatically clears itself. The button in the box also doesnt work and it will not pop up any thing so I cannot create an incident for testing.  Also when attempting to setup the Map viewer I am met with an error stating that the service is being migrated/deprecated, is there an alternate key that can be used? Azure Maps possibly?

**Comment by v-ajaysahu** [comment]
@clarkec2 ,
The Location Field does not rely on a Bing Maps or Azure Maps subscription. It seems you may have forgotten to add permissions to access the Calendar. The link provided below should help resolve this issue. After granting the necessary permissions, please check if the location picker field in the app is functioning correctly.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#6-add-permissions-for-office-365-exchange-online

**Comment by clarkec2** [comment]
That did appear to be the case, we consented to the missing permission, and re uploaded the app, however the Location input is still broken. Same behavior as before, auto clears anything inputted and the map button is not working.

**Comment by v-ajaysahu** [comment]
@clarkec2 ,
Please clear your cache and attempt the process again. If the issue continues, open Teams in your browser, then open developer tools. Next, launch the TEOC app and attempt to replicate the problem. Kindly share the console and network logs from the developer tool.
