### ISSUE TITLE
Microsoft Teams Emergency Operations Center secret expired

### ISSUE THREAD

**Issue by frspecial** [OfficeDev/microsoft-teams-emergency-operations-center#226]
Our Microsoft Teams Emergency Operations Center secret has expired. We have generated a NEW secret value but do not know where to update it?

**Comment by v-saikirang** [comment]
Hi @frspecial,

Thanks for reaching out to us.

Please refer to the this section of the wiki to update your client secret - https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Troubleshooting#1-client-secret-expiry

After performing the steps please allow some time, clear out cache and try again.

Thanks.

**Comment by frspecial** [comment]
Thanks ! That did it. Much appreciated.

Rgds,



Frank Special
Cloud Architect
TECO An Emera Company
Cell: 561-306-7024





________________________________
