### ISSUE TITLE
An error has occurred, while retrieving incidents, please refresh the app.

### ISSUE THREAD

**Issue by leratolempe** [OfficeDev/microsoft-teams-emergency-operations-center#228]
Good day.

We have successfully implemented the TEOC which seems operational, however when loading the App we get an error on the dashboard: An error has occurred, while retrieving incidents, please refresh the app.
<img width="914" alt="An error has occurred" src="https://github.com/user-attachments/assets/0456be66-e92d-41bd-9eaa-e9f8e74a9c7d">

Additionally, when trying to create an incident, the App just hangs at "Please wait".
<img width="896" alt="Please wait " src="https://github.com/user-attachments/assets/974446db-2086-4f25-9e42-3b3f82635bd7">

Can you please assist us with resolving these issues.

**Comment by v-saikirang** [comment]
Hi @leratolempe,

Thanks for reaching out to us.

Can you please share a screenshot of the site contents page of the Share point site that you provisioned.

Thanks.

**Comment by leratolempe** [comment]
Good Day

Good day
Thank you so much for your response and willingness to assist. Please see below screenshot as requested:

***@***.***

Looking forward to your response.

Kind Regards,
Lerato Lempe

**Comment by leratolempe** [comment]
Good day
Thank you so much for your response and willingness to assist. Please see below screenshot as requested:

<img width="901" alt="image" src="https://github.com/user-attachments/assets/c4c3c719-2b5f-446a-a9c2-1a778b1cf549">

Looking forward to your response. Thanks in advance.

**Comment by v-saikirang** [comment]
Hi @leratolempe,
Thanks for the screenshot. Looks like the provisioning of the lists did not happen. 
Can you please delete this site from SP admin center from "Active Sites" and then from "Deleted sites" too. Then try to run the script again by providing the same site name, and let me know if that works.
Please wait until you see, the App provision complete message. Provisioning will take around 20 to 30 mins.

![image](https://github.com/user-attachments/assets/6ad3103c-4f33-43ce-92a9-be9acf9c05b2)

Thanks.

**Comment by leratolempe** [comment]
Good day

Apologies for the delayed response. The app provisioning completed successfully, the error has disappeared and it seems that incidents can now be created. Just waiting for end user testing. Thank you so much for your assistance.

![App provisioning complete](https://github.com/user-attachments/assets/9621c54e-cfb9-4e54-a8ae-d166d31d4774)

<img width="905" alt="Create incident" src="https://github.com/user-attachments/assets/c1a6ba3e-9d84-49fd-9a38-374792e90c25">
