### ISSUE TITLE
Unable to add guest users

### ISSUE THREAD

**Issue by mihikagulhane** [OfficeDev/microsoft-teams-emergency-operations-center#229]
<img width="899" alt="teoc_teams_app_error" src="https://github.com/user-attachments/assets/fdff1514-e4c9-4f31-855b-987b54d8dec8">
I was trying to add guest users in one of the incident and I was unable to add it.
I tried many a times with different persons but it shows the same error.

**Comment by v-saikirang** [comment]
Hi @mihikagulhane,

Is the user that you are trying to add as guest from the same tenant as yours's? From the screenshot it  looks like the guest user is from the same tenant where the app is installed. Please confirm.
Thanks.

**Comment by mihikagulhane** [comment]
Hi team,

Yes, the guest user I’m trying to add is from the same organisation as mine.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mihikagulhane** [comment]
Hi Sai,

Thanks for informing me.
I have a follow-up question regarding role assignment. Specifically, I am inquiring whether it is possible to customize the settings to restrict incident visibility in the dashboard. For instance, can we configure the system to display only those incidents for which the user is a member? For now who have access to the app can see all the incidents in dashboard.
Your insights on this matter would be greatly appreciated.
Thank you for your attention to this query.

Kind Regards,
Mihika
________________________________

**Comment by v-saikirang** [comment]
Hi @mihikagulhane,

Appreciate your feedback.

As of now the dashboard is visible to every user but only the incident members will be allowed to the "Teams" associated with it. And only the Incident commander and secondar incident commander will be allowed to "Edit" the incident. 

We will still consider your feedback and if possible try to implement this restriction based on feasibility and priority in our future releases.

Hope this answers your question.

Thanks.

**Comment by mihikagulhane** [comment]
[like]  Gulhane Mihika INPU reacted to your message:
________________________________

**Comment by mihikagulhane** [comment]
> Hi @mihikagulhane,
> 
> Appreciate your feedback.
> 
> As of now the dashboard is visible to every user but only the incident members will be allowed to the "Teams" associated with it. And only the Incident commander and secondar incident commander will be allowed to "Edit" the incident.
> 
> We will still consider your feedback and if possible try to implement this restriction based on feasibility and priority in our future releases.
> 
> Hope this answers your question.
> 
> Thanks.

Hi Team,
Do you have a timeline for this particular enhancement/feature.

Thank You!
Kind Regards,
Mihika
