### ISSUE TITLE
PeoplePicker not showing users

### ISSUE THREAD

**Issue by Robbayly** [OfficeDev/microsoft-teams-emergency-operations-center#23]
Hi team,

Just successfully deployed the solution and first site - great guide etc.

However the people picker is not searching and displaying a filtered result e.g David - is only returning 1 user, when there's over 20 active David's, no "Andrew" when there's 20. it's really hit-n-miss.

SharePoint PeoplePicker can find these users, as can add Member to Team - is there a filter or group

![2022-05-25 16_27_12-General (DEMO) _ Microsoft Teams and 9 more pages - WHC - Microsoft​ Edge Beta](https://user-images.githubusercontent.com/25297019/170195294-548acc80-5d5a-4175-acba-f60015461016.png)
![2022-05-25 16_28_06-Users - Microsoft Azure and 9 more pages - WHC - Microsoft​ Edge Beta](https://user-images.githubusercontent.com/25297019/170195300-5ab81a90-ed7a-414c-b600-95eb5086d0d1.png)

TIA
Rob

**Comment by Robbayly** [comment]
checked in desktop as well as web-based

**Comment by v-saikirang** [comment]
Hi @Robbayly,

Thanks for your feedback. 

Can you please try typing in the full email of the person and see if it shows up in the people picker..

Thanks.

**Comment by Robbayly** [comment]
Thanks will try in the morning

P: 1300611359 | M: 0415818373
Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by v-saikirang** [comment]
Thanks @Robbayly.

Can you also please confirm if the person that's showing up in the people picker is some one that you interact with or part of any common groups and vice versa with the persons that are not showing up.
Thanks.

**Comment by Robbayly** [comment]
Hi team,

Tried pasting and typing in the users email address – still no match found.

Of the 6 names displayed when entering the people picker, 3 are frequent contacts, the other 3 are not. None are member of the current M365 Team group hosting the EOC app.

Looking through the deployment guide, in the Graph permissions 4.5.iii People.Read – it’s described as “Allows the app to read a scored list of people relevant to the signed-in user.” Investigating brought me to Use the people API in Microsoft Graph to get information about the people most relevant to you - Microsoft Graph | Microsoft Docs<https://docs.microsoft.com/en-us/graph/people-example>. We’re using a admin account, which doesn’t have day-to-day interaction via email / teams / etc. So this may be the cause?

Our client’s staff are across several geographically dispersed locations, and may need to include non-related staff members from other sites as part the incident management process or team. In which case this “scored list” becomes a limiting factor.

If this is the limiting scope, is here an alternative permission or API which can be substituted? And where would we update that in the app?


Kind Regards

Rob Bayly | Practice Lead – Support Services
M:  +61 415 818 373  |  E:  ***@***.******@***.***>
P:  1300 611 359 |  www.sharingminds.com.au<http://www.sharingminds.com.au/>

**Comment by Robbayly** [comment]
Is this a scenario where we may need to manage the people insight privacy level within the tenancy, vis https://docs.microsoft.com/en-us/graph/insights-customize-people-insights-privacy ?

By default, the display or return of people insights is enabled for an organization. Administrators with the global administrator role can customize this behavior for an organization using REST APIs and the appropriate permissions. They can customize by setting properties of the insightsSettings resource in the following ways:

Disable people insights for all users in the organization, by setting the isEnabledInOrganization property of the insightsSettings resource to false. (By default, the isEnabledInOrganization property is true.)

Disable people insights for a subset of users, by assigning these users to an Azure Active Directory (Azure AD) group, and setting the disabledForGroup property to the ID of that group. Find out more about creating a group and adding users as members.

**Comment by v-saikirang** [comment]
Hi @Robbayly,

Can you please try adding this new graph api permission "User.ReadBasic.All" by following the steps mentioned in the section "4. Add Permissions to Microsoft Graph Azure AD app" in the [deployment guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-add-permissions-to-microsoft-graph-azure-ad-app).
This change may take some time take affect. So if you dont see changes reflect right away please check after 1-2 hours.

Please let us know how this turns up.
Thanks.

**Comment by Robbayly** [comment]
Thanks Team, that worked, and was almost instantaneous. Saw the app reload in Teams, and full search enabled.
