### ISSUE TITLE
Error updating the App Service from 3.0 to 3.1.

### ISSUE THREAD

**Issue by ToC-Tthor** [OfficeDev/microsoft-teams-emergency-operations-center#231]
Running the Sync in App service to update results in this error:

`Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/abort-controller@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-auth@1.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-client@1.9.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-http-compat@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-lro@2.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-paging@1.6.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-rest-pipeline@1.16.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-tracing@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-util@1.9.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/keyvault-keys@4.8.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/logger@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.19.2' }
npm WARN EBADENGINE }`

I tried changing Node version to 18, but now results in:
```
Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.1.0',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```

**Comment by v-ajaysahu** [comment]
@ToC-Tthor , thanks for reporting this issue.
Have you added the GENERATE_SOURCEMAP to your application settings in the app service as outlined in the upgrade instructions?
Reference Link: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#5-add-new-application-setting-generate_sourcemap-in-the-app-service

**Comment by ToC-Tthor** [comment]
I believe I have, the panel is different now than the documentation.  Application Settings no longer seems to be under the Configuration blade.

[cid:a6e693bf-a48a-4f2e-b23b-aee8dd307a7a]
________________________________

**Comment by v-ajaysahu** [comment]
@ToC-Tthor , If you cannot locate Application Settings within the Configuration blade, they should be available under the Environment Variables blade. Please verify and confirm.

**Comment by ToC-Tthor** [comment]
That's correct, and that is where I have the Generate_sourcemap = false configured.
________________________________

**Comment by v-ajaysahu** [comment]
@ToC-Tthor ,
Please reset your Node version to 16.13.0 and attempt the process once more. If the issue persists, kindly provide your email address here on GitHub along with your available times (note: our availability is from 10 AM to 7:30 PM IST only).

**Comment by ToC-Tthor** [comment]
Thank you @v-ajaysahu, I have reset to Node 16.13.0 and re-run the sync, however it still errors as before.   My email is trevor.thorsteinson@canmore.ca.  Friday the 23rd I am available all day.

**Comment by v-ajaysahu** [comment]
@ToC-Tthor ,
I have scheduled a meeting on 23rd at 7 PM IST.

**Comment by ToC-Tthor** [comment]
Hello, the last redeploy from our testing errored out as before.


FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0104343B v8::internal::Heap::PageFlagsAreConsistent+3099
 2: 01037744 v8::internal::Heap::CollectGarbage+2116
 3: 01035D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run-script build
An error has occurred during web site deployment.
npm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: ***@***.******@***.***',\r\nnpm WARN

________________________________

**Comment by v-ajaysahu** [comment]
@ToC-Tthor ,
A meeting has been scheduled for Monday, 26th August 2024, at 7 PM IST to address and troubleshoot the issue.

**Comment by ToC-Tthor** [comment]
@v-ajaysahu looks like changing the app service plan back to S2 did solve the issue.  I have now successfully upgraded to 3.1.

**Comment by v-ajaysahu** [comment]
@ToC-Tthor ,
The issue arose from downgrading the APP Service plan to Basic and was resolved after upgrading back to the Standard S2 plan. As this issue is resolved, I am closing it. If you have any queries, feel free to comment here.
