### ISSUE TITLE
TEOC after deployed when in welcome screen of the app it gives an error  “ An error has occurred, while retrieving incidents, please refresh the app.”  and when creating new incident it loads doesn't give any error 

### ISSUE THREAD

**Issue by sivanikakuru09** [OfficeDev/microsoft-teams-emergency-operations-center#232]
1.	TEOC (Teams emergency operation center)

When the app loads , the page gives an error message that “ An error has occurred, while retrieving incidents, please refresh the app.” 
Refer TEOC1
 
When I try to click on creating  “New incident”  tab it loads as below screen and doesn’t throw any error. 
Refer TEOC2
 

![TECO1](https://github.com/user-attachments/assets/d8491d56-91b6-4824-b74b-08a538f37dc4)
![TEOC2](https://github.com/user-attachments/assets/4162ac47-4308-4557-9bbf-d622608070dd)

**Comment by v-saikirang** [comment]
Hi @sivanikakuru09,

Thanks for reaching out to us.

This looks an issue with provisioning the share point lists. Can you please refer to the [Issue 228](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/228) and follow the instructions.

Thanks.
