### ISSUE TITLE
URGENT: App hung at "Login" in desktop and online Teams

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#233]
Just shows a Login box and when we try to login it just hangs there.

Have restarted the service.  Any ideas?

**Comment by v-ajaysahu** [comment]
@tcrobbins4 , thank you for reporting this issue.
Please ensure that the base resource name and SharePoint site name are correct. 

- To do this, navigate to the Azure Resource Group, select 'Deployments', and then pick "Microsoft.Template". 
- Afterwards, click on 'Inputs' in the left pane to review the values you've entered. 
- The base resource name should not contain any uppercase letters, and the SharePoint site name should be just the site name, not the full URL. For example, if the site URL is https://example.sharepoint.com/sites/TEOCSite, the correct input would be 'TEOCSite'. If this is not the case, you will need to delete the resource group and start the process over. 

Please verify and confirm.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription

**Comment by tcrobbins4** [comment]
I verified everything you noted and everything matches as it should. SharePoint site is reachable and no changes made to it that I know of.

**Comment by v-ajaysahu** [comment]
@tcrobbins4 , thanks for confirming.
As you have confirmed that there are no changes from your side, please check if the client secret has expired. If it has, kindly follow the link provided below.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Troubleshooting#1-client-secret-expiry

**Comment by tcrobbins4** [comment]
That did it.  Thank you.  I will put a reminder on my calendar for next expiration :)
