### ISSUE TITLE
An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by leratolempe** [OfficeDev/microsoft-teams-emergency-operations-center#234]
Good day
Can you kindly assist. When we attempt to create a new incident, we receive the error message "An error has occurred, please try to create your incident again"

<img width="907" alt="An error has occurred, please try again" src="https://github.com/user-attachments/assets/88ea82e8-4cc0-4bb7-a2c1-3f3ef4f7979b">

Your feedback and assistance will be much appreciated. 

Kind Regards,

**Comment by v-ajaysahu** [comment]
@leratolempe , Thank you for reporting this.
Please launch Teams in your browser, then access the developer tools and open the TEOC app. Try to create an Incident and then share the console logs & network traces to assist in troubleshooting the issue.

**Comment by leratolempe** [comment]
Hi @v-ajaysahu 
Thank you for your response and willingness to assist. Please find attached logs as requested. 
[Network Logs.zip](https://github.com/user-attachments/files/16692524/Network.Logs.zip)
[Console Logs.log](https://github.com/user-attachments/files/16692527/Console.Logs.log)

**Comment by v-ajaysahu** [comment]
@leratolempe ,
Based on the logs you've shared, it appears there is an error occurring when attempting to save to the "TEOC-IncidentTransaction" list. Please check the permissions that have been assigned. According to our documentation, users must be added to the Member group to have the ability to save items.

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#1-provisioning-teoc-site

**Comment by leratolempe** [comment]
Thank you so much for your assistance. The issue is now sorted.
