### ISSUE TITLE
TEOC Members Don't see Create New Ticket Button

### ISSUE THREAD

**Issue by nolanpatrick143** [OfficeDev/microsoft-teams-emergency-operations-center#236]
I'm setting up a TEOC Test site for training and familiarization for my organization before we implement a production environment. I got it set up, but users who are assigned as site member, do not see "Create New Ticket" button. I can't find documentation on what the membership level needs to be able to create an incident. We what most users to be able to create an incident, but not have admin access to the application. Is there a doc on how to properly configure access for users to create a new incident?

**Comment by v-saikirang** [comment]
Hi @nolanpatrick143,

As of now by default "Create New Incident" and "Manage" menu is visible to everyone. But when you enable roles from "Admin Settings - > Config Settings", these 2 options will be visible only to people listed in the "TEOC-UserRoles" SP list with "Admin" as "Role".  You can find more details about this option in the wiki : https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#manage-options

Please let us know if you need more information.

Thanks.
