### ISSUE TITLE
Request for Space Reduction Between Dropdown Values - Incident Type Category

### ISSUE THREAD

**Issue by mihikagulhane** [OfficeDev/microsoft-teams-emergency-operations-center#237]
![image](https://github.com/user-attachments/assets/5e0936c9-d8e8-4ff9-889d-86f558a26bc1)

Hi Team,
I am reaching out to inquire about the possibility of reducing the space between the dropdown values of the "Incident Type Category."
Upon reviewing the attached file, it is evident that the current spacing between the dropdown values is causing inconvenience, as users are required to scroll extensively to make a selection. In contrast, the spacing for the "Select Role Category" dropdown is appropriately visible, as illustrated in the attached file for reference.

![image](https://github.com/user-attachments/assets/0165866b-bf79-4d91-9944-b031681514ab)

Given the impact on user experience, I kindly request your assistance in exploring options to minimize the space between the dropdown values for the "Incident Type Category." This adjustment will significantly enhance usability and streamline the selection process for our users.
Your prompt attention to this matter is greatly appreciated. Please feel free to share any insights or recommendations regarding the feasibility of this adjustment.

Thank you for your collaboration and support in improving our user interface.
Best regards,
Mihika

**Comment by v-saikirang** [comment]
Hi @mihikagulhane,

This is a known limitation and we have already addressed this issue. We will plan for a hot fix shortly. Please watch out this space for details.

Thanks.

**Comment by mihikagulhane** [comment]
Thank you for the support in improving our user interface.
Will wait for the fix.

**Comment by v-saikirang** [comment]
Thanks. Closing this ticket.
