### ISSUE TITLE
TEOC Application Admin Role Inquiry

### ISSUE THREAD

**Issue by mihikagulhane** [OfficeDev/microsoft-teams-emergency-operations-center#239]
Hi Team,

I am reaching out to inquire about the availability of an admin role within the TEOC application. Specifically, we are interested in understanding whether it is possible to assign a particular user as an admin who would have access to enter into all incident details, not just those incidents assigned to them?

Your clarification on this matter would be greatly appreciated.
Thank you for your attention to this inquiry.

Best regards,
Mihika

**Comment by v-saikirang** [comment]
Hi @mihikagulhane,

Thanks for reaching to us.

There is such feature that allows a central admin to be part of all incidents. TO be able to get in to incident, a person has to be part of that incident in one or the other role. So they can be added as "Secondary Incident Commander" for each incident if they want to get in.

Please let us know if you need more information.

**Comment by mihikagulhane** [comment]
Having 2 more questions:
1. Availability to have a central dashboard, with generic CM files accessible to everybody along with key contact people?
2. Send mass communication during emergency?

**Comment by mihikagulhane** [comment]
For the above 2 questions, we can achieve this if we can assign a group of people at a time to a particular incident like a DL or group of people stored in a sharepoint list so that for that particular incident they can store generic files and can send mass communication at a go.

**Comment by v-saikirang** [comment]
Hi @mihikagulhane,

You can use the Teams created for the incident to perform the communications only within the team. You can also use "Post Announcement" in Active Dashboard. But this is limited to team members. There is no feature as of now that allows communication to non team members as this app is focused on helping the team working on each incidents.
Unfortunately the app does not support exactly what you are asking for. But we will try think around this in the future. Thanks for the feedback. 

Thanks.

**Comment by mihikagulhane** [comment]
Okay thanks for the input.
