### ISSUE TITLE
PlanningItemsSelected icon not showing

### ISSUE THREAD

**Issue by Robbayly** [OfficeDev/microsoft-teams-emergency-operations-center#24]
https://<site>.azurewebsites.net/static/media/PlanningItemsSelected.b8234f22.svg
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
![2022-05-27 09_50_09-Window](https://user-images.githubusercontent.com/25297019/170602012-3e900756-69bd-4e23-a125-cac97d2da723.png)
"

**Comment by v-ashrirao** [comment]
@Robbayly, 
Thanks for reporting this.
Please allow us some time. We will get back to you ASAP.

**Comment by v-ashrirao** [comment]
@Robbayly, Thank you for your patience. We are still analyzing the root cause of this issue. We will get back to you once we have updates regarding this.

**Comment by Robbayly** [comment]
Hi Team,

Our Azure admin has refreshed and we have the new version - 16.13, however even after an hour and repeated refresh of tab, the image is still not loading in web or desktop app.

https://<appname>.azurewebsites.net/static/media/PlanningItemsSelected.b8234f22.svg
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Thanks
Rob

**Comment by v-ashrirao** [comment]
@Robbayly, Just to understand, 
Can you please confirm, after restarting the App Service deployment was successful or not?
You can validate this by clicking logs from deployment center. Status of sync should be Success(Active).
![image](https://user-images.githubusercontent.com/100257227/172523398-8f01a086-d54b-4f4f-b8f2-4076b127cf3f.png)

**Comment by Robbayly** [comment]
The admin checked the log and advised that the deployment had failed. It has been re-run successfully, and the icon is now displaying. 

Thanks you for your assistance.
