### ISSUE TITLE
Query on Deployment Guide

### ISSUE THREAD

**Issue by salviroshan89** [OfficeDev/microsoft-teams-emergency-operations-center#241]
Hi team on the step 10 i.e. [Deploy “NotifyToTeams” Extension in SharePoint](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#10-deploy-notifytoteams-extension-in-sharepoint), we havent deployed the package to our tenant app catalog instead we have uploaded it to a site collection app catalogue of the TEOC SharePoint site. As we didnt wanted to make the extension deployed on all sites in our tenant. Could you suggest if that is right approach and there were no explanation on the step 10 why extension needs to be deployed on all sites in tenant. Could you elaborate on that too?

**Comment by v-saikirang** [comment]
Hi @salviroshan89 ,

Can you please let us know if this feature is working for you.

Thanks.

**Comment by v-ajaysahu** [comment]
@salviroshan89 ,
The "NotifyToTeams" extension is a List View Command set designed to enable users to select an item, such as a published article, and notify the Announcement channel in Teams. This feature is exclusively available for Teams created via the TEOC app, hence this extension needs to be deployed to all the sites.
I hope I've answered your query.
