### ISSUE TITLE
Fails to Install due to changes in PnP Management Shell

### ISSUE THREAD

**Issue by erikhedges** [OfficeDev/microsoft-teams-emergency-operations-center#242]
Since PnP Management Shell has been deleted from Entra as of 9 Sept 2024, how do we go forward to deploy Teams EOC? See issue [here ](https://github.com/pnp/powershell/issues/4250).

**Comment by v-ajaysahu** [comment]
@erikhedges , thanks for reporting this issue.
We're aware of the issue within the PNP Management Shell and are currently investigating it. Rest assured; we will update you as soon as possible.

**Comment by v-ajaysahu** [comment]
@erikhedges ,
The issue has been resolved in the latest 3.2 release. Please refer to the [wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide) for more details. As this matter has been addressed with the new update, I'm closing this issue. Should you have any further questions or concerns, don't hesitate to post your comments here.
