### ISSUE TITLE
Missing Manage and New Incident Buttons

### ISSUE THREAD

**Issue by asdraper27** [OfficeDev/microsoft-teams-emergency-operations-center#243]
After updating to 3.1, TEOC interface in Teams is missing Manage and New Incident buttons.  The user account I am logged into with is an owner on the VEOC App in Azure

**Comment by v-saikirang** [comment]
Hi @asdraper27,

Thanks for reaching out to us. 

Please check SP list "TEOC-Config" if the "EnableRoles" is "True". If yes, change it to "False" and try again.
![image](https://github.com/user-attachments/assets/fbfbb0f3-4f66-4d4c-8c9c-5d922affb9ad)

Thanks.

**Comment by asdraper27** [comment]
That did the trick, thank you!
