### ISSUE TITLE
Cannot add to a Team/Channel

### ISSUE THREAD

**Issue by clarkec2** [OfficeDev/microsoft-teams-emergency-operations-center#244]
When attempting to add the app to a Team via the app we are met with a white screen and the save button is unavailable. I believe this is due to the manifest, could you please direct me where to go to ensure the configurable tab is setup properly? 
![image](https://github.com/user-attachments/assets/2579af66-ecb6-486c-9375-a8eec85c47ce)

**Comment by clarkec2** [comment]
Same issue, the only way I can add the app to a team is through powershell, opening the app works in teams I have the command against. If you try to add it to a new team or open it without adding it via powershell we are met with the screenshot I provided.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

Sorry but i am little confused. Is the app working as expected without adding it to any Teams when directly opened from "Apps" section.
Thanks.

**Comment by clarkec2** [comment]
Yes the app works perfectly fine "on its own".  Again, when you try to add it to a Team that white space page pops up and you cant "save" it.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

The app is mainly designed to act as stand alone app. We are also adding this app as a tab in the General channel of the Incident Teams created dynamically. But this will open the Active Bridge of the incident which opened from within incident teams.

So now that you have mentioned you were able to add the app to a Teams through power shell what do you see in the tab. Can you please share a screenshot.
Thanks.

**Comment by clarkec2** [comment]
This what is shown when adding it to channel for pinning...
![image](https://github.com/user-attachments/assets/098f7357-5ea5-4d8a-b6f5-37b1712208d3)

After clicking the pin to team button...
![image](https://github.com/user-attachments/assets/add4f16c-aa8c-4b48-ad46-2e8c91f25cd2)

From the documentation...
![image](https://github.com/user-attachments/assets/414fb78d-49f0-45c4-9cf3-991acfcb5201)

Which isnt working.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

Sorry if iam getting it wrong but in one of your previous messages you mentioned its working fine when added through power shell. Can you please share a screenshot of the app working when added as tab in channel.

Thanks.

**Comment by clarkec2** [comment]
I literally just did that, see the previous screenshots. This app is used by non techs without admin access and needs to be added as a tab to channels and teams at their discretion, they dont have access to powershell to add and remove the app as needed. Your documentation states that the app can be "added as a tab" which in our env currently it cannot, looking over this it appears to be from the manifest settings around that configurable tab. 

Again....
![image](https://github.com/user-attachments/assets/320f3ebb-7302-4ffe-876e-baab028d75d0)


Read the issue and stop trying to interpret what you feel I am trying to say. The app cannot be added as a tab to a team/channel, we are met with the previous screen shots where it wont allow us to save.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

We have identified the issue and working on a fix. We will try to release the fix ASAP.
Thanks.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

We have released a hot fix for the fix. You should now be able to add the app as a tab to a channel. Please upgrade your app as per the upgrade instructions in the Wiki depending on your current version.

Thanks for your feedback. I am closing this ticket for now. Please feel free to re open the ticket in case of any issues.

Thanks.
