### ISSUE TITLE
What is the function of the [basename]simpleauth Azure Web App

### ISSUE THREAD

**Issue by SemBurendo** [OfficeDev/microsoft-teams-emergency-operations-center#245]
Does anyone know the function of the [basename]simpleauth Azure web app deployed as part of the solution. The solution architecture does not include this site nor is it referenced by the documentation. As far as I can see it has no code deployed to it just some app settings.  Is it required for the normal functioning of the solution and what is it's function? Thanks.

**Comment by v-ajaysahu** [comment]
@SemBurendo , thanks for asking this.
The simpleauth Azure web app is specifically designed for authentication, featuring a Client Id and Client Secret for the app's authentication process, along with an Identifier URI. These details are available under Environment Variables.

**Comment by SemBurendo** [comment]
@v-ajaysahu  thanks for the reply. I noticed the simpleauth site uses a user-assigned identity but I can't see any role assignments for the identity. What is this identity used to access?
