### ISSUE TITLE
Unable to Provision Error

### ISSUE THREAD

**Issue by fajr365** [OfficeDev/microsoft-teams-emergency-operations-center#246]
I am receiving the following error when running the EOC-Provision script.
AADSTS700016: Application with identifier '31359c7f-bd7e-475c-86db-fdb8c937548e' was not found in the directory ...
I ran thru all the troubleshooting steps however it still fails.
Please advise.

Thank you.

**Comment by v-saikirang** [comment]
Hi @fajr365,

Thanks for reaching out to us.

This is a known issue caused due changes made by MS  in PNP Management shell as described in  the blog: https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/
We are currently working on the modifications in the power shell script as mentioned in the blog. This will be part of our next release in a week or so. You can alternatively try to implement the changes as per the blog your self and complete the provisioning process. I am closing this ticket for now. Please watch out for next version in this repo.
Thanks.
