### ISSUE TITLE
Getting a 'You do not have permission to view this directory or page error' on the TEOC site

### ISSUE THREAD

**Issue by SemBurendo** [OfficeDev/microsoft-teams-emergency-operations-center#248]
I had TEOC deployed and working ok and then suddenly getting the error message below. The error disappeared temporarily when I restarted the site yesterday but it's back again this morning.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/1864ee79-870f-4d38-9774-7ad0e06e8f4e">

**Comment by v-ajaysahu** [comment]
@SemBurendo , thanks for reporting this issue.
Could you kindly verify if the Azure App Service is functioning properly? Additionally, if there are no issues with the App Service, could you share the console logs and network traces?

**Comment by SemBurendo** [comment]
@v-ajaysahu I have found and resolved the issue, thanks
