### ISSUE TITLE
Teams EOC App crashes once the Select Role dropdown is selected

### ISSUE THREAD

**Issue by mnferozdc** [OfficeDev/microsoft-teams-emergency-operations-center#249]
While creating a new Incident, the _Select Role_ dropdown shows the values that are stored in the backend from SharePoint such as:

![image](https://github.com/user-attachments/assets/8fdb7e39-7c99-4d3a-b254-74bdf075dce7)

However, once a value is clicked, the App immediately crashes and results in a blank screen such as:

![image](https://github.com/user-attachments/assets/ca95a038-30a7-4306-bca3-896f384e1795)

We were able to triage this a little further by launching the Teams App using a Browser and then launching the Developer Tools section. As such, we noticed the following:

![image](https://github.com/user-attachments/assets/cf18ded3-0d43-415a-bb4a-68bbe9a19997)

It appears like the code is crashing due to the following exception:

i.e., **_Cannot read properties of undefined .... at z.onRoleChange_**

Can some insights be shared as to how best we can try to troubleshoot and triage this exception, please? Thanks!

**Comment by v-ajaysahu** [comment]
@mnferozdc , Thank you for bringing this issue to our attention.
Could you kindly launch Teams via a web browser and activate the developer tool? Afterward, please access the TEOC app and attempt to replicate the issue. It would be greatly helpful if you could then provide us with the console logs and network traces to troubleshoot the issue.
