### ISSUE TITLE
User Role Rights?

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#252]
Can you provide documentation outlining the specific rights and permissions associated with each user role within EOC?

Specifically, I am looking for information on how role-based access affects the ability to make changes during an incident, such as when there is a need to update staff assignments or grant executive or general staff members the authority to perform critical updates to the incident management system. In some cases we need to add users on the fly or even remove users but the assigned Incident Commander or Secondary Incident Commander might not always be available to perform those edits. 

Also is there anyway we can edit or create new roles potentially with custom rights?

**Comment by v-saikirang** [comment]
Hi @BCG-cmori,

As of now we have very basic role based access configuration options in TEOC. You can refer to the wiki for "Enable Role-Based access" under [Manage Options](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#manage-options) section.
We would like to expand this some time in future though depending on use cases and feasibility.

Also is there anyway we can edit or create new roles potentially with custom rights? - You can add new roles from TEOC-RoleAssignments SP list but its not tied to any custom rights. We have however added a new feature in latest v3.2 under Admin Settings to give a role access to Edit incidents along with incident commander and Secondary incident commander.

Please let us know if you need more information. 

Thanks.
