### ISSUE TITLE
Steps to Integrate Azure Maps with TEOC

### ISSUE THREAD

**Issue by lowelllivingston** [OfficeDev/microsoft-teams-emergency-operations-center#253]
Steps to Integrate Azure Maps with TEOC

Anyone have any experience with this or can provide any guidance?

Stuck on Step number 3 & 4

Overview:
The Microsoft Teams Emergency Operations Center (TEOC) is a solution designed to help organizations manage and respond to incidents by centralizing communications and resources. Azure Maps brings advanced mapping and location services into this platform, enabling real-time data and geographic insights, such as monitoring emergency events, logistics, and the deployment of resources.
Steps to Integrate Azure Maps with TEOC:
1. Setup Microsoft Teams Emergency Operations Center (TEOC):
	• Ensure you have TEOC installed in your Microsoft Teams environment.
	• Follow the [TEOC installation guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center) to configure the TEOC environment in Teams.
	• Configure incident management workflows and custom actions to suit your organization’s needs.
2. Get Azure Maps API Key:
	• Sign in to the Azure Portal and create an Azure Maps account (if you don’t have one).
	• Go to Azure Maps Resource in your resource group.
	• Copy the Primary Key and Secondary Key from the Keys section.
3. Set Up Azure Maps for Enterprise:
	• Navigate to your Azure Maps account in the Azure portal.
	• Enable APIs and services such as Route, Search, Traffic, Weather, etc., depending on your emergency management needs.
	• Create a Custom Map Layer if needed to overlay specific data (e.g., hazardous zones, critical infrastructure).
4. Configure TEOC for Azure Maps Integration:
	• Access the TEOC configuration within Teams.
	• In the TEOC dashboard or control panel, there will be settings for third-party integrations, including mapping tools.
	• Add your Azure Maps API key to the TEOC configuration, and configure it to display map tiles and data visualizations for locations relevant to your incidents.
5. Customize Map Overlays and Incident Data:
	• Use Azure Maps to create custom layers for displaying real-time data such as traffic, weather, or evacuation zones.
	• Ensure these layers are relevant to your organization's emergency scenarios.
	• If you're managing multiple locations, leverage the Search and Routing APIs to plan resource deployment and evacuation routes.
6. Visualize and Manage Data in Teams:
	• After integration, you will see Azure Maps embedded into the TEOC Teams interface.
	• Use this interface to:
		○ View real-time maps of incidents.
		○ Track emergency vehicles or personnel.
		○ Monitor traffic and weather conditions.
		○ Display custom zones or geofenced areas for your operations.
7. Use Incident Reporting and Location Sharing:
	• Through TEOC, incident reports from field personnel or automated systems can now include geolocation data.
	• Field teams can report their locations via mobile devices or other GPS-enabled devices, and it will show up on Azure Maps within the TEOC dashboard.
8. Testing and Validation:
	• Before going live, test the integration by simulating an emergency incident.
	• Ensure all stakeholders (emergency teams, leadership) can view and use Azure Maps features within TEOC.
9. Security Considerations:
	• Ensure that only authorized personnel have access to TEOC and its integrated Azure Maps functions.
	• Set appropriate access controls in Azure for the Maps service, especially when handling sensitive locations or data.

**Comment by v-saikirang** [comment]
Hi @lowelllivingston,

May I know where did you find these instructions to integrate Azure Maps with TEOC.

As of now we have instructions only to integrate with Bing Maps with TEOC. So if you already have a Bing MAPs key generated it would work with TEOC. Now that Bing maps migrated to Azure Maps we have not yet tested with Azure Maps key. That is something we are planning to do in of our future releases. But we had couple customers mentioning Azure Map key worked to an extent with TEOC. But we have not yet validated it. 

our [Wiki ](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#incidents-map-viewer)has instructions to integrate only Bings Map key.

Please let us know if you need more information.

Thanks.

**Comment by lowelllivingston** [comment]
Hello & thanks for your response - the instructions came from ChatGPT - I followed your wiki and when I login to https://www.bingmapsportal.com/Account/Register I see that they are no longer onboarding new customers so I can't expose/obxtain an Account, My Keys value :(

Thoughts?

![image](https://github.com/user-attachments/assets/f6937b96-3c08-44bb-8a81-cf5f33e7f699)

**Comment by v-saikirang** [comment]
Hi @lowelllivingston,

Yes, you will not be able to create Bings api key any more. As i mentioned we are currently looking in to possibility of migrating to Azure Maps in TEOC. You can still try creating azure maps key instead as one of the users mentioned it was working for them to an extent. If not, please watch out for any updates in the future for Azure Maps integration.

Thanks for your feedback.
