### ISSUE TITLE
Setup TEOC and can see in Teams but when creating a new Incident issue with "location is required"

### ISSUE THREAD

**Issue by lowelllivingston** [OfficeDev/microsoft-teams-emergency-operations-center#254]
Setup TEOC and can see in Teams but when creating a new Incident issue with "location is required" - it says location is required but we can't add anything to that field.
It won't let use Add/create new incident
Is there a solution?
[teoc_2024-09-23_10-43-05.pdf](https://github.com/user-attachments/files/17101649/teoc_2024-09-23_10-43-05.pdf)

**Comment by v-saikirang** [comment]
Hi @lowelllivingston,

Thanks for reaching out to us.

Can you please confirm if you have provided the office 365 exchange permission as mentioned in the [wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#6-add-permissions-for-office-365-exchange-online).

For any further issues please share a screenshot directly instead of an attachment.
Thanks.

Thanks.

**Comment by lowelllivingston** [comment]
![image](https://github.com/user-attachments/assets/be9657d6-3c08-47c1-a5c4-b957835b88aa)
Permission is set for Microsoft Graph - Calendars.Read and Granted consent. We are on 3.1 - do we need to update to 3.2? Seems powershell approach has changed is their updated documentation for 3.1 to 3.2 and might this help? - thanks for your reply

**Comment by v-saikirang** [comment]
Hi @lowelllivingston,

The permission should be from Office 365 exchange online as shown in wiki. Please add the permission as per the steps.

If you have already set up SharePoint site then power shell changes are not applicable for you.
We advise you still upgrade to 3.2 so you have the latest features as mentioned in the release notes. You can follow the upgrade wiki.

Thanks.

**Comment by lowelllivingston** [comment]
Thanks! I found it and added - should this then fix issue for location is required? 
![image](https://github.com/user-attachments/assets/3dd6bea8-0c17-4e08-91b7-c146dda42044)

Can you send wiki steps I need to follow to update from 3.1 to 3.2 please?

**Comment by v-saikirang** [comment]
Hi @lowelllivingston,

After adding the permission you should now be able to select location.

Here is the wiki link: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version

Thanks.

**Comment by lowelllivingston** [comment]
I figured out - Just went to Teams and deleted

**Comment by lowelllivingston** [comment]
not sure if that was the right thing to do - still see it in teams - may take some time to reflect removal from sharepoint/teams

**Comment by v-saikirang** [comment]
Hi @lowelllivingston ,

To remove the test data you need to delete the teams and the list items from share point. I hope this clarifies. I am closing this ticket. Please let us know if you have any issues.
Thanks.
