### ISSUE TITLE
Connect-PnPOnline -Url $TenantURL -Interactive: Specified method is not supported.

### ISSUE THREAD

**Issue by maksudcs** [OfficeDev/microsoft-teams-emergency-operations-center#255]
Hey,

i am trying to deploy TEOC app in my tenant through PowerShell but getting following error:

PS D:\Projects\People\****\Source\****\Deployment\provisioning> .\EOC-Provision.ps1
Enter site template XML schema file path: D:\Projects\People\****\Source\****\Deployment\provisioning\EOC-SiteTemplate.xml
D:\Projects\People\****\Source\****\Deployment\provisioning\EOC-SiteTemplate.xml
tenant App Id for authentication. As of September 9th, 2024 this option is not available anymore. Refer to https://pnp.github.io/powershell/articles/registerapplication.html on how to register your own application.
Connect-PnPOnline: D:\Projects\People\Daniel\Source\SEOC\Deployment\provisioning\EOC-Provision.ps1:32:1
Line |
  32 |  Connect-PnPOnline -Url $TenantURL -Interactive
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Specified method is not supported.
Checking if site already exists at /sites/TEstEOC
Site doesn't exist, creating new site at /sites/TEstEOC
https://csiroc.sharepoint.com/sites/TEstEOC
WARNING: Connecting with -Interactive used the PnP Management Shell multi-tenant App Id for authentication. As of September 9th, 2024 this option is not available anymore. Refer to https://pnp.github.io/powershell/articles/registerapplication.html on how to register your own application.

Error Message:  Specified method is not supported.

below my PnP.PowerShell version:

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   2.12.0                PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAvailableSiteClassification…}

Thanks

**Comment by v-saikirang** [comment]
Hi @maksudcs,

Thanks for reaching out to us.

We have modified the power shell script as part of our new release couple days back. Can you please confirm if you are using the new power shell script. Also please check the deployment guide for pre requisites for running the power shell script.
Thanks.

**Comment by maksudcs** [comment]
Hi @v-saikirang ,  
Thanks for your response. Fantastic , now its working.  
Thanks
