### ISSUE TITLE
New Channels Visible to users by default

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#256]
Is this an easy one for me or you to update?  All the channels created by TEOC are not visible by default.  Can I edit the backend code to make the Visible by default?

**Comment by v-saikirang** [comment]
Hi @tcrobbins4,

We had this turned on earlier but there was an issue with a graph end point which was causing the create channel to fail. So we had to revert it. We will consider this in our future releases based on feasibility.

Thanks for the feedback.
Thanks.

**Comment by malimal99** [comment]
yes, only the General channel seems to show. Since the Announcement channel is hidden, notifications are off by default.
