### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#257]
Can I jump straight to 3.2 from 2.0?  I looked and didn't see anything about that.  Thanks.

**Comment by v-ajaysahu** [comment]
@tcrobbins4, Thank you for highlighting this matter. 
We've outlined the steps for upgrading to the latest version in our wiki. If you're moving from version 2.0 to the newest version, please follow the instructions highlighted under **This step is applicable only if you upgrade the app from 2.0 or older**. For the latest release, adhere to the instructions where no specific versions are mentioned.
I hope this addresses your concern. Should you have further questions or need clarification, feel free to reach out.
