### ISSUE TITLE
Teams Templates - feature request

### ISSUE THREAD

**Issue by ToC-Tthor** [OfficeDev/microsoft-teams-emergency-operations-center#258]
Hello, I am hoping that in a future version we might be able to make and use Teams templates to prebuild teams sites and content that will then get deployed as part of the incident creation process.  Either one base template or the ability to choose a template when deploying the incident.

**Comment by v-saikirang** [comment]
Hi @ToC-Tthor ,

Thanks for your feedback.

We will assess the feasibility and include in our backlog if possible.

Thanks.
