### ISSUE TITLE
Run EOC-TeamFx in localhost

### ISSUE THREAD

**Issue by maksudcs** [OfficeDev/microsoft-teams-emergency-operations-center#261]
Hi,
I hope you are doing well! :)

I’ve been working on the TEOC template, and our organization has specific requirements to add some fields during incident creation, such as categories, sub-types, field names, and customizations in the dashboard.

While the TEOC template provides guidelines for customization, there’s one important thing I’d like to clarify. During development, we need to run the template in our local environment for debugging and testing to ensure everything works as expected before deploying it to our Azure cloud.

However, I’m unsure how to set up and run the TEOC template locally. Could you please provide any guidelines or instructions for this?

Thank you!

**Comment by v-saikirang** [comment]
Hi @maksudcs,

Thanks for reaching out to us.

Please note that we do not provide any support for customization or development needs. However you can refer to the below links for more information on running this project using Teams Toolkit. These links provide details development/setting up of Teams apps using Teams Toolkit. 

https://learn.microsoft.com/en-us/training/paths/m365-teams-toolkit-vsc/
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/install-teams-toolkit?tabs=vscode

Also note that once you customize the app in your tenant you will not be able to receive any new features that we implement in our main git hub repo and we will also not be able to provide any further support in your tenant for the customized version. 

Please let us know if you need more information.

Thanks.

**Comment by maksudcs** [comment]
Thanks, @v-saikirang, for your valuable response.

From your message: **"Also note that once you customize the app in your tenant, you will not be able to receive any new features that we implement in our main GitHub repo, and we will also not be able to provide further support in your tenant for the customized version."**

I understand that each organization may have different titles, values for incident creation, dashboard grid items, or columns, which can vary from company to company. 

**How can we customize the TEOC app in such a way that we can still receive updates for the TEOC app?**

Is there any guideline or documentation available for this?

Thanks again for your valuable input.

**Comment by v-saikirang** [comment]
Hi @maksudcs,

There are few things like App Title you can configure from Admin Settings screen. You can also try to modify master data items in the SP lists as long as it's not conflicting with core functionalities of the app. Any changes to the code will be considered as customization and once you create you own custom repo we will not be able to provide any inputs. For any release of new features, you can check the code base and manually copy the required code to your repo.

Thanks.

**Comment by maksudcs** [comment]
It sounds like we're feeling limited by the app's support and customization options. For small organizations, a straightforward solution can be helpful, but it's frustrating when we need more flexibility.
