### ISSUE TITLE
How to add Secondary Incident Commander

### ISSUE THREAD

**Issue by GitRomney** [OfficeDev/microsoft-teams-emergency-operations-center#262]
Looking through old support cases, I see that Incident Commander and Secondary Incident Commander are the two roles with rights to edit an incident. The field to add an Incident Commander allows only one user to be added and there is no "Role" for "Secondary Incident Commander. Is the person who creates the incident considered the "Secondary Incident Commander"? Am confused about what the "Secondary Incident Commander" is and how to add one. Thank you.

**Comment by v-saikirang** [comment]
Hi @GitRomney,

Thanks for reaching out to us.

"Secondary Incident Commander" is one of the default roles that you select from the Roles dropdown list and assign users.
Hope this clarifies your question.

![image](https://github.com/user-attachments/assets/04c76950-33a2-409a-9696-50d01bdce721)

**Comment by GitRomney** [comment]
We don't have that role option. In fact, we have different roles than you are showing. See image.

![image](https://github.com/user-attachments/assets/9a1060aa-1ca3-48e9-ae58-0d9f47cf4bac)

**Comment by GitRomney** [comment]
These are all of the roles in 
https://[TENANT NAME].sharepoint.com/sites/[SITE NAME]/Lists/TEOC-RoleAssignments/AllItems.aspx

![image](https://github.com/user-attachments/assets/c7c756df-6c60-409e-83a5-59523c282ae5)
