### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by Piranhapr** [OfficeDev/microsoft-teams-emergency-operations-center#265]
Is there an option that when a Bridge is activated, the Bridge automatically calls ALL participants of that incident?

**Comment by v-ajaysahu** [comment]
@Piranhapr , thank you for reaching out with your question. 
Upon activating Bridge, a notification will be sent to all users involved in the incident, but it's important to note that Bridge does not initiate calls to all participants. 
Reference Link: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#incident-details-dashboard
I trust this clarifies your query. While I'm closing this request, please feel free to post any further questions on the same issue if needed.

**Comment by Piranhapr** [comment]
Thanks for your prompt response.  I got that the Bridge does not initiate calls to all participants, but do you have any suggestions, or is there is a way we can force that?
Thanks.

**Comment by v-ajaysahu** [comment]
@Piranhapr ,
At present, the Teams JS API doesn't support automatically adding all participants to a call, but we plan to incorporate this feature if future updates allow it. As a temporary solution, I suggest manually inviting users to join the call through the participant's section.
