### ISSUE TITLE
Compatibility with Azure Maps/Bing Maps deprecated.

### ISSUE THREAD

**Issue by dannemillerncom** [OfficeDev/microsoft-teams-emergency-operations-center#266]
Is there currently anyway to use Azure Maps or an alternative to Bing Maps?

In the solutions overview it instructs to use a Bing Maps key to get map functionality, however Bing Maps is no longer being supported and new enterprise accounts can not be created, and enterprise services will end on June 30 2025.

**Comment by v-saikirang** [comment]
Hi @dannemillerncom,

Thanks for reaching out to us.

We are currently working on migrating to Azure maps. This should be part of a future release. Please watch out this repo for updates on the next release.

Thanks.

**Comment by dannemillerncom** [comment]
Thank you.
