### ISSUE TITLE
How to add Secondary Incident Commander (Reopening)

### ISSUE THREAD

**Issue by GitRomney** [OfficeDev/microsoft-teams-emergency-operations-center#267]
You closed my previous support request before it was resolved. (https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/262)

Looking through old support cases, I see that Incident Commander and Secondary Incident Commander are the two roles with rights to edit an incident. The field to add an Incident Commander allows only one user to be added and we do not see a role for "Secondary Incident Commander." You answered that "'Secondary Incident Commander' is one of the default roles that you select from the Roles dropdown list and assign users." Unfortunately, we don't see the roles you pictured in your screenshot.

These are the only roles we see:

![image](https://github.com/user-attachments/assets/23b8a926-12a2-4dfb-aa40-ff2e734c966e)

![image](https://github.com/user-attachments/assets/5fcd4a65-4778-4d93-acf7-a5e11f600cb6)

![image](https://github.com/user-attachments/assets/1aac5ac1-278c-4b1b-a4dc-f7fd09ff38a8)

Do you know why we don't see the roles you mentioned in the previously referenced ticket? Is there a way for us to import more roles? We especially need roles which will allow multiple staff members to edit/update an incident, which I understand the Secondary Incident Commander would be able to do.

We have upgraded to 3.2 and that didn't change the roles.

Thank you in advance for your help.

**Comment by v-saikirang** [comment]
Hi @GitRomney,

Sorry for the misunderstanding.

Based on the screenshots it looks like the values in the SharePoint list have been changed. You can add the new value directly in the SP list. Please check with the person who set up the app or who changed the values in the list based on the list item history.

Please let us know if you need additional information.

Thanks.

**Comment by GitRomney** [comment]
Thank you for your quick response!

I'm the one who set up the app and I didn't change a thing. Looking in the recycle, I see that one of the TEOC users deleted four roles! I've restored them and now they are working.

Thanks again for the help! I'll go ahead and close this request.
