### ISSUE TITLE
Location Field Cannot Filled.

### ISSUE THREAD

**Issue by dannemillerncom** [OfficeDev/microsoft-teams-emergency-operations-center#268]
While trying to create a new incident in Teams the Location field can not be completed preventing the incident from being created. Have attempted address, Lat/Long, city, and states. As soon as I hit enter or click off the field it clears itself.
![image](https://github.com/user-attachments/assets/69ce56ae-6a9b-4599-a2a8-282df2c37dc1)

**Comment by v-saikirang** [comment]
Hi @dannemillerncom,

Thanks for reaching out to us. Please check if you have added the office 365 exchange permission as per the wiki:https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#6-add-permissions-for-office-365-exchange-online

![image](https://github.com/user-attachments/assets/d7a494db-ab13-43e8-a340-bca444e7653c)
Thanks.

**Comment by dannemillerncom** [comment]
Yes that was the issue thank you.
