### ISSUE TITLE
Failed Upgrade from 2.1 to 3.2 

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#269]
Hi - 

I attempted to upgrade from 2.1 to 3.2. However the deployment failed when i performed the sync in the deployment center. I have attached the logs for your review. Please let me know if I did something wrong. 

[failed-logs.txt](https://github.com/user-attachments/files/17331438/failed-logs.txt)

**Comment by v-ajaysahu** [comment]
@BCG-cmori , thank you for bringing this issue to our attention. 
It appears that the GENERATE_SOURCEMAP setting might not have been added to the App Service. For your reference, here is the link with the necessary steps: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#5-add-new-application-setting-generate_sourcemap-in-the-app-service--this-step-is-applicable-only-if-you-upgrade-the-app-from-30-or-older--

**Comment by BCG-cmori** [comment]
Ah thanks I will fix that.
