### ISSUE TITLE
Incidents are being created without an "Incident ID", do not create Teams Channels and can not be edited.

### ISSUE THREAD

**Issue by dannemillerncom** [OfficeDev/microsoft-teams-emergency-operations-center#270]
While making test cases I ran into an issue where incidents where failing to be properly created. Incidents 4 and 5 failed while 6 was successful.  When trying to edit the NaN incidents the page gets stuck in a loading screen.
![image](https://github.com/user-attachments/assets/2398c256-9135-471b-b1d9-fd78c819c8e8)

**Comment by v-ajaysahu** [comment]
@dannemillerncom , thanks for bringing this to our attention.
Could you kindly provide the console logs and network traces? They will assist us in diagnosing the problem. Additionally, could you share the steps needed to replicate this issue?

**Comment by dannemillerncom** [comment]
Sorry for the delay. I am struggling to recreate the issue. When it originally happened I had deleted and restored several test incidents from Sharepoint. Some of them had their Teams channels deleted others hadn't. I have recreated the steps and the issue has no popped back up.

**Comment by v-ajaysahu** [comment]
@dannemillerncom ,
Since the issue cannot be replicated at this moment, I'm going to mark it as resolved. However, if you manage to replicate the problem later, including the steps and logs, feel free to update this thread.
