### ISSUE TITLE
Blank Teams App

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-emergency-operations-center#272]
In the Teams app, see...

![image](https://github.com/user-attachments/assets/2f490a43-6533-4be4-842b-464fb2782c2a)

In the web app trace, I see..

![image](https://github.com/user-attachments/assets/9881c0bf-492f-4fba-9c47-bf2dede6ed60)

**Comment by v-saikirang** [comment]
Hi @malimal99,

Thanks for reaching out to us.

Have you provisioned the SP site. If yes, Can you please share the screenshot of the site along with the URL of the site.

Thanks.

**Comment by malimal99** [comment]
![image](https://github.com/user-attachments/assets/eca946f5-b803-455e-8d89-a31f4911b3bd)

![image](https://github.com/user-attachments/assets/34d2d265-5f1c-4195-b4d8-c2dd1051b319)

**Comment by v-saikirang** [comment]
Thanks for sharing. Can you also please share the console logs from the browser.

Thanks.

**Comment by v-saikirang** [comment]
Thanks. Please allow us some time. We will check and let you know by Monday.
Thanks.

**Comment by malimal99** [comment]
Thanks...I see a mistake I may have made...verifying now.

**Comment by malimal99** [comment]
Question:

In this step "Go to App Registrations page [here](https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps) and select the application (TEOC specific) which you created in step 1. Follow the below steps to set up the authentication for the application."

Do I edit the PnP PowerShell app or the Azure AD TeamsEOCxx app?

@v-saikirang

**Comment by malimal99** [comment]
Hello....I did a fresh install in am up and running. 

I wonder why I had to accept permission for the Teams App the first time I ran it. In the Teams admin center it said all permission were granted for the orf.
