### ISSUE TITLE
Can't provision new incident due to internal Group naming convention

### ISSUE THREAD

**Issue by cll23** [OfficeDev/microsoft-teams-emergency-operations-center#273]
Hi solution team, we have deployed the solution but only one user can provision new incidents.  This user is Global admin, who provisions the solution.  After reviewing relevant logs, we have found that our internal group naming convention required suffix for Teams group names.  Therefore, when users can create SharePoint list items but eventually failed to provisioning Teams site.  Is there a way to accept Teams naming convention policy?  Any insights would be greatly appreciated!

**Comment by v-saikirang** [comment]
Hi @cll23,
Thanks for reaching out to us.

Can you try customizing the Teams Name from Admin settings screen as shown below by changing the order and the modifying the "Prefix" value and see if it works for you:

![image](https://github.com/user-attachments/assets/5f777960-a29f-4c81-bfe4-4c92c27ca1a4)

Thanks.

**Comment by cll23** [comment]
> Hi @cll23, Thanks for reaching out to us.
> 
> Can you try customizing the Teams Name from Admin settings screen as shown below by changing the order and the modifying the "Prefix" value and see if it works for you:
> 
> ![image](https://private-user-images.githubusercontent.com/87538202/378440739-5f777960-a29f-4c81-bfe4-4c92c27ca1a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTkzMDIsIm5iZiI6MTcyOTUxOTAwMiwicGF0aCI6Ii84NzUzODIwMi8zNzg0NDA3MzktNWY3Nzc5NjAtYTI5Zi00YzgxLWJmZTQtNGM5MmMyN2NhMWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEzNTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTc3YTM5Y2E0MTFhYzdlY2M1MDUxNmJjOWE2ZjkwZjg0ZTBkODM5Mjc2N2IyMWNiODE4YmQ0MTVlYWFlMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KxkU1k9nT_K2rnMOLBttyyuPyBcx53Wj0gttQGGZoaQ)
> 
> Thanks.

Hi v-saikirang,

Thank you for providing a possible workaround.  Unfortunately we have tried that trick and doesn't work.  Our group naming policy has a suffix from the creator's department, which is the problem.

Here is our policy:

![policy](https://github.com/user-attachments/assets/cf55b882-7927-436e-8f27-15bb63bbea1d)

Here is the error log from browser network activities.  

![error](https://github.com/user-attachments/assets/6a35549e-a760-4850-99dc-5c71f04f6991)

I can see the attempts and deleted /sites/TEOC/Lists/TEOC-IncidentTransaction items in SharePoint list and no Teams site provisioning activities for users so that's what we think the problem is.  Any other potential solution for this issue you can recommend is really appreciated!  Thank you once again.

**Comment by cll23** [comment]
> Hi @cll23,
> 
> Unfortunately there is no other workaround for the policy in your tenant.
> 
> The only option is to customize the code from your end.
> 
> Thanks.

Hi v-saikirang,

Thanks for your quick response.  In this case, could you please provide some references about which part of the code recommended to customize for solving this issue?  I have asked our developer to review but we are not familiar with this language so any additional documentations or guidance would be greatly appreciated.  Thanks!

**Comment by v-saikirang** [comment]
Hi @cll23,

Customization would require hands on knowledge on teams app development, react and typescript. At this point we are also not sure what code changes are required as it requires some analysis and POCs. Unfortunately we will not be able to support custom versions. 

Thanks.

**Comment by cll23** [comment]
Hi v-saikirang,

Thank you for taking the time to respond to my inquires and for keeping us informed about the situation.  While it's not a supported scenario at the moment, hopefully the solution creators will consider this use case in the future release.  Thanks again!
