### ISSUE TITLE
How to add additional field in incident creation page

### ISSUE THREAD

**Issue by maksudcs** [OfficeDev/microsoft-teams-emergency-operations-center#274]
Hi,

I need to add extra dropdown , how to do this. please check the picture.

![fields](https://github.com/user-attachments/assets/73e6db4a-6140-4d7b-a8cb-0879bb516ae4)

Thanks

**Comment by v-ajaysahu** [comment]
@maksudcs , thank you for bringing this to our attention. 
If you're considering adding more fields, this would require customization. Please be aware that we do not offer support for customization or development. However, you can find more information on how to run this project using the Teams Toolkit by visiting the links below. These resources provide detailed instructions on developing and setting up Teams apps with the Teams Toolkit.
https://learn.microsoft.com/en-us/training/paths/m365-teams-toolkit-vsc/
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals
https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/install-teams-toolkit?tabs=vscode

Additionally, please note that customizing the app within your tenant means you won't receive new features from our main GitHub repository, and we won't be able to offer further support for the customized version in your tenant.
Also, below is the link for basic customization.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Customizations

Please let us know if you need more information.
