### ISSUE TITLE
Deployment Questions

### ISSUE THREAD

**Issue by erikhedges** [OfficeDev/microsoft-teams-emergency-operations-center#275]
In [Setting up Authentication](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-set-up-authentication) under sections 2(ii) and 2(iv) which client ID are we using here? Is it the client ID from step 1, or the client ID from step 2?

For setting up the API App for [Step 2](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#2-register-azure-ad-application) the instructions state "Leave the "Redirect URI" field blank for now." I don't see where we add a redirect URL for this app in later instructions. When I attempt to log in to the app I receive an error "AADSTS500113: No reply address is registered for the application." and I assume it's because of the missing reply URL in this app.

I thought that would be done in [Set up Authentication](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#4-set-up-authentication), but the instructions state to use the application created in Step 1.

I appreciate clarifications.

**Comment by v-ajaysahu** [comment]
@erikhedges , thanks for bringing this to our attention.
Please retrieve the Client ID from the Azure App Registration as outlined in step 2(iv). While step 2(ii) instructs you to leave 'Redirect URI' field blank, rest assured, this detail is addressed in step 4(ii). Also, there's a correction to be made, it should indeed be step 2, not step 1, as mentioned. This error will be corrected. 
I hope this clears up any confusion you might have had.

**Comment by stephanefortin** [comment]
I would like to know if it is only step 4.2 or all of step 4 that we must use the application created in step 2?
