### ISSUE TITLE
What is the best way to add task types to the active dashboard?

### ISSUE THREAD

**Issue by dannemillerncom** [OfficeDev/microsoft-teams-emergency-operations-center#276]
Currently the only option is "To Do," however we are wanting to have tasks for each section of the incident (Planning, logistics, public information etc.) Diving through the code I found the "To Do" reference in `EOC-TeamsFx/tabs/src/common/Constants.ts` on line 100 `export const plannerBucketTitle = "To do";` but checking it's references through different files I'm not sure how I would add more task types.
![image](https://github.com/user-attachments/assets/054f350f-8277-4544-a1dd-9f3b5dc20d24)

**Comment by v-saikirang** [comment]
Hi @dannemillerncom,

Thanks for reaching out to us. We will look in to this and get back to you ASAP. Thanks.

**Comment by v-saikirang** [comment]
Hi @dannemillerncom,
Currently we have only one planner bucket implemented in the standard version. At this moment we do not have enough information on how to add more types and we do not support customization scenarios. But we would like to take your feedback and add it to our backlog and implement in one of our future releases based on feasibility. Thanks.
