### ISSUE TITLE
Error when Fork this repository and define the Forked repository as the "External GIT" inside our Azure Web app "Deployment Center"

### ISSUE THREAD

**Issue by mvcsharepointdev** [OfficeDev/microsoft-teams-emergency-operations-center#279]
We have an Azure App Service >> and inside the "Deployment Center" >> "External GIT" >> i define this repo as the external GIT. and i did the deployment and it went successfully. 

Now I Forked this repo inside another GItHub repo using those steps:-

1) git clone https://github.com/microsoft-teams-operations-center/microsoft-teams-emergency-operations-center.git

2) git remote add upstream https://github.com/OfficeDev/microsoft-teams-emergency-operations-center.git

3) git remote -v
origin  https://github.com/microsoft-teams-operations-center/microsoft-teams-emergency-operations-center.git (fetch)
origin  https://github.com/microsoft-teams-operations-center/microsoft-teams-emergency-operations-center.git (push)
upstream        https://github.com/OfficeDev/microsoft-teams-emergency-operations-center.git (fetch)
upstream        https://github.com/OfficeDev/microsoft-teams-emergency-operations-center.git (push)

4) git fetch upstream

5) git add .
6) git commit -m "Your commit message"
7) git push origin main

So now the Forked repo got the exact code as the original repo (this repo). But when I defined the Forked repo as the external GIT isndie Azure Web App >> and i do a deployment i got this error:-

`
Log Details
Commit ID: 6c8c0020fbffd097889e492386eae6c0ccb590a6

12:45:40 AM
Updating submodules.
12:45:40 AM
Preparing deployment for commit id '6c8c0020fb'.
12:45:40 AM
Running custom deployment command...
12:45:40 AM

Running deployment command...
Show Logs...
12:47:38 AM
Deployment Failed.
Command: deploy.cmd
Restoring npm packages for EOC-TeamsFx (this can take several minutes)
"C:\home\site\repository"
Restoring npm packages for tabs folder (this can take several minutes)
"C:\home\site\repository\EOC-TeamsFx\tabs"
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/abort-controller@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-auth@1.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-client@1.9.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-http-compat@2.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-lro@2.7.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-paging@1.6.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-rest-pipeline@1.16.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-tracing@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/core-util@1.9.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/keyvault-keys@4.8.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/logger@1.1.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@10.2.2',
npm WARN EBADENGINE   required: { node: '14 || >=16.14' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }
npm WARN EBADENGINE }

up to date in 18s

276 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> teamsfx-template-tab@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '@fluentui/react' in 'C:\home\site\repository\EOC-TeamsFx\tabs\src\components'

Failed exitCode=1, command=npm run-script build
An error has occurred during web site deployment.
npm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/abort-controller@2.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-auth@1.7.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-client@1.9.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-http-compat@2.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-lro@2.7.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-paging@1.6.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-rest-pipeline@1.16.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-tracing@1.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/core-util@1.9.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/keyvault-keys@4.8.0',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: '@azure/logger@1.1.2',\r\nnpm WARN EBADENGINE   required: { node: '>=18.0.0' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nnpm WARN EBADENGINE Unsupported engine {\r\nnpm WARN EBADENGINE   package: 'lru-cache@10.2.2',\r\nnpm WARN EBADENGINE   required: { node: '14 || >=16.14' },\r\nnpm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.19.2' }\r\nnpm WARN EBADENGINE }\r\nC:\Program Files (x86)\SiteExtensions\Kudu\103.100930.002\bin\Scripts\starter.cmd deploy.cmd`

So why this is working for the original repo but not for the forked repo?

Thanks

**Comment by v-saikirang** [comment]
Hi @mvcsharepointdev,

Thanks for reaching out to us.

Please allow us some time. We will get back to you ASAP.
Thanks.

**Comment by mvcsharepointdev** [comment]
@v-saikirang ok thanks

**Comment by v-ajaysahu** [comment]
@mvcsharepointdev ,
Given that your repository is a fork, we've observed 22 commits. Please note that we do not offer support for custom modifications. 
This issue will now be closed. However, should you have any questions regarding TEOC, feel free to ask them here.
