### ISSUE TITLE
 blank spaces between the list of Incident Type

### ISSUE THREAD

**Issue by MesiChaka** [OfficeDev/microsoft-teams-emergency-operations-center#280]
Whenever , we select the Incident Type there are blank spaces between the list of Incident Type, How we can resolve the blank spaces between each fields. 
![image](https://github.com/user-attachments/assets/3dee6c47-7980-4222-84ad-ea6f3188cd2c)

**Comment by v-ajaysahu** [comment]
@MesiChaka , thanks for bringing this to our attention.
Could you please verify your current version? The issue has been resolved in the latest release version 3.2. If you're using an older version, kindly update it by following the instructions in this link: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version
