### ISSUE TITLE
on active dashboard the information that was submitted with disappears

### ISSUE THREAD

**Issue by MesiChaka** [OfficeDev/microsoft-teams-emergency-operations-center#282]
When the incident is created without Role assignment, click on active dashboard the information that was submitted with disappears. It doesn't happens frequently but want to know why we are not the seeing which we submitted. We validated the information is stored in SharePoint site. 
![image](https://github.com/user-attachments/assets/58203019-2ee7-4b63-8952-1e00d81b6fe2)

**Comment by v-ajaysahu** [comment]
@MesiChaka , thanks for bringing this to our attention.
Could you please open Teams in your browser, open developer tools in your browser, and launch the TEOC app? Once there, attempt to replicate the issue and share both the console logs and network traces with us. This will help us to troubleshooting efforts.
