### ISSUE TITLE
App Service Tier F1 mentioned in documentation but not available

### ISSUE THREAD

**Issue by lawrence-jeff** [OfficeDev/microsoft-teams-emergency-operations-center#284]
The cost estimates page lists F1/Free tier which is not available in the deployment scripts:
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Cost-Estimates
And per Microsoft rep is also not working/supported if manually configured. This table entry should be removed or the deployment scripts updated

**Comment by v-saikirang** [comment]
Hi @lawrence-jeff,

Thanks for reaching out to us. We will look in to your query and get back to ASAP. Thanks

**Comment by v-ajaysahu** [comment]
@lawrence-jeff ,
Indeed, the F1/ Free tier is unavailable. We'll make sure to update the Cost-Estimates wiki in our upcoming releases.
This issue will now be closed, but if you have any further questions, feel free to ask them here.
