### ISSUE TITLE
Upgrade to version 3.2

### ISSUE THREAD

**Issue by SemBurendo** [OfficeDev/microsoft-teams-emergency-operations-center#285]
Are there instructions for upgrading from older versions to version 3.2?

**Comment by v-saikirang** [comment]
Hi @SemBurendo,

Thanks for reaching out to us.

For upgrade instructions please refer to "Upgrade" section in the " Wiki' of the Git Hub repo.
Thanks.

**Comment by SemBurendo** [comment]
duh, thanks
