### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by stephanefortin** [OfficeDev/microsoft-teams-emergency-operations-center#286]
I would like to know if it is only step 4.2 or all of step 4 that we must use the application created in step 2 instead of 1?

**Comment by v-ajaysahu** [comment]
@stephanefortin , thank you for raising this question.
In the first step, the Client Id is utilized exclusively by PowerShell scripts, while in the second step, it pertains to your app registration. Regarding your question, you should apply the Client Id from Step 2 wherever the Client Id is mentioned after step 2.
I hope this resolves your concern. Although I'm marking this issue as closed, don't hesitate to post any further questions you might have.
