### ISSUE TITLE
Factory reset the Sharepoint (database)?

### ISSUE THREAD

**Issue by tofighi** [OfficeDev/microsoft-teams-emergency-operations-center#287]
If an admin mistakenly deleted or renamed SharePoint lists, is there a way to restore the TEOC to its original state or redeploy it with minimal effort? Is there any option to revert the changes?
When I click on create incident it gets stuck, it seems something is missing
<img width="1212" alt="Screenshot 2024-11-08 at 4 30 48 PM" src="https://github.com/user-attachments/assets/0d430c4a-3b5c-4814-8bd0-f2f79252c9ba">

**Comment by v-saikirang** [comment]
Hi @tofighi,

Thanks for reaching out to us.

If a list is deleted, the admin can refresh the app and the list will be re created on load.

If a list is renamed you can try reverting the change and or deleting the list so it will be created again as per above logic. 

Please let me know if you need more information.
Thanks.
