### ISSUE TITLE
Create Shared Channels in Template

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-emergency-operations-center#289]
Can you add the ability to create Shared Channels by default?

Thanks.

**Comment by v-ajaysahu** [comment]
@malimal99 , Thank you for raising that question. 
When you are either creating or editing an incident, you have the option to include channels. 
I hope this addresses your concern.
![image](https://github.com/user-attachments/assets/44748bb3-a625-4aad-8683-507479f42171)

**Comment by malimal99** [comment]
Thank you, but this only creates standard or Private channels. I don't see a way to create a shared channel during the creation.

**Comment by v-saikirang** [comment]
Hi @malimal99,

Currently we do not have the ability to create shared channels. We will check the feasibility and  try to implement this in future. 
Thanks for your feedback.
