### ISSUE TITLE
Channels Hidden and No notifications

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-emergency-operations-center#290]
I saw in another post you all reverted the code to show all channels by default.

Hidden channels seem to have notifications turned off by default. This makes the Announcement channel useless. 

Is there a way to have it visible or the notifications turned on by default?

**Comment by v-saikirang** [comment]
Hi @malimal99,

We checked this with "Teams/graph" team and they confirmed this behavior is by design and cannot be changed at the moment. We may consider this in future depending on any changes coming to the respective APIs.

Thanks.

**Comment by malimal99** [comment]
Thanks for checking.
