### ISSUE TITLE
Added app but stuck at login?. 

### ISSUE THREAD

**Issue by CiaranSuntera** [OfficeDev/microsoft-teams-emergency-operations-center#296]
Good Morning, 

I've completed the steps and "Added the app" to teams but stuck at this page. Clicking login does nothing. 
![Screenshot 2024-11-25 091725](https://github.com/user-attachments/assets/fc4f84b6-473b-4b00-9ca9-9daf258ac316)

Would appreciate any help :) 

Many thanks, 

Ciaran

**Comment by v-ajaysahu** [comment]
@CiaranSuntera , thank you for reporting this issue.
Please verify if you have entered the correct Client Id and Client Secret during deployment. Ensure that the Client Id is the same in the Teams Manifest file. Also, check if the Base resource name is in uppercase. To confirm, navigate to the Azure Resource group, click on deployment, then select "Microsoft.template" and review the input section to verify the Client Id and Base resource name.
Additionally, open Teams in a browser and access the developer tools. Keep the developer tools open, then access the TEOC app and try to reproduce the issue. Please share the Console log, network traces and Teams Manifest file which you uploaded to Teams Admin center.

**Comment by CiaranSuntera** [comment]
Thank you for your swift reply!

I’ve check and it would seem the IDs are correct in the Inputs, and all is lower case:


Inputs Page:
***@***.***

App Registration Page:

***@***.***



I’ve noted the below error on the on deployment if that has any effect.
***@***.***

Kind Regards,

Ci

CIARÁN CLARKE
IT Engineer, Suntera Global
T +44 1624 682255 // M +44 7624 476139
Email: ***@***.******@***.***>
Website<https://www.suntera.com/> // My LinkedIn<https://www.linkedin.com/in/daniel-bryans-8593a416/> // Suntera LinkedIn
<https://www.linkedin.com/company/67739595/>
Suntera Group Limited, a company registered in the Isle of Man (001262V) at Peveril Buildings, Peveril Square, Douglas, Isle of Man, IM99 1RZ. A member of the Suntera Global group of companies. This email is confidential. For full details of limitations on the use of this email, other companies within the group, additional contact and regulatory details, your data rights and other useful information please visit our website<https://www.suntera.com/legal-and-regulatory>.
***@***.***<https://www.suntera.com/?utm_campaign=SG24_Suntera%20Global&utm_source=Outlook&utm_medium=Outlook%20Signature%20Banner&utm_content=Outlook%20Signature%20Banner%20-%20Global%204>

**Comment by v-ajaysahu** [comment]
@CiaranSuntera ,
Since your response was via email, we couldn't view the details. Could you please respond directly on GitHub so we can access the shared information? Additionally, please provide the console logs and network traces as mentioned in the previous comments.

**Comment by v-ajaysahu** [comment]
@CiaranSuntera ,
Thank you for providing the logs and screenshot. Upon review, we identified that the Web Application Info resource URL in the Teams Manifest file is incorrect. It should be "`api://<<appDomain>>/<<clientId>>`". In your case, the app domain is `suntera-eoc.azurewebsites.net`, and you need to add the client ID. Kindly follow the instructions provided in the link below and subsequently upload the Team App package to Teams.
https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#7-create-the-teams-app-packages

<img width="830" alt="image" src="https://github.com/user-attachments/assets/4fe6c809-16f8-4fc2-abc2-1b3547244c84">
