### ISSUE TITLE
Issue with Adding Sharepoint Extension.

### ISSUE THREAD

**Issue by fajr365** [OfficeDev/microsoft-teams-emergency-operations-center#297]
When adding the sharepoint App, the documentation seems to be out of date for the new sharepoint. In the final step "do you trust eoc-extention..." New sharepoint has 2 options
"Only enable this app" and "Enable this app and add it to all sites"
What is the correct choice?

**Comment by v-ajaysahu** [comment]
@fajr365 , thank you for bringing this to our attention.
We will update our documentation in the upcoming releases. The correct option will be "Enable this app and add it to all sites".
I hope this clarifies your query. If you have any further questions or issues, please feel free to post here.
