### ISSUE TITLE
An error has occurred, please try to create your incident again

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-emergency-operations-center#301]
We are receiving the "An error has occurred, please try to create your incident again" when creating an incident. It was working fine for a while.

I researched past issues, but this one seems a little different.

Network and Console logs attached.

[teams.microsoft.com.zip](https://github.com/user-attachments/files/18029157/teams.microsoft.com.zip)

**Comment by v-ajaysahu** [comment]
@malimal99 , thanks for bringing this to our attention.
After reviewing the shared logs, it appears that the issue occurs during the creation of the Incident, as it fails to add items to the "TEOC-IncidentTransaction" List.
Could you please confirm if the provision of the Site was successful, or if it was created manually? Additionally, please check if the List Title has been updated, and if so, revert it to "TEOC-IncidentTransaction".

![image](https://github.com/user-attachments/assets/e5fd52cf-8cf9-4245-92a4-e730ec39c7ce)

**Comment by malimal99** [comment]
Thank you for the review..

We were able to create incidents prior to this issue..The site was provisioned successfully.

I will review you other troubleshooting steps and report back. I have suspicion someone may have messed with that list.

**Comment by v-ajaysahu** [comment]
@malimal99 ,
This is a gentle reminder.
Could you please confirm if you are able to proceed?

**Comment by malimal99** [comment]
Hello, I checked the list name and it looks fine. I have taken some screenshots.  I am also running an audit on the site now.

![Screenshot 2024-12-18 091414](https://github.com/user-attachments/assets/89581855-8622-45b5-adcc-ddcaf77a79e7)
![Screenshot 2024-12-18 090952](https://github.com/user-attachments/assets/3afbac5a-3c5f-413c-b143-20f276390d82)
![Screenshot 2024-12-18 090040](https://github.com/user-attachments/assets/e20d5cfc-b15a-4669-813b-d7fedf174919)

**Comment by malimal99** [comment]
I have an audit but don't see any changes after the 10th. I don't want to upload because there may be sensitive data.

**Comment by v-ajaysahu** [comment]
@malimal99 ,
Could you please confirm the type of Location Column in the "TEOC-IncidentTransaction" List? Additionally, let us know the version you are currently using. When did you start experiencing this issue? If it occurred after an upgrade, please specify the previous version.

**Comment by v-saikirang** [comment]
Hi @malimal99,

Can you please respond to this ticket. As per our internal policy we would have to have to close this ticket in next 2 days if there is no response.
Thanks.

**Comment by malimal99** [comment]
I will respond tomorrow.

**Comment by v-saikirang** [comment]
Hi @malimal99,

Due to our policy, We will have to close this ticket as we didn't get response. Please feel free to open a new issue if you still face any issues.
Thanks.
