### ISSUE TITLE
There was a problem reaching this app

### ISSUE THREAD

**Issue by maksudcs** [OfficeDev/microsoft-teams-emergency-operations-center#302]
Hi ,

I am getting this below error when uploading the resource in teams. 
 Failed to load resource: the server responded with a status of 404 (Not Found).  https://xxxxx.azurewebsites.net/index.html#/tab

![Screenshot 2024-12-09 011338](https://github.com/user-attachments/assets/638375ba-6ec4-40ba-8cbf-b262df0d8235)

Git repo URL is mendatroy when deployment in Azure . below image
![image](https://github.com/user-attachments/assets/73e607c0-635b-4e9e-8917-c5c659000108)

Thanks

**Comment by v-ajaysahu** [comment]
@maksudcs , thanks for bringing this to our attention.
Yes, the Git Repo URL is mandatory and is pre-filled with our repo URL. You only need to update it if you wish to point it to a different repo. 
Could you please confirm whether the deployment in Azure was successful, as it might be related to the issue you are experiencing?

**Comment by maksudcs** [comment]
Thanks @v-ajaysahu 
Now , its successful deployment in Azure & its working but i get another error when creating New incident. please check below error:


![image](https://github.com/user-attachments/assets/613dc89a-ca38-4bc9-87a5-b3de9adcfd6d)


![image](https://github.com/user-attachments/assets/79c708db-d9f0-4faf-8998-d96d2e6e6c92)

Thanks

**Comment by v-ajaysahu** [comment]
@maksudcs ,
It appears that you have removed the TEOC app and attempted reinstallation. When reinstalling, if you have created any Incidents, you must also clean the M365 Group Sites to avoid encountering these errors during Incident creation. 
To resolve this, navigate to the SharePoint Admin center and ensure that any existing Incident M365 groups are permanently deleted, including those in the Deleted Site section.
