### ISSUE TITLE
No Map View

### ISSUE THREAD

**Issue by pdnrescue** [OfficeDev/microsoft-teams-emergency-operations-center#305]
The video mentions a Map View but doesn't exist in my deployment.  How do I enable map viewer?

**Comment by pdnrescue** [comment]
Shouldn't it be next to Incident Details?

![image](https://github.com/user-attachments/assets/e03c0809-754b-4f0c-b1e3-d20a66ac93f7)

**Comment by v-saikirang** [comment]
Hi @pdnrescue,
Thanks for reaching out to us.

Please follow the instruction in the [Wiki](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Solution-Overview#incidents-map-viewer) to be able to use Map Viewer.

Hope this clarifies your question. I am closing this ticket for now but please let us know if you have any further questions. 
Thanks.

**Comment by v-saikirang** [comment]
Hi @pdnrescue,

Currently there is no way to save the zoom to an area. We will check the feasibility in the future. Thanks for your feedback.
