### ISSUE TITLE
Unable to create incidents (group naming convention issue)

### ISSUE THREAD

**Issue by SneilMM** [OfficeDev/microsoft-teams-emergency-operations-center#32]
Hi, installed the app today and encountering same errors as on https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/16

I'm in a non-GCC tenant using the latest version of the app. 

When run in the console the output displayed is:

![image](https://user-images.githubusercontent.com/108598066/177021402-740a19a5-864f-4c29-a320-5f5250c78537.png)

We restrict group creation and have a naming conventions policy for new groups in the tenant. Could I bypass these for the app, or incorporate them somehow?

**Comment by SneilMM** [comment]
If the incident is created by a user with User Admin or Global Admin then they are not subject to the controls / conventions and the incident creation succeeds. Obvious now I think about it but perhaps a note could be added to the documentation?

**Comment by v-ashrirao** [comment]
@SneilMM, Thank you for reporting this. We will add note in documentation to avoid such errors in future.
