### ISSUE TITLE
Deployment issue - Step 5 unblocking provisioning folder

### ISSUE THREAD

**Issue by kkay82** [OfficeDev/microsoft-teams-emergency-operations-center#33]
Trying to deploy the Teams EOC solution. At Step 5 - unblock the deployment script, I run into the following issue:

![image](https://user-images.githubusercontent.com/67169954/179527977-5b4225c0-f313-4910-b886-179d670a80a4.png)

**Comment by v-saikirang** [comment]
Hi @kkay82,

Thanks for reaching out to us. Please allow us some time and we will get back to you on this.

Thanks.

**Comment by kkay82** [comment]
@v-saikirang Disregard, chatted with Josh and all deployed!
