### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by mwceadmin** [OfficeDev/microsoft-teams-emergency-operations-center#34]
Hello, I am running into the same issue as here https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/13. 
I have deployed it few times now. I have added the optional claim to manifest and change it to 2 for AccessTokenAcceptedVersion. I verified spelling, multiple times as well. 

this is what I see in the log 401 Unauthorized  
![image](https://user-images.githubusercontent.com/83797434/180111134-b769c57c-380e-47f5-99ae-8af07f256637.png)

Deployment was successful (green in all spots). all I see in teams is the "login" button but when I click on it it just goes away - the error above is what shows in the logs. 
Please advise.

**Comment by v-prigunasek** [comment]
Hi @mwceadmin,

Thanks for reporting this issue. Could you please provide us the below additional information?
1. Is it a GCC or a Non-GCC tenant?
2. Are you trying to deploy the app using Windows or Mac OS?
3. I see you have mentioned the deployment is successful however this error might pop up if something is missed out in configuration setup. If you could share the screenshots of the Authentication setup step, that would be great for us to review it.

**Comment by mwceadmin** [comment]
It is non-GCC
windows
Happy to share the configuration - however when I got back to it now - it works fine. I didn't change anything since I posted the issue. So not sure, maybe it just needed time. Or maybe there was something going on with Azure/Teams yesterday.  

Thank you for speedy response. But looks like it fixed it self.

**Comment by v-prigunasek** [comment]
Hi @mwceadmin,

Thanks for the confirmation, it is good to hear that you are able to get it working. Yes, yesterday there was a global outage on MS Teams that impacted many users, and it might be a reason too. 

Please let me know whether I can go ahead and close this ticket? Thanks!
