### ISSUE TITLE
Site deployment error

### ISSUE THREAD

**Issue by almaucla** [OfficeDev/microsoft-teams-emergency-operations-center#38]
![image](https://user-images.githubusercontent.com/90116366/184233581-35fe5104-4478-44c9-bce5-1e7a17a156e4.png)

I'm trying to deploy the SP site and gets the bellow error

SD:\microsoft-teams-emergency-operations-center\Deployment\provisioning> .\EOC-Provision.ps1
Please enter site template XML schema file path: D:\microsoft-teams-emergency-operations-center\Deployment\provisioning\EOC-SiteTemplate.xml
D:\microsoft-teams-emergency-operations-center\Deployment\provisioning\EOC-SiteTemplate.xml
Please enter your tenant name: (contoso): amengo
Please enter your tenant admin email: alex@mauclair.com
PnP.PowerShell module found
Checking if site already exists at /sites/TEOCSite
Site doesn't exist, creating new site at /sites/TEOCSite

Error Message:  {"SiteId":"","SiteStatus":3,"SiteUrl":""}

TEOC App Provisioning failed.

**Comment by v-prigunasek** [comment]
Hi @almaucla ,
Can you please check whether you have the sites collection /sites/TEOCSite under Deleted Sites in SharePoint Admin Portal. If so, please delete it from there and then try running the PowerShell script.

Thanks!

**Comment by almaucla** [comment]
![image](https://user-images.githubusercontent.com/90116366/184369446-80d6f826-b097-4f6a-bce1-c2a90be9c755.png)

Hi Priya

this was the first message I received. I had the double quote in the path. so when I retried I got the error mentioned earlier. you were spot on. the site was in the deleted sites.

thanks for you help. it worked.

**Comment by almaucla** [comment]
I added the double quote because I had a space in the path initially.

**Comment by v-prigunasek** [comment]
Good to know that it worked, @almaucla.
Closing the ticket. Thanks.
