### ISSUE TITLE
EOC Deployment Fails

### ISSUE THREAD

**Issue by dheevar** [OfficeDev/microsoft-teams-emergency-operations-center#39]
Hello, I am trying to deploy the template, but it fails every time. I have tried with multiple Azure subscriptions and tenant and changed the DC location from India to East US but it fails.

It fails with message "Object reference not set to an instance of an object". Detailed message: {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"Object reference not set to an instance of an object."}]}

I am following all the steps mentioned in the deployment guide, but it is still failing.

![image](https://user-images.githubusercontent.com/81696067/187338130-049367d3-5c9f-4cfc-b5ff-7a0caf0c1b7a.png)
![image](https://user-images.githubusercontent.com/81696067/187338143-d8bdbb40-a25f-4e1d-b64e-42539f688aa8.png)
![image](https://user-images.githubusercontent.com/81696067/187338162-51ebef23-3893-4946-a678-844c8f2cc61a.png)

Regards,

dheevar paralkar.

**Comment by v-prigunasek** [comment]
Hi @dheevar ,

Thanks for reporting the issue. We will look into it and get back to you.

Thanks!

**Comment by v-prigunasek** [comment]
Hi @dheevar,

I did look into this error, and it seems to be a known issue with Azure App Service that popped up recently. 
Reference : https://github.com/OfficeDev/TeamsFx/issues/5759

Can you please follow the below workaround to resolve this error?
1.  From the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#2-deploy-to-your-azure-subscription) , Click on "Deploy to Azure" button.
2. Click on Edit template. 
![image](https://user-images.githubusercontent.com/98514691/187418420-dd99c9be-4d09-454a-b357-255a2fe1c6a6.png)
3. Search for **Microsoft.Web/serverfarms** in the template.
4. Add **"properties" : {}**  as shown below under resources (line # 222)

![image](https://user-images.githubusercontent.com/98514691/187419122-537a96d1-fb4c-4c3f-ad8a-5604ab39f77c.png)
5. Click on **Save**.

Then follow remaining steps (from step 4) from the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#2-deploy-to-your-azure-subscription) to proceed with the deployment process.

Please let us know if still see any issues. Thanks!

**Comment by dheevar** [comment]
Hi,

The deployment got successfully completed after making the changes that you suggested. You may go ahead and close the ticket. If there are any other issues that i may encounter, i will let you know. Thanks
