### ISSUE TITLE
SharePoint Site provisioning fails

### ISSUE THREAD

**Issue by dheevar** [OfficeDev/microsoft-teams-emergency-operations-center#41]
Hi,

I am not able to provision the SPO site. Powershell scripts fails with error, File not found. TEOC app provisioning failed.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/81696067/187886173-a9d0df24-8192-4106-a108-df8d9a276d29.png">

screenshot shared. request support on the same

**Comment by v-prigunasek** [comment]
Hi @dheevar ,

I see from the above screenshot, the path to schema file is invalid. Please provide the entire path to the schema file ending with .xml

![image](https://user-images.githubusercontent.com/98514691/187898892-b3f5007d-40eb-4730-8f92-075568d13402.png)

Let me know if you still see any issues. Thanks

**Comment by dheevar** [comment]
hi @v-prigunasek ,

after giving the file path, i was able to successfully deploy the application. currently checking if all features and functionalities are working as per documentation.
