### ISSUE TITLE
Created new incident; Not accessible in Teams list.

### ISSUE THREAD

**Issue by eendrulat** [OfficeDev/microsoft-teams-emergency-operations-center#44]
While testing TEOC on Microsoft's dev tenant, I created a new incident (Incident #54, severe drought) and do not see it in the list of teams I can access .

When I click the incident # link, I get no response. Looking at Console; I see this error when I try to click the link: 
_**_TypeError: Failed to construct 'URL': Invalid URL_**_

![image](https://user-images.githubusercontent.com/527590/188212224-30d5dc48-a240-4c42-a541-6c9a53290981.png)

![image](https://user-images.githubusercontent.com/527590/188212846-30db6b09-d6be-489e-9354-276eae918eb4.png)

**Comment by v-prigunasek** [comment]
Hi Eric,

Please allow me to close the ticket here and we will communicate in email since it is an internal testing issue. Thanks.
