### ISSUE TITLE
README for SPFx extension lacks relevant information

### ISSUE THREAD

**Issue by Josverl** [OfficeDev/microsoft-teams-emergency-operations-center#46]
it would be good to update the below README to align with rest of the repo and remove some of the boilerplate

https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/blob/ce385c737467fa238641efdd090a6c66e3aac95f/EOC-Extensions/README.md

**Comment by v-prigunasek** [comment]
Hi @Josverl,

Any changes to the repo will go with a PR on our planned release date only. We normally add these kinds of requests to our backlog and will try to incorporate those changes in our next upcoming release.
For now, I will keep this ticket open and will close it after our next release. Thanks!

**Comment by v-prigunasek** [comment]
Hi @Josverl ,

The ReadMe file for SPFX extension has been updated in this Repo. Hence closing the ticket. Thanks!
