### ISSUE TITLE
Main webpage still says GA will be July 2022

### ISSUE THREAD

**Issue by npherson** [OfficeDev/microsoft-teams-emergency-operations-center#47]
https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/emergency-operations-center/

![image](https://user-images.githubusercontent.com/22797301/192845018-6605a2f8-5bd4-4bde-a24d-c8c0bfb2f377.png)

**Comment by v-prigunasek** [comment]
Hi @npherson,

Thanks for reporting this here. We will be releasing a version 1.0 of TEOC application in couple of weeks and this warning will be removed by that time.

**Comment by npherson** [comment]
Can the target date on the page be updated in the meantime?

**Comment by Michael-Dahlke** [comment]
When version 1.0 is released, will be it remove the requirement to sideload the app and have it managed as a custom app? Or will it be made available to all Teams tenant organizations through the Teams app store?

**Comment by v-prigunasek** [comment]
Hi @Michael-Dahlke ,

TEOC v1.0 will still be available as custom app and it needs to be deployed through Teams admin center or uploaded in Teams App.

Thanks!

**Comment by v-prigunasek** [comment]
> Can the target date on the page be updated in the meantime?

This will be updated early next week. I will update you once that is done. Thanks!

**Comment by v-prigunasek** [comment]
Hi @npherson,

The information in adoption site has been updated, hence closing this ticket.
https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/emergency-operations-center/
