### ISSUE TITLE
TEOC App GUI Overlay (Incident Form)

### ISSUE THREAD

**Issue by SakwaBunyasi** [OfficeDev/microsoft-teams-emergency-operations-center#48]
1) Is the TEOC App a Power Platform (PowerApp)?
2) Is there a way to build a list in SharePoint which would display on an incident form?

- For Example: Currently the incident form just allows the addition of Users and is set to mandatory.  Is there a way to create a new list for Groups for example to be assigned to the incident form?  Understand that a corresponding security group would need to be made available in AAD to allow for said User Groups to be assigned into the new list.  The question therefore is how to get new lists to populate in the TEOC Create Incident App.

**Comment by v-prigunasek** [comment]
Hi @SakwaBunyasi,

Thanks for submitting your query here. Please find below responses
1. No, it is not a PowerApp. It is a React/TeamsFx application.
2.  I assume, you are looking to pull values from the SharePoint list and populate it in the Incident Form. Unfortunately, it is not possible to integrate any other SP lists to the Incident Form other than the lists that are created as part of the TEOC application.
Please refer this guide for the customization that are allowed with very minimal code changes - https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Customizations

For the question related to adding security/user groups to the incident form - Currently, it allows the addition of Users only in the Incident form. However, we will consider your request and look for its feasibilities. If it is something that can be incorporated, we will take up that for our next release.

Please let us know if you need any additional details.

**Comment by v-prigunasek** [comment]
We are closing this ticket since we did not get any response. Please create a new ticket for any issues.
