### ISSUE TITLE
Cannot create new Incident without User Admin role

### ISSUE THREAD

**Issue by Shaun2027** [OfficeDev/microsoft-teams-emergency-operations-center#61]
We have just configured TEOC and our test users are getting this error when trying to create New Incident - 

![image](https://user-images.githubusercontent.com/118851940/203409965-72c5fb5a-d05c-482e-b693-e0c319a8e68d.png)

I tested with my account which has the User Admin role and i was able to create an Incident with no issue.
We do not use any group naming policies but we do not allow Users to create 365 groups.

We thought with the Group.ReadWrite.All permission, this would allow the app to create the group but is it actually looking to the user for their role? Are our only options to give these users User Admin role? Or would group admin work?

**Comment by v-prigunasek** [comment]
Hi @Shaun2027 ,

Thanks for reaching out to us. 
Can you please confirm whether you have Group Naming Policy in your tenant? If that is the case, the group creations will fail for all users and it just works for User Admin and Global Admin role as they are exempted from the naming policy.

Please refer this thread # [55](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/55)

**Comment by Shaun2027** [comment]
Hi @v-prigunasek 
No we do not have any group naming policies configured but we do not allow users to create m365 groups. (under Settings, General we have "Users can create Microsoft 365 groups in Azure portals, API or PowerShell" set to No). Should the Group.ReadWrite.All permission overwrite that?
Shaunagh

**Comment by v-prigunasek** [comment]
Hi @Shaun2027 ,

Thanks for sharing that information. If you have that setting enabled in your tenant, then only users in certain admin roles (Global admin, Users admin, Groups admin) can override it. 

The "Group.ReadWrite.All" permission will not override those settings, it allows the app to create groups and read all group properties and memberships on behalf of the signed-in user.

Thanks!

**Comment by Shaun2027** [comment]
Thanks @v-prigunasek.
After you confirmed the above, then we were able to use a group that has permission to create M365 groups - similar to this https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide
And this is now working for us! Thanks again

**Comment by v-prigunasek** [comment]
That sounds good. Thanks for updating us on this.
