### ISSUE TITLE
Unable to create new incident

### ISSUE THREAD

**Issue by rottenapple22** [OfficeDev/microsoft-teams-emergency-operations-center#67]
Was able to get the app installed and it appears to be working, however upon trying to create an incident I receive "An error has occurred" and it fails to create the incident.

It does create a team for the incident and then deletes it shortly after.

**Comment by v-prigunasek** [comment]
Hi @rottenapple22 ,

Thanks for reaching out to us. Can you please open the app in Teams browser version to replicate this issue and share us the console logs from the browser?

Also let us know how these below settings are configured in your tenant.
1.  Do you have any Group naming policy configured? (Azure Portal --> Groups --> Settings-->Naming Policy)
2.  Do you have this setting "Users can create Microsoft 365 groups in Azure portals, API or PowerShell" set to **No** ? (Azure Portal --> Groups --> Settings-->General)
3.  Do you have this setting "Create teams site under" set to /teams/? (SharePoint Admin Center --> Settings --> Site creation )

**Comment by rottenapple22** [comment]
Hello @v-prigunasek,

1. We do not.
2. Currently this is set to "Yes", would it be an issue in the future if it was changed to no?
3. I think this could be our issue, this is set to /teams/, I noticed in the console logs it's trying to reference the site it created using /sites, is this something we can fix

Thank you!

**Comment by v-prigunasek** [comment]
Hi @rottenapple22 ,

Thanks for providing the above information. Please find my response for #2 and #3 below.

2.  Yes, if that setting is changed to No, it will not allow the users except Global Admins or Group Admins to create M365 groups, hence incident creation will fail. However, there is a workaround to handle this scenario that would allow group of users to create M365 groups which will let them create incidents also. Please follow this article to handle this scenario -  https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide

3. Yes, for now the TEOC application will create team sites only under /sites/ path. However, we have fixed this issue and it will be available in our next release. Thereafter the TEOC application, will create team sites under /sites/ or /teams/ based on the settings applied in the tenant. FYI - We don't have a release date yet, but it will be in few months. Please do watch this repo for any new releases/updates.

**Comment by rottenapple22** [comment]
Thank you for the update, we will wait for new releases

**Comment by rottenapple22** [comment]
Any updates on when this may be patched? Thank you!

**Comment by v-prigunasek** [comment]
Hi @rottenapple22 ,

The new version 2.0 of TEOC application has been released and this issue has been fixed in that. Please follow the "Upgrade to Latest Version" from Wiki to sync the latest code and test it out. Thanks!

**Comment by cmejiaDohmh** [comment]
trying to create an incident I receive "An error has occurred" and it fails to create the incident. do the users need to have access to create groups in the tenant or the TEOC app does it? The app reg has all the rights it need to do it on behave of the user

**Comment by v-prigunasek** [comment]
Hi @cmejiaDohmh , 

Thanks for reaching out. Please confirm us on the below items.
1. Do you have any Group naming policy configured? (Azure Portal --> Groups --> Settings-->Naming Policy)
2. Do you have this setting "Users can create Microsoft 365 groups in Azure portals, API or PowerShell" set to No ? (Azure Portal --> Groups --> Settings-->General)

If any of these settings applies to your tenant, then the incident creation will fail. The app registration rights will provide permissions on behalf of users to create groups and all related resources, but it will not override this tenant level settings. 

If you don't have these settings enabled and still having issues while creating incident then please log a new issue for tracking and share us the console log for further troubleshooting on this error. Thanks!
