### ISSUE TITLE
Roadmap and deleting incidents

### ISSUE THREAD

**Issue by sheacm** [OfficeDev/microsoft-teams-emergency-operations-center#68]
Hi, I have two questions:
1.  Is there a roadmap for TEOC that I can view?  I am interested in finding out when the next version will be released and what new features will be included, particularly the ability to RBAC the incident page so that multiple EMTs can share a single TEOC app.
2. What is the proper way to delete an incident?  Is it to delete the incident from the SharePoint list and delete the associated M365 group?  We have been creating incidents for testing that we want to cleanup.  I also foresee a user possibly needing to delete an incident in the future for whatever reason.

**Comment by v-prigunasek** [comment]
Hi @sheacm,

Thanks for reaching out to us. Please find my answers below.

1. We don't have any roadmap available for public view and it will be tracked internally only. Normally we will include some new features, UI enhancements and bug fixes (if any) in our new release and it will be captured in the Release notes during every release. We don't have the date yet for our next release, but it will be in few months.

2.  Yes, you need to delete that incident item from SharePoint list, associated M365 group and then the associated team site from SharePoint admin center. Please be noted that after deleting the M365 group and team site from admin centers, it will reside in the deleted groups and deleted sites respectively for some days. So, use the PowerShell command lets to delete the group and team site permanently.
As you have mentioned, this might be a useful feature and there will be a possible need on this delete functionality. We will add this item to our backlog and based on our project timelines we will try to incorporate this feature in the application itself.

**Comment by sheacm** [comment]
Thank you for the response! Issue resolved.
