### ISSUE TITLE
Error on creating incident cant find field "incidentcommander"

### ISSUE THREAD

**Issue by rsnyder-feld** [OfficeDev/microsoft-teams-emergency-operations-center#70]
[teams.microsoft.com-1674235595204.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10470966/teams.microsoft.com-1674235595204.log)
Attached in the console logs from the web version I double-checked all my list I don't see anything wrong but I could not find a reference to the field in question.  Yes I am picking an incident commander but it like I probably screwed something else up when I built the silly thing.

**Comment by v-prigunasek** [comment]
Hi @rsnyder-feld ,

I see from the logs, that the IncidentCommander field is missing in the TEOC-IncidentTransaction list. Please check that and if that is not available, create the column manually in the list and then try creating an incident from the TEOC app.

Column Display Name: **IncidentCommander**
Column Internal Name: **IncidentCommander**
Column Type: Multiple lines of text

![image](https://user-images.githubusercontent.com/98514691/214085787-4b552dfb-dfd0-4e3c-96e4-ede34749b89b.png)

**Comment by v-prigunasek** [comment]
Closed due to inactivity. Please feel free to open a new ticket if the issue still persists.
