### ISSUE TITLE
Role Assignment fails

### ISSUE THREAD

**Issue by chunelson64** [OfficeDev/microsoft-teams-emergency-operations-center#73]
![teoc-issue-1](https://user-images.githubusercontent.com/45632940/220195902-e1f36ce4-efe9-46b1-a65d-6226417c4fec.jpg)
 I am unable to create a new incident. When I click on the Role Assignment drop down and select a role, it takes me to a blank page.

**Comment by v-prigunasek** [comment]
Hi @chunelson64 , 

Thanks for reaching out to us. 
Could you please open the TEOC application in browser version of teams and then replicate the issue and share me the console logs to investigate further on this issue?

**Comment by chunelson64** [comment]
[EOC-error-02223.txt](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10806225/EOC-error-02223.txt)

**Comment by v-prigunasek** [comment]
Thanks for sharing the logs, @chunelson64. 
Could you please Navigate to TEOC SharePoint Site--> Site Contents--> "TEOC-RoleDefaultValues" list and then share me the screenshot of the items on that list?

**Comment by chunelson64** [comment]
![image](https://user-images.githubusercontent.com/45632940/221645344-e3650d28-10bf-4a14-a77e-3cd03b9d51ab.png)

**Comment by v-prigunasek** [comment]
Thanks for sharing this, @chunelson64. Could you please confirm what version of TEOC application that you are using?

I assume you have might have recently upgraded the version (0.5 to 1.0) of the code in your App service but missed to run the upgrade PowerShell script. If you have recently Sync'ed the latest code in App service, then please run the upgrade PowerShell script as mentioned [here]( https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#1-run-the-upgrade-powershell-script) and follow the other steps if anything has not been done yet.

Please let me know if you see any issues.

**Comment by chunelson64** [comment]
Hi,

That was it. I used the older version and did not run the SPO upgrade Powershell script. Thanks so much!

**Comment by v-prigunasek** [comment]
That's perfect. Thanks for confirming.
