### ISSUE TITLE
Problem with Login via Teams App

### ISSUE THREAD

**Issue by SKasai-UCSB** [OfficeDev/microsoft-teams-emergency-operations-center#78]
We are having trouble with the Teams App deploy, where we see the app, try to access it, but when click on the 'Login' button, a window 'flashes', but nothing further.  So we may be a little confused on the step of setting up auth from the deployment instructions.  Is there any troubleshooting tips for this?

**Comment by WREMO-NZ** [comment]
> We are having trouble with the Teams App deploy, where we see the app, try to access it, but when click on the 'Login' button, a window 'flashes', but nothing further. So we may be a little confused on the step of setting up auth from the deployment instructions. Is there any troubleshooting tips for this?

Exactly the same issue here. No issues with any instructions in the deployment guide, Can add the app to a team but just can't log in. 
![Untitled](https://user-images.githubusercontent.com/127365449/223896847-5ddbe923-d4e6-4845-bc1c-52133e368c36.png)

**Comment by v-prigunasek** [comment]
Hi @SKasai-UCSB , @WREMO-NZ ,

Thanks for reaching out to us. Could you please open the TEOC app in browser version of teams and try to login to replicate the issue and then share us the console logs and network trace to get more insights about this error?

To get a console logs, please try to access the TEOC application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the console window) and then right click on the logs to Save it as a log file.

![image](https://user-images.githubusercontent.com/98514691/223915054-2ade5068-892c-4b31-80f0-60ff51a6987c.png)

![image](https://user-images.githubusercontent.com/98514691/223915112-e469bbd1-c6ef-4a15-951a-00baa3d1f6c8.png)

Open the network window and Export the log trace as HAR file.

![image](https://user-images.githubusercontent.com/98514691/223915410-e25fdb71-8b67-4b5b-b21e-f77e42cbd809.png)

Please share us these log and HAR files to further investigate on this login issue. Thanks.

**Comment by v-prigunasek** [comment]
Hi @SKasai-UCSB , @WREMO-NZ ,

Can you please confirm whether you are seeing this behavior in Teams Desktop App or Chrome Browser?

I'm seeing this behavior in Chrome browser, but it works fine in Edge. So, I would recommend you open the TEOC application in browser version of Teams in Edge to authenticate the login and then try to access the application in Teams Desktop.

Please let me know if you still see any issues. Thanks!

**Comment by SKasai-UCSB** [comment]
Okay, one of our guys noticed we may have missed a step, which was: 
----
Back under Manage, click on Manifest.

    In the editor that appears, find accessTokenAcceptedVersion and update the value from null to 2 
----
We added it, but now all we see is this:
![image](https://user-images.githubusercontent.com/76448007/224084676-5b8fe5dd-190d-44bf-bef6-ad818e3e6a39.png)
So not sure what we are suppose to be seeing.

**Comment by WREMO-NZ** [comment]
> Can you please confirm whether you are seeing this behavior in Teams Desktop App or Chrome Browser?

Same issue in both. 

Attached are the log and har files. 

[teams.microsoft.com-1678393210938.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10935755/teams.microsoft.com-1678393210938.zip)

**Comment by SKasai-UCSB** [comment]
[teoc-ts.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10936021/teoc-ts.zip)
Here is our console and network error logs.

**Comment by v-prigunasek** [comment]
> [teoc-ts.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10936021/teoc-ts.zip) Here is our console and network error logs.

Hi @SKasai-UCSB,
Thanks for sharing the logs. Can you please check the REACT_APP_SHAREPOINT_SITE_NAME configuration in your app service ? (In Azure portal, navigate to TEOC resource group, open app service and click on Configuration)


![image](https://user-images.githubusercontent.com/98514691/224220419-234e5b9f-c831-4173-9084-519b81152a95.png)

It should be just the site name **teoc**, if you have provided the full URL of the site by any chance, please update that to sitename as shown above and click ok and Save it.

Then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service.

**Comment by v-prigunasek** [comment]
> > Can you please confirm whether you are seeing this behavior in Teams Desktop App or Chrome Browser?
> 
> Same issue in both.
> 
> Attached are the log and har files.
> 
> [teams.microsoft.com-1678393210938.zip](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10935755/teams.microsoft.com-1678393210938.zip)

Hi @WREMO-NZ ,

Thanks for sharing the logs. I see there are some errors related to token. Could you please share me your contact email address, so that we can share the files over the email?
I would require the Manifest file from App registration and the Teams Manifest file to further investigate on this error. Thanks!

**Comment by SKasai-UCSB** [comment]
I performed it and it looks like it works (But did require clearing the Teams Cache (Working with a break-fix team)

We do notice that in the Teams app, the 'Go to Website' we click on it and it goes to the teoc azurewebsite with a 'Please wait' with no real response.  Should I do a console/network on that via web?

**Comment by WREMO-NZ** [comment]
@v-prigunasek 

Thanks - you can contact us at tech@wremo.nz

**Comment by SKasai-UCSB** [comment]
> > I performed it and it looks like it works (But did require clearing the Teams Cache (Working with a break-fix team)
> > We do notice that in the Teams app, the 'Go to Website' we click on it and it goes to the teoc azurewebsite with a 'Please wait' with no real response. Should I do a console/network on that via web?
> 
> Yes, that is the expected behavior when we access the azurewebsites URL. We are populating the azurewebsites URL as a default website URL. However if you wish to update it to a different URL that you want to access on click of "Go to Website" you can update this setting in the Manifest file, then rezip the folder and upload the new zip file to the Teams admin center. ![image](https://user-images.githubusercontent.com/98514691/224948948-a6c2657e-0fa2-4814-938f-fca38a355df4.png)

I want to clarify that it goes to the website, but what it loads is sitting there with a 'please wait' and a spinning wheel, which we aren't sure if this si correct or we are missing something.

**Comment by v-prigunasek** [comment]
Hi @SKasai-UCSB ,

Yes, that is correct and expected one. It will just show the spinner with 'please wait'. You are good on that part. Thanks!

**Comment by SKasai-UCSB** [comment]
> Hi @SKasai-UCSB ,
> 
> Yes, that is correct and expected one. It will just show the spinner with 'please wait'. You are good on that part. Thanks!

I see, so we should replace that websiteUrl entry with something else if we want it to go to a website then.  We were confused because we thought it was suppose to go to some functionality, but wasn't mention in the setup to change it as an option so thought it was broken because it literally did nothing but that instead of something that had functionality.
