### ISSUE TITLE
An error occurred, please try to create your incident again

### ISSUE THREAD

**Issue by ATCADS** [OfficeDev/microsoft-teams-emergency-operations-center#80]
We have one user that is getting a non-descript error regarding entering a new incident in MSTEOC. Are there logs anywhere to help facilitate troubleshooting these events?

screenshot of the error message:
![image](https://user-images.githubusercontent.com/77405614/225990296-9088c03b-69a3-41f6-a38b-0ecc3ced0b7d.png)

Thank you for your time and effort.
ATCADS

**Comment by v-prigunasek** [comment]
Hi @ATCADS,

Thanks for reaching out to us. Could you please open the TEOC app in browser version of teams and try to login to replicate the issue and then share us the console logs and network trace to get more insights about this error?

To get a console logs, please try to access the TEOC application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the console window) and then right click on the logs to Save it as a log file.

![image](https://user-images.githubusercontent.com/98514691/226243501-b2484b40-1e08-480c-8b3c-44d9a09d96e4.png)

![image](https://user-images.githubusercontent.com/98514691/226243510-763d59d0-ac79-4c17-86f8-0cbac048315f.png)

**Comment by ATCADS** [comment]
I believe we figured out what the issue. We control who can create Teams unified groups and once we added the user to that group they were able to create new incidents. Odd though, my account is not included in this group but can create incidents. Still looking why. 
Thank you again for the support.
