### ISSUE TITLE
TeamId attribute not populated

### ISSUE THREAD

**Issue by eendrulat** [OfficeDev/microsoft-teams-emergency-operations-center#81]
When creating a new incident in TEOC, the TeamId field in the 'Incident Transaction' list does not appear to get populated:
![image](https://user-images.githubusercontent.com/527590/229894936-a44acf72-785b-4349-94e9-d4132639c416.png)

**Comment by v-prigunasek** [comment]
Hi @eendrulat,

Yes, that column is no longer used in the App as we have the TeamID value populated in the TeamWebURL column itself. We have removed that column and that change will be part of the upcoming release. For upgrade scenarios, the column will be still available in the list, but we have removed that from list view.

**Comment by eendrulat** [comment]
@v-prigunasek, great, thanks for the reply
