### ISSUE TITLE
EOC Teams install I see my name but nothing inside

### ISSUE THREAD

**Issue by tc78000** [OfficeDev/microsoft-teams-emergency-operations-center#82]
I have install the EOC and follow deployment but at the end I see a blank page just with my name on it. Maybe I miss something. What do you need to help me?

**Comment by v-prigunasek** [comment]
Hi @tc78000 ,

Thanks for reaching out to us! Could you please share us the console logs to further troubleshooting on this issue?

To get a console logs, please try to access the TEOC application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the console window) and then right click on the logs to Save it as a log file.
![image](https://user-images.githubusercontent.com/98514691/230133612-89d31f9a-809e-4da3-b73c-ae464bbad7f1.png)
![image](https://user-images.githubusercontent.com/98514691/230133655-57fc7d3a-f916-427a-9b55-9dcd63e3252c.png)

**Comment by tc78000** [comment]
[teams.microsoft.com-1680724735960.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/11162595/teams.microsoft.com-1680724735960.log)

Please find the logs

**Comment by v-prigunasek** [comment]
Hi @tc78000 

Thanks for sharing the logs. Can you please check the REACT_APP_SHAREPOINT_SITE_NAME configuration in your app service ? (In Azure portal, navigate to TEOC resource group, open app service and click on Configuration)

![image](https://user-images.githubusercontent.com/98514691/230275310-1f6c2f74-bd32-4f4b-931f-ac966984c640.png)


It should be just the site name TeamsEOCSite, if you have provided the full URL of the site by any chance, please update that to sitename as shown above and click ok and Save it.

Then perform this [step](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Upgrade-to-Latest-Version#3-sync-latest-version), to get the code updated with the new site name value in your app service.

**Comment by tc78000** [comment]
Hello v-prigunasek. it is working now
