### ISSUE TITLE
Final SharePoint step: adding SP extention package: Deployment failed

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#91]
Clicked on New and/or Update.  Added package from clone.  Receive the following error after accepting the Trust Confirmation dialog.

Deployment failed.  Correlation ID: ebb5aca0-6084-d000-e46b-3c79611cd09a

FYI: Never received the Trust confirmation using "New" so I tried "Upload" and that showed the confirmation.  Regardless both give the Deployment failed error.

**Comment by v-prigunasek** [comment]
Hi @tcrobbins4 ,

Can you please check and confirm whether you have Site Collection Administrator access in the AppCatalog site? If you are not a SCA on appcatalog site, please add yourself as a SCA and try again to upload the app. Thanks!

**Comment by tcrobbins4** [comment]
Well, I am a company administrator which was already listed there, but I added myself directly and uploaded again and it appeared to work that time.
