### ISSUE TITLE
SharePoint Site is Empty

### ISSUE THREAD

**Issue by festri** [OfficeDev/microsoft-teams-emergency-operations-center#92]
After going through the setup process and deploying the app to Teams, the application says, "An error has occurred, while retrieving incidents, please refresh the app." Furthermore, the ability to create incidents is non-functional, and the "Roles" and "Incident Types" are under the "Manange" dropdown link to the SharePoint site, but the URLs are invalid. 

My initial thoughts are the SharePoint site was never provisioned correctly when running the PS script, as the site doesn't contain any files. It is unrelated to the known bug with the SharePoint site using the /teams/ instead of /sites/ in the URL, I checked that already. Any assistance is greatly appreciated!

**Comment by v-prigunasek** [comment]
Hi @festri,

Thanks for reaching out to us. 
Can you please share us the screenshot of the site contents page from the SP site? Also please let us know about the details of script and xml template that you have chosen during provisioning. Is it the New Install script or the Upgrade script? Thanks!

**Comment by v-prigunasek** [comment]
I see it did not provision any lists, can you please delete this site from SP admin center from Active Sites and then from Deleted sites too. Then try to run the script again by providing the same site name, and let me know if that works.
Please wait until you see, the App provision complete message. Provisioning will take around 20 to 30 mins.
![image](https://user-images.githubusercontent.com/98514691/235718430-da1abccd-0c04-4c9c-ad76-d5ee33ecf000.png)

Let me know if you are still having any issues with the provisioning. Thanks!

**Comment by festri** [comment]
I did that, and now it throws up the error "File not found" when I run the script.

![screenshot](https://user-images.githubusercontent.com/104092102/235722698-2a7545dd-70d2-4c91-89a2-acbadc88d115.jpg)

**Comment by v-prigunasek** [comment]
The xml file path should not contain the double quotes. Please remove it and retry again. Make sure to delete the SharePoint site from Active and Deleted Sites from SP admin before running the script again.

**Comment by festri** [comment]
That fixed it. I can't believe it was something so simple. @v-prigunasek, thanks for all your help.
