### ISSUE TITLE
Deleted Team Still Showing in Active Incidents

### ISSUE THREAD

**Issue by DoxeyS** [OfficeDev/microsoft-teams-emergency-operations-center#97]
We have just upgraded to v2 and created a new Team to verify functionality. After creating the new team, I went into the Teams admin center and deleted the first Team incident that we made. I then went into the Teams EOC application and noticed that the deleted Team's linked incident is still showing. When attempting to go into the active incident to make it inactive, it just has the loading circle constantly.

**Comment by v-prigunasek** [comment]
Hi @DoxeyS ,

To delete the incident completely, you need to delete the Team and the item associated to that incident from the TEOC-IncidentTransaction SharePoint List. Could you please delete the item from the list, so it will not be shown in the dashboard? Thanks!

Thanks again for trying the new TEOC 2.0 version. Please feel free to reach out to us if you face any issues.

**Comment by DoxeyS** [comment]
Thank you! That appears to have been what was needed! I'll close this.
